ehcache/ehcache3

- xml/src/main/java/org/ehcache/config/xml/XmlConfiguration.java
- xml/src/test/java/org/ehcache/config/xml/XmlConfigurationTest.java
- xml/src/test/resources/configs/template-cache.xml
> #255 Add Expiry Policy while constructing builder from Cache Template

- build.gradle
- core/build.gradle
- core/src/main/java/org/ehcache/EhcacheManager.java
- core/src/main/java/org/ehcache/events/CacheEventNotificationServiceImpl.java
- core/src/main/java/org/ehcache/spi/ServiceLocator.java
- core/src/test/java/org/ehcache/EhcacheManagerTest.java
- integration-test/build.gradle
Since we don't have any names related to a Ehcache instance, info logging in Ehcache.java will not be much useful.
> Adding logging for Lifecycle operations for issue #112

- api/src/main/java/org/ehcache/config/CacheConfiguration.java
- core/src/main/java/org/ehcache/CacheManagerBuilder.java
- core/src/main/java/org/ehcache/Ehcache.java
- core/src/main/java/org/ehcache/EhcacheManager.java
- core/src/main/java/org/ehcache/StandaloneCacheBuilder.java
- core/src/main/java/org/ehcache/config/BaseCacheConfiguration.java
- core/src/main/java/org/ehcache/config/CacheConfigurationBuilder.java
- core/src/main/java/org/ehcache/config/persistence/PersistenceConfiguration.java
- core/src/main/java/org/ehcache/spi/service/LocalPersistenceService.java
- impl/src/main/java/org/ehcache/internal/HeapCache.java
- impl/src/main/java/org/ehcache/internal/persistence/DefaultLocalPersistenceService.java
- impl/src/main/java/org/ehcache/internal/persistence/DefaultLocalPersistenceServiceFactory.java
- impl/src/main/resources/META-INF/services/org.ehcache.spi.service.ServiceFactory
- impl/src/test/java/org/ehcache/PersistentCacheManagerTest.java
- impl/src/test/java/org/ehcache/internal/persistence/DefaultLocalPersistenceServiceTest.java
Let me know whether that seems to do it...
> Issue #30 Persistence stuff

- impl/src/main/java/org/ehcache/internal/persistence/DefaultLocalPersistenceService.java
Closing the RandomAccessFile so that the file gets deleted.
Since the RAF was not closed, file.delete was not working on windows and in turn the test was failing.
> Fixing DefaultLocalPersistenceServiceTest.testLocksDirectoryAndUnlocks() failure on windows

- core-spi-test/src/main/java/org/ehcache/internal/store/StoreEventListenerTest.java
> #170, fixed findbug issue

- core-spi-test/src/main/java/org/ehcache/internal/store/StoreEventListenerTest.java
- impl/src/main/java/org/ehcache/internal/store/OnHeapStore.java
Adding capacity constraint check on eviction during putIfAbsent
> #270 : Fixing putIfAbsent fails to remove entry on eviction

- docs/user/107.adoc
- docs/user/common.adoc
- docs/user/ehcache.css
- docs/user/examples.adoc
- docs/user/index.adoc
- docs/user/menu.adoc
- docs/user/xml.adoc
- docs/user/xsds.adoc
- impl/src/test/java/org/ehcache/GettingStarted.java
Basic work done... Some docs are there now... input welcome!
I pushed it to http://ehcache.github.io btw, under documentation
> Issue #281 Basic user docs

- xml/src/main/java/org/ehcache/config/xml/XmlConfiguration.java
- xml/src/test/java/org/ehcache/config/xml/IntegrationConfigTest.java
- xml/src/test/resources/configs/cache-integration.xml
> Expose Cache loader/Writer Configuration at template

- 107/src/main/java/org/ehcache/jsr107/CacheResources.java
- 107/src/main/java/org/ehcache/jsr107/Eh107CacheManager.java
- 107/src/main/java/org/ehcache/jsr107/Eh107CompleteConfiguration.java
- 107/src/main/java/org/ehcache/jsr107/Eh107MutableConfiguration.java
- 107/src/test/java/org/ehcache/jsr107/Eh107JSRTemplateOverridingTest.java
- 107/src/test/resources/ehcache-107-overriding.xml
Adding in test case which verifies following condition
Template | Conf | isRead/WriteThrough | Applicable
------------ | ------------- | ------------- | -------------
Yes|No|No| None
Yes|Yes|Yes| Conf
Yes|No|Yes| Template
With this in #216 only pending task will be writing a brand new MutuableConfiguration for Ehcache.
> Adding in Cache loader/writer overriding test case for #216

- 107/src/test/java/org/ehcache/ParsesConfigExtensionTest.java
- api/src/main/java/org/ehcache/config/CacheConfiguration.java
- core/src/main/java/org/ehcache/Ehcache.java
- core/src/main/java/org/ehcache/EhcacheManager.java
- core/src/main/java/org/ehcache/StandaloneCacheBuilder.java
- core/src/main/java/org/ehcache/config/BaseCacheConfiguration.java
- core/src/main/java/org/ehcache/config/CacheConfigurationBuilder.java
- core/src/main/java/org/ehcache/config/StoreConfigurationImpl.java
- core/src/main/java/org/ehcache/spi/cache/Store.java
- core/src/test/java/org/ehcache/EhcacheManagerTest.java
- impl/src/main/java/org/ehcache/config/serializer/DefaultSerializationProviderConfiguration.java
- impl/src/main/java/org/ehcache/internal/HeapCache.java
- impl/src/main/java/org/ehcache/internal/store/OnHeapStore.java
- impl/src/main/java/org/ehcache/internal/store/disk/DiskStorageFactory.java
- impl/src/main/java/org/ehcache/internal/store/disk/DiskStore.java
- impl/src/test/java/org/ehcache/GettingStarted.java
- impl/src/test/java/org/ehcache/config/CachingTierConfigurationBuilderTest.java
- impl/src/test/java/org/ehcache/internal/store/OnHeapStoreBulkMethodsTest.java
- impl/src/test/java/org/ehcache/internal/store/OnHeapStoreByRefSPITest.java
- impl/src/test/java/org/ehcache/internal/store/OnHeapStoreByRefTest.java
- impl/src/test/java/org/ehcache/internal/store/OnHeapStoreByValueSPITest.java
- impl/src/test/java/org/ehcache/internal/store/OnHeapStoreByValueTest.java
- impl/src/test/java/org/ehcache/internal/store/OnHeapStoreEvictionTest.java
- impl/src/test/java/org/ehcache/internal/store/disk/DiskStoreSPITest.java
- integration-test/src/test/java/org/ehcache/integration/EhcacheBulkMethodsITest.java
- xml/src/main/java/org/ehcache/config/xml/ConfigurationParser.java
- xml/src/main/resources/ehcache-core.xsd
- xml/src/test/java/com/pany/ehcache/serializer/TestSerializer.java
- xml/src/test/java/org/ehcache/config/xml/XmlConfigurationTest.java
- xml/src/test/resources/configs/ehcache-serializer.xml
Lets discuss this.
This PR contains changes required for cleaning up Cache and Store configs , exposing xml to add custom serializers for default serialization provider.
> Adding Serializer for xml config #182

- build.gradle
- dist/build.gradle
* Fix and clean up dependencies in public artifact pom file
* Fix Java8 build - disable doclint and skip findbugs
> Issue #313

- README.adoc
- docs/user/107.adoc
- docs/user/examples.adoc
- docs/user/index.adoc
- docs/user/menu.adoc
- docs/user/xml.adoc
- docs/user/xsds.adoc
- impl/src/test/java/org/ehcache/GettingStarted.java
Includes description of new samples including in another PR.
> Documentation updates in preparation for OSS Beta

- core-spi-test/src/main/java/org/ehcache/internal/store/StoreProviderCreateStoreTest.java
- core/src/main/java/org/ehcache/CacheManagerBuilder.java
- core/src/main/java/org/ehcache/EhcacheManager.java
- core/src/main/java/org/ehcache/config/persistence/PersistentStoreConfigurationImpl.java
- core/src/main/java/org/ehcache/spi/cache/Store.java
- core/src/main/java/org/ehcache/spi/service/LocalPersistenceService.java
- docs/user/index.adoc
- impl/src/main/java/org/ehcache/internal/persistence/DefaultLocalPersistenceService.java
- impl/src/main/java/org/ehcache/internal/store/disk/DiskStorageFactory.java
- impl/src/main/java/org/ehcache/internal/store/disk/DiskStore.java
- impl/src/main/java/org/ehcache/internal/store/disk/DiskStorePathManager.java
- impl/src/test/java/org/ehcache/GettingStarted.java
- impl/src/test/java/org/ehcache/internal/store/disk/DiskStoreSPITest.java
- impl/src/test/java/org/ehcache/internal/store/disk/DiskStoreTest.java
- impl/src/test/java/org/ehcache/internal/store/tiering/CacheStoreSPITest.java
- xml/src/main/java/org/ehcache/config/xml/ConfigurationParser.java
- xml/src/main/resources/ehcache-core.xsd
- xml/src/test/java/org/ehcache/config/xml/XmlConfigurationTest.java
- xml/src/test/resources/configs/persistence-config.xml
Fixes on top of @alexsnaps changes
> Issue #327

- README.adoc
- build.gradle
- docs/user/index.adoc
> Issue #332

- docs/user/index.adoc
- impl/src/test/java/org/ehcache/GettingStarted.java
fix a typo introduced in m1 release doc
clarify the examples
> issue #336 added doc refinements

- xml/src/main/resources/ehcache-core.xsd
This TODO could only be achieved with Schematron.
All Hail Schematron.
> Issue #354 : Todo cannot be done (technically impossible)

- core/src/main/java/org/ehcache/events/CacheEventNotificationServiceImpl.java
Simple change to reduce logging content.
> issue-298: Change to improve logging

- core/src/main/java/org/ehcache/UserManagedCacheBuilder.java
- core/src/main/java/org/ehcache/config/CacheConfigurationBuilder.java
- core/src/main/java/org/ehcache/config/ResourcePoolsBuilder.java
- core/src/test/java/org/ehcache/config/CacheConfigurationBuilderTest.java
- impl/src/test/java/org/ehcache/GettingStarted.java
- impl/src/test/java/org/ehcache/loaderwriter/writebehind/WriteBehindEvictionTest.java
- impl/src/test/java/org/ehcache/statistics/StatisticsTest.java
- integration-test/src/test/java/org/ehcache/integration/EvictionEhcacheTest.java
- integration-test/src/test/java/org/ehcache/integration/UserManagedCacheEvictionTest.java
- xml/src/main/java/org/ehcache/config/xml/XmlConfiguration.java
* Always copy when modifying
* Accept a builder instance in place of ResourcePools in related builders
First step for #391
> Issue #391 Clean up ResourcePoolsBuilder

- core-spi-test/src/main/java/org/ehcache/internal/store/StoreProviderCreateStoreTest.java
- impl/src/main/java/org/ehcache/internal/persistence/DefaultLocalPersistenceService.java
- impl/src/test/java/org/ehcache/GettingStarted.java
- impl/src/test/java/org/ehcache/internal/store/disk/DiskStoreSPITest.java
- impl/src/test/java/org/ehcache/internal/store/offheap/OffHeapStoreSPITest.java
- impl/src/test/java/org/ehcache/internal/store/tiering/CacheStoreSPITest.java
Throwing IllegalArgumentException when PersistenceConfiguration is null and added logging
> Issue #349 : Improve `DefaultLocalPersistenceProvider`

- core/src/main/java/org/ehcache/config/writebehind/WriteBehindConfiguration.java
- core/src/main/java/org/ehcache/config/writebehind/WriteBehindConfigurationBuilder.java
- docs/user/index.adoc
- impl/src/test/java/org/ehcache/GettingStarted.java
- impl/src/test/java/org/ehcache/loaderwriter/writebehind/WriteBehindEvictionTest.java
- impl/src/test/java/org/ehcache/loaderwriter/writebehind/WriteBehindTest.java
- xml/src/main/java/org/ehcache/config/xml/XmlConfiguration.java
This needs to go in for #253 to complete
> Getting started example for write behind #253

- core/src/main/java/org/ehcache/config/writebehind/WriteBehindConfigurationBuilder.java
- impl/src/test/java/org/ehcache/loaderwriter/writebehind/WriteBehindEvictionTest.java
- impl/src/test/java/org/ehcache/loaderwriter/writebehind/WriteBehindTest.java
Looks like I missed that change in the previous PR.
Should be really done now ...
> Issue #391 Fix return type of WriteBehindConfigurationBuilder.build()

- 107/config/findbugs-excludes.xml
- 107/src/main/java/org/ehcache/jsr107/Eh107Cache.java
- 107/src/main/java/org/ehcache/jsr107/Eh107CacheManager.java
- 107/src/main/java/org/ehcache/jsr107/Eh107CompleteConfiguration.java
- 107/src/main/java/org/ehcache/jsr107/Eh107Configuration.java
- 107/src/main/java/org/ehcache/jsr107/Eh107ReverseConfiguration.java
- 107/src/test/java/org/ehcache/docs/EhCache107ConfigurationIntegrationTest.java
- 107/src/test/java/org/ehcache/jsr107/Eh107JSRTemplateOverridingTest.java
- build.gradle
- docs/user/107.adoc
This covers part of issue #216.
The use of Ehcache 3 templates will be in another pull request.
> Issue #216 CacheConfiguration to JSR-107 Configuration bridging

- core/src/main/java/org/ehcache/events/CacheEventNotificationListenerServiceProvider.java
- core/src/main/java/org/ehcache/util/ResourcePoolMerger.java
- core/src/test/java/org/ehcache/CacheConfigurationChangeListenerTest.java
- core/src/test/java/org/ehcache/util/ResourcePoolsMergerTest.java
- impl/src/test/java/org/ehcache/RuntimeConfigurationTest.java
Adding ResourceUnit validation
> Issue #320 : Add capacity constraint to `RuntimeConfig`

- core-spi-test/src/main/java/org/ehcache/internal/tier/AuthoritativeTierFlush.java
- core-spi-test/src/main/java/org/ehcache/internal/tier/CachingTierClear.java
- core-spi-test/src/main/java/org/ehcache/internal/tier/CachingTierRemove.java
- core/src/main/java/org/ehcache/spi/cache/AbstractValueHolder.java
- core/src/main/java/org/ehcache/spi/cache/Store.java
- core/src/main/java/org/ehcache/spi/cache/tiering/CachingTier.java
- core/src/test/java/org/ehcache/EhcacheBasicCrudBase.java
- core/src/test/java/org/ehcache/EhcacheBulkMethodsTest.java
- core/src/test/java/org/ehcache/EhcacheTest.java
- core/src/test/java/org/ehcache/spi/cache/AbstractValueHolderTest.java
- impl/src/main/java/org/ehcache/internal/store/disk/DiskStorageFactory.java
- impl/src/main/java/org/ehcache/internal/store/disk/Segment.java
- impl/src/main/java/org/ehcache/internal/store/heap/ByRefOnHeapValueHolder.java
- impl/src/main/java/org/ehcache/internal/store/heap/ByValueOnHeapValueHolder.java
- impl/src/main/java/org/ehcache/internal/store/heap/OnHeapStore.java
- impl/src/main/java/org/ehcache/internal/store/heap/OnHeapValueHolder.java
- impl/src/main/java/org/ehcache/internal/store/offheap/EhcacheConcurrentOffHeapClockCache.java
- impl/src/main/java/org/ehcache/internal/store/offheap/OffHeapStore.java
- impl/src/main/java/org/ehcache/internal/store/offheap/OffHeapValueHolder.java
- impl/src/main/java/org/ehcache/internal/store/offheap/factories/EhcacheSegmentFactory.java
- impl/src/main/java/org/ehcache/internal/store/offheap/portability/OffHeapValueHolderPortability.java
- impl/src/main/java/org/ehcache/internal/store/tiering/CacheStore.java
- impl/src/test/java/org/ehcache/internal/store/disk/DiskStoreTest.java
- impl/src/test/java/org/ehcache/internal/store/heap/BaseOnHeapStoreTest.java
- impl/src/test/java/org/ehcache/internal/store/offheap/OffHeapStoreSPITest.java
- impl/src/test/java/org/ehcache/internal/store/offheap/OffHeapStoreTest.java
- impl/src/test/java/org/ehcache/internal/store/offheap/OffHeapValueHolderPortabilityTest.java
- impl/src/test/java/org/ehcache/internal/store/tiering/CacheStoreSPITest.java
- impl/src/test/java/org/ehcache/internal/store/tiering/CacheStoreTest.java
... but am still in the process of adding tests... 
Also, one thing isn't entirely clear to me yet: notifying on expire when flushing. 
This is based off the PR for #436 - definitely can't be merged yet!
> PR on Issue #373

- impl/src/main/java/org/ehcache/internal/store/offheap/OffHeapValueHolder.java
writeContext needs to be flushed
> Issue #252 Fix OffHeapValueHolder.writeBack()

- build.gradle
- core-spi-test/src/main/java/org/ehcache/internal/store/StoreComputeTest.java
- core-spi-test/src/main/java/org/ehcache/internal/store/StoreFactory.java
- core-spi-test/src/main/java/org/ehcache/internal/tier/AuthoritativeTierComputeIfAbsentAndFault.java
- core-spi-test/src/main/java/org/ehcache/internal/tier/AuthoritativeTierFactory.java
- core-spi-test/src/main/java/org/ehcache/internal/tier/AuthoritativeTierGetAndFault.java
- impl/src/main/java/org/ehcache/internal/persistence/DefaultLocalPersistenceService.java
- impl/src/main/java/org/ehcache/internal/store/disk/EhcachePersistentConcurrentOffHeapClockCache.java
- impl/src/main/java/org/ehcache/internal/store/disk/OffHeapDiskStore.java
- impl/src/main/java/org/ehcache/internal/store/disk/factories/EhcachePersistentSegmentFactory.java
- impl/src/main/java/org/ehcache/internal/store/offheap/AbstractOffHeapStore.java
- impl/src/main/java/org/ehcache/internal/store/offheap/EhcacheOffHeapBackingMap.java
- impl/src/main/java/org/ehcache/internal/store/offheap/factories/EhcacheSegmentFactory.java
- impl/src/test/java/org/ehcache/internal/persistence/DefaultLocalPersistenceServiceTest.java
- impl/src/test/java/org/ehcache/internal/store/disk/OffHeapDiskStoreSPITest.java
- impl/src/test/java/org/ehcache/internal/store/disk/OffHeapDiskStoreTest.java
- impl/src/test/java/org/ehcache/internal/store/disk/factories/EhcachePersistentSegmentTest.java
- impl/src/test/java/org/ehcache/internal/store/heap/OnHeapStoreByRefSPITest.java
- impl/src/test/java/org/ehcache/internal/store/heap/OnHeapStoreByValueSPITest.java
- impl/src/test/java/org/ehcache/internal/store/offheap/OffHeapStoreSPITest.java
- impl/src/test/java/org/ehcache/internal/store/offheap/factories/EhcacheSegmentTest.java
- impl/src/test/java/org/ehcache/internal/store/tiering/CacheStoreSPITest.java
This is an initial cut.  I'd like some review of the changes here... but I plan on adding some more test coverage before anyone merges it.
> Issue 442 Initial cut of offheap disk store byte based capacity eviction

- core-spi-test/src/main/java/org/ehcache/internal/tier/AuthoritativeTierFlush.java
- core-spi-test/src/main/java/org/ehcache/internal/tier/CachingTierClear.java
- core-spi-test/src/main/java/org/ehcache/internal/tier/CachingTierFactory.java
- core-spi-test/src/main/java/org/ehcache/internal/tier/CachingTierGetOrComputeIfAbsent.java
- core-spi-test/src/main/java/org/ehcache/internal/tier/CachingTierRemove.java
- core/src/main/java/org/ehcache/spi/cache/tiering/CachingTier.java
- core/src/main/java/org/ehcache/spi/cache/tiering/LowerCachingTier.java
- docs/src/docs/asciidoc/user/index.adoc
- impl/src/main/java/org/ehcache/internal/store/DefaultStoreProvider.java
- impl/src/main/java/org/ehcache/internal/store/heap/OnHeapStore.java
- impl/src/main/java/org/ehcache/internal/store/offheap/AbstractOffHeapStore.java
- impl/src/main/java/org/ehcache/internal/store/offheap/OffHeapStore.java
- impl/src/main/java/org/ehcache/internal/store/tiering/CacheStore.java
- impl/src/main/java/org/ehcache/internal/store/tiering/CompoundCachingTier.java
- impl/src/main/java/org/ehcache/internal/store/tiering/CompoundCachingTierProviderFactory.java
- impl/src/main/java/org/ehcache/internal/store/tiering/CompoundCachingTierServiceConfiguration.java
- impl/src/main/resources/META-INF/services/org.ehcache.spi.service.ServiceFactory
- impl/src/test/java/org/ehcache/docs/GettingStarted.java
- impl/src/test/java/org/ehcache/internal/store/heap/OnHeapStoreCachingTierByRefSPITest.java
- impl/src/test/java/org/ehcache/internal/store/offheap/AbstractOffHeapStoreTest.java
- impl/src/test/java/org/ehcache/internal/store/offheap/OffHeapStoreLifecycleHelper.java
- impl/src/test/java/org/ehcache/internal/store/offheap/OffHeapStoreSPITest.java
- impl/src/test/java/org/ehcache/internal/store/tiering/CacheStoreWith3TiersSPITest.java
- impl/src/test/java/org/ehcache/internal/store/tiering/CompoundCachingTierSPITest.java
- impl/src/test/java/org/ehcache/internal/store/tiering/CompoundCachingTierTest.java
> Issue #367 - done and waiting to be reviewed

- README.adoc
- docs/src/docs/asciidoc/user/index.adoc
> Update to docs for release

- 107/src/main/java/org/ehcache/jsr107/ServiceConfigurationParser.java
... no test. Does it fly without one?
> Issue #466 Ignore non element nodes

- 107/src/main/java/org/ehcache/jsr107/EhcacheCachingProvider.java
- 107/src/test/java/org/ehcache/ParsesConfigurationExtensionTest.java
- core/src/main/java/org/ehcache/CacheManagerBuilder.java
- core/src/main/java/org/ehcache/EhcacheManager.java
- core/src/test/java/org/ehcache/EhcacheManagerTest.java
> Hide ServiceLocator from EhcacheManager constructor

- core/src/main/java/org/ehcache/spi/ServiceLocator.java
- core/src/test/java/org/ehcache/spi/ServiceLocatorTest.java
* defer to when the ServiceLocater starts all services
> Issue #561 Fix services dependencies loading

- impl/src/main/java/org/ehcache/internal/store/tiering/CompoundCachingTier.java
- impl/src/test/java/org/ehcache/internal/store/tiering/CompoundCachingTierTest.java
* Pass service configs to tiers creation
> Issue #566 Fix CompoundCachingTier.Provider

- core/src/main/java/org/ehcache/EhcacheManager.java
- core/src/main/java/org/ehcache/spi/LifeCycledAdapter.java
- core/src/main/java/org/ehcache/util/LifeCycleUtils.java
- core/src/test/java/org/ehcache/StatusTransitionerTest.java
> Issue #549 - Add a LifeCycledAdapter to simplify writing LifeCycled anonymous-class

- core/src/main/java/org/ehcache/EhcacheManager.java
- core/src/test/java/org/ehcache/EhcacheManagerTest.java
Unit test and fix for Issue #571
> Issue#571 - Cannot exit maintenance mode

- core/src/main/java/org/ehcache/spi/ServiceLocator.java
- core/src/test/java/org/ehcache/spi/ServiceLocatorTest.java
- core/src/test/java/org/ehcache/spi/services/DefaultTestProvidedService.java
- core/src/test/java/org/ehcache/spi/services/TestProvidedService.java
- core/src/test/java/org/ehcache/spi/services/TestProvidedServiceFactory.java
- core/src/test/resources/META-INF/services/org.ehcache.spi.service.ServiceFactory
* Restore startAllServices contract
> Issue #569 Fix multiple service startups

- core/src/main/java/org/ehcache/EhcacheManager.java
of serializer not found error message for OnHeap caches
> Issue #577 Downgrading the log level

- docs/src/docs/asciidoc/user/getting-started.adoc
With custom `Transient` only and `Persistent` only serializer implementations.
> Custom serializers documentation

- impl/src/main/java/org/ehcache/internal/classes/ClassInstanceProvider.java
- impl/src/main/java/org/ehcache/internal/copy/SerializingCopier.java
- impl/src/main/java/org/ehcache/spi/copy/DefaultCopyProvider.java
- impl/src/test/java/org/ehcache/docs/GettingStarted.java
- impl/src/test/java/org/ehcache/internal/classes/ClassInstanceProviderTest.java
- impl/src/test/java/org/ehcache/internal/copy/SerializingCopierTest.java
Couple of ugly things in here. See inline comments.
> Issue #605 Wired Serializer in all DefaultCopyProvider paths

- core/src/main/java/org/ehcache/EhcacheManager.java
- core/src/main/java/org/ehcache/config/DefaultConfiguration.java
- core/src/test/java/org/ehcache/EhcacheManagerTest.java
Could be overly cautious in maintaining the DefaultCache.caches map, let me know...
> Issue #585 CM RuntimeCfg exposes CacheRuntimeCfg

- 107/src/main/java/org/ehcache/jsr107/Jsr107ServiceConfigurationParser.java
- 107/src/main/resources/ehcache-107ext.xsd
- 107/src/test/resources/ehcache-107-integration.xml
- 107/src/test/resources/ehcache-107-listeners.xml
- 107/src/test/resources/ehcache-example.xml
- 107/src/test/resources/ehcache-loader-writer-107-load-atomics.xml
- 107/src/test/resources/org/ehcache/docs/ehcache-jsr107-config.xml
- docs/src/docs/asciidoc/user/xml.adoc
- xml/src/main/java/org/ehcache/config/xml/ConfigurationParser.java
- xml/src/main/resources/ehcache-core.xsd
- xml/src/test/resources/configs/cache-integration.xml
- xml/src/test/resources/configs/defaultTypes-cache.xml
- xml/src/test/resources/configs/ehcache-cacheEventListener.xml
- xml/src/test/resources/configs/ehcache-multipleCacheEventListener.xml
- xml/src/test/resources/configs/getting-started.xml
- xml/src/test/resources/configs/nonExistentVeto-template.xml
- xml/src/test/resources/configs/prioritizer-cache.xml
- xml/src/test/resources/configs/resources-templates.xml
- xml/src/test/resources/configs/template-cache.xml
- xml/src/test/resources/configs/writebehind-cache.xml
... on words separated by dash
> Issue #548 Align XML element, attribute and XSD type names

- osgi-test/config/checkstyle-suppressions.xml
Add the required config files for static checks
> Issue #614 Fix static checks

- impl/src/main/java/org/ehcache/internal/store/heap/OnHeapStore.java
- impl/src/test/java/org/ehcache/internal/store/heap/BaseOnHeapStoreTest.java
* Eviction notification now happens under lock
* Expiry notification from the iterator now happens under lock
> Issue #641 Fix higher caching tier concurrent contract

- core/src/main/java/org/ehcache/spi/cache/tiering/LowerCachingTier.java
- core/src/main/java/org/ehcache/statistics/AuthoritativeTierOperationOutcomes.java
- core/src/main/java/org/ehcache/statistics/CachingTierOperationOutcomes.java
- core/src/main/java/org/ehcache/statistics/HigherCachingTierOperationOutcomes.java
- core/src/main/java/org/ehcache/statistics/LowerCachingTierOperationsOutcome.java
- core/src/main/java/org/ehcache/statistics/StoreOperationOutcomes.java
- impl/src/main/java/org/ehcache/internal/store/heap/OnHeapStore.java
- impl/src/main/java/org/ehcache/internal/store/offheap/AbstractOffHeapStore.java
- impl/src/main/java/org/ehcache/internal/store/tiering/CompoundCachingTier.java
- impl/src/test/java/org/ehcache/internal/store/heap/BaseOnHeapStoreTest.java
- impl/src/test/java/org/ehcache/internal/store/offheap/AbstractOffHeapStoreTest.java
- impl/src/test/java/org/ehcache/internal/store/tiering/CompoundCachingTierTest.java
- impl/src/test/java/org/ehcache/internal/util/StatisticsTestUtils.java
This PR creates statistics for the store operations. It does not yet resolve the creation of a compound counter to expose a usefulness statistic from a given tier.
> Issue #615 Store operations statistics

- management/src/test/java/org/ehcache/management/registry/DefaultManagementRegistryTest.java
@ljacomet : I have simplified the test with the help of @chrisdennis . I "hope" it will pass now...
> Fixed unit tests not passing when machine is slow

- core/src/main/java/org/ehcache/Ehcache.java
- impl/src/main/java/org/ehcache/internal/store/heap/OnHeapStore.java
- impl/src/main/java/org/ehcache/internal/store/offheap/AbstractOffHeapStore.java
- impl/src/test/java/org/ehcache/internal/store/heap/BaseOnHeapStoreTest.java
- impl/src/test/java/org/ehcache/internal/store/heap/OnHeapStoreCachingTierByRefSPITest.java
- impl/src/test/java/org/ehcache/internal/store/heap/OnHeapStoreCachingTierByValueSPITest.java
- impl/src/test/java/org/ehcache/internal/store/offheap/AbstractOffHeapStoreTest.java
- impl/src/test/java/org/ehcache/internal/store/tiering/CompoundCachingTierSPITest.java
- transactions/src/main/java/org/ehcache/transactions/xa/XAStore.java
- transactions/src/test/java/org/ehcache/transactions/xa/XAStoreTest.java
Replacing the PR opened by @rishabhmonga:
* merged all commits from @rishabhmonga into a single one
* Fixed last remark on PR #665 in a new commit
> Issue #133 Handle exceptions from Expiry calls

- xml/src/main/java/org/ehcache/config/xml/XmlConfiguration.java
> issue-690: remove unused private method

- build.gradle
- management/src/main/java/org/ehcache/management/providers/ManagementProvider.java
Also removed that rogue character ...
> Issue #691 Specify encoding for compiler and javadoc

- CONTRIBUTING.adoc
This enables a link to appear in the GitHub UI when creating an issue
or a pull request linking to this content.
> Add a CONTRIBUTING page to the repository

- core/src/main/java/org/ehcache/Ehcache.java
- core/src/main/java/org/ehcache/UserManagedCacheBuilder.java
- core/src/main/java/org/ehcache/spi/service/ExecutionService.java
- core/src/test/java/org/ehcache/EhcacheBasicClearTest.java
- core/src/test/java/org/ehcache/EhcacheBasicContainsKeyTest.java
- core/src/test/java/org/ehcache/EhcacheBasicCrudBase.java
- core/src/test/java/org/ehcache/EhcacheBasicGetAllTest.java
- core/src/test/java/org/ehcache/EhcacheBasicGetTest.java
- core/src/test/java/org/ehcache/EhcacheBasicIteratorTest.java
- core/src/test/java/org/ehcache/EhcacheBasicPutAllTest.java
- core/src/test/java/org/ehcache/EhcacheBasicPutIfAbsentTest.java
- core/src/test/java/org/ehcache/EhcacheBasicPutTest.java
- core/src/test/java/org/ehcache/EhcacheBasicRemoveAllTest.java
- core/src/test/java/org/ehcache/EhcacheBasicRemoveTest.java
- core/src/test/java/org/ehcache/EhcacheBasicRemoveValueTest.java
- core/src/test/java/org/ehcache/EhcacheBasicReplaceTest.java
- core/src/test/java/org/ehcache/EhcacheBasicReplaceValueTest.java
- core/src/test/java/org/ehcache/EhcacheBulkMethodsTest.java
- core/src/test/java/org/ehcache/EhcacheLoaderWriterTest.java
- core/src/test/java/org/ehcache/EhcacheTest.java
- impl/src/main/java/org/ehcache/config/executor/PooledExecutionServiceConfiguration.java
- impl/src/main/java/org/ehcache/internal/events/CacheEventDispatcherFactoryImpl.java
- impl/src/main/java/org/ehcache/internal/executor/OnDemandExecutionService.java
- impl/src/main/java/org/ehcache/internal/executor/PooledExecutionService.java
- impl/src/main/java/org/ehcache/internal/util/ThreadFactoryUtil.java
- impl/src/test/java/org/ehcache/internal/executor/PooledExecutionServiceTest.java
- integration-test/src/test/java/org/ehcache/integration/ThreadPoolsTest.java
Added warning on dubious config, refactored null usage and added unit and integration tests in the area of thread pools.
> issue-689: Refactor thread pools wiring

- impl/src/main/java/org/ehcache/internal/store/heap/OnHeapStore.java
Invalidation needs to happen strictly under key exclusive access
otherwise the contract between higher and lower caching tiers can be
violated.
> Issue #715 Fix invalidation invocation

- 107/src/test/resources/ehcache-107-default-copiers.xml
- 107/src/test/resources/ehcache-107-integration.xml
- 107/src/test/resources/ehcache-107-listeners.xml
- 107/src/test/resources/ehcache-107-serializer.xml
- 107/src/test/resources/ehcache-107-stats.xml
- 107/src/test/resources/ehcache-107-types.xml
- 107/src/test/resources/ehcache-107.xml
- 107/src/test/resources/ehcache-example.xml
- 107/src/test/resources/ehcache-loader-writer-107-load-atomics.xml
- 107/src/test/resources/ehcache-loader-writer-107.xml
- 107/src/test/resources/org/ehcache/docs/ehcache-jsr107-config.xml
- 107/src/test/resources/org/ehcache/docs/ehcache-jsr107-template-override.xml
- osgi-test/src/test/resources/org/ehcache/osgi/ehcache-107-osgi.xml
- osgi-test/src/test/resources/org/ehcache/osgi/ehcache-osgi.xml
- transactions/src/test/resources/configs/simple-xa.xml
- transactions/src/test/resources/docs/configs/xa-getting-started.xml
- xml/src/main/java/org/ehcache/config/xml/ConfigurationParser.java
- xml/src/main/java/org/ehcache/config/xml/XmlConfiguration.java
- xml/src/main/resources/ehcache-core.xsd
- xml/src/test/resources/configs/cache-copiers.xml
- xml/src/test/resources/configs/cache-integration.xml
- xml/src/test/resources/configs/default-serializer.xml
- xml/src/test/resources/configs/ehcache-cacheEventListener.xml
- xml/src/test/resources/configs/ehcache-complete.xml
- xml/src/test/resources/configs/ehcache-multipleCacheEventListener.xml
- xml/src/test/resources/configs/getting-started.xml
- xml/src/test/resources/configs/resources-caches.xml
- xml/src/test/resources/configs/resources-templates.xml
- xml/src/test/resources/configs/sizeof-engine.xml
- xml/src/test/resources/configs/writebehind-cache.xml
Applying some consistency at the XML configuration
> Issue #703

- clustered/ops-tool/build.gradle
- clustered/ops-tool/config/checkstyle-suppressions.xml
- clustered/ops-tool/gradle.properties
- clustered/ops-tool/src/main/java/org/ehcache/clustered/operations/AbstractCommand.java
- clustered/ops-tool/src/main/java/org/ehcache/clustered/operations/BaseOptions.java
- clustered/ops-tool/src/main/java/org/ehcache/clustered/operations/Command.java
- clustered/ops-tool/src/main/java/org/ehcache/clustered/operations/CreateCacheManager.java
- clustered/ops-tool/src/main/java/org/ehcache/clustered/operations/DestroyCacheManager.java
- clustered/ops-tool/src/main/java/org/ehcache/clustered/operations/ListCacheManagers.java
- clustered/ops-tool/src/main/java/org/ehcache/clustered/operations/OperationsTool.java
- clustered/ops-tool/src/main/java/org/ehcache/clustered/operations/URIConverter.java
- clustered/ops-tool/src/main/java/org/ehcache/clustered/operations/UpdateCacheManager.java
- clustered/ops-tool/src/test/java/org/ehcache/clustered/operations/OperationsToolTest.java
This is the stubbed out version of the operator tool CLI.  This doesn't close the associated issue, but once accepted it does settle the API.
> Issue #738 Initial CLI Skeleton

- docs/src/docs/asciidoc/user/getting-started.adoc
- docs/src/docs/asciidoc/user/menu.adoc
- docs/src/docs/asciidoc/user/thread-pools.adoc
- impl/src/main/java/org/ehcache/CacheManagerBuilder.java
- impl/src/main/java/org/ehcache/config/CacheConfigurationBuilder.java
- impl/src/main/java/org/ehcache/internal/executor/PooledExecutionServiceConfigurationBuilder.java
- impl/src/test/java/org/ehcache/docs/GettingStarted.java
- impl/src/test/java/org/ehcache/docs/ThreadPools.java
- xml/src/test/resources/configs/docs/getting-started.xml
- xml/src/test/resources/configs/docs/thread-pools.xml
Please note that my #165 PR is required before this can be merged.
> #688: thread pools documentation

- 107/build.gradle
- 107/src/main/java/org/ehcache/jsr107/ConfigurationMerger.java
- api/src/main/java/org/ehcache/event/EventOrdering.java
- api/src/main/java/org/ehcache/spi/loaderwriter/WriteBehindConfiguration.java
- build.gradle
- buildSrc/src/main/groovy/EhDistribute.groovy
- impl/src/main/java/org/ehcache/config/builders/CacheConfigurationBuilder.java
- impl/src/main/java/org/ehcache/config/builders/CacheEventListenerConfigurationBuilder.java
- impl/src/main/java/org/ehcache/config/builders/CacheManagerBuilder.java
- impl/src/main/java/org/ehcache/config/builders/CacheManagerConfiguration.java
- impl/src/main/java/org/ehcache/config/builders/ConfigurationBuilder.java
- impl/src/main/java/org/ehcache/config/builders/PooledExecutionServiceConfigurationBuilder.java
- impl/src/main/java/org/ehcache/config/builders/ResourcePoolsBuilder.java
- impl/src/main/java/org/ehcache/config/builders/UserManagedCacheBuilder.java
- impl/src/main/java/org/ehcache/config/builders/UserManagedCacheConfiguration.java
- impl/src/main/java/org/ehcache/config/builders/WriteBehindConfigurationBuilder.java
- impl/src/main/java/org/ehcache/config/builders/package-info.java
- impl/src/test/java/org/ehcache/config/builders/CacheConfigurationBuilderTest.java
- impl/src/test/java/org/ehcache/docs/GettingStarted.java
- xml/src/test/java/org/ehcache/xml/FromTemplateCacheConfigurationBuilderDefaultTest.java
* Remove javadoc for `internal` packages
* Javadoc for builders
* Misc clean ups
This is a first part of the work needed for #776, more to come.
> Issue #776 Builders javadoc

- clustered/client/src/main/java/org/ehcache/clustered/client/EhcacheClientEntityFactory.java
- clustered/client/src/main/resources/META-INF/services/org.terracotta.entity.EntityClientService
- clustered/dist/build.gradle
- clustered/integration-test/src/test/java/org/ehcache/clustered/BasicEntityInteractionTest.java
- clustered/integration-test/src/test/java/org/ehcache/clustered/PassThroughEhcacheIntegrationTest.java
- clustered/server/src/main/java/org/ehcache/clustered/server/EhcacheServerEntityService.java
- clustered/server/src/main/resources/META-INF/services/org.terracotta.entity.ServerEntityService
Initial cut of the Ehcache kitting code... requires a fix to Terracotta-OSS/terracotta-platform but should be otherwise okay.
> Issue #724

- impl/src/test/java/org/ehcache/impl/internal/store/heap/BaseOnHeapStoreTest.java
When the test fails because of the timeout, a thread dump will be
printed which should allow to determine if anything is broken in that
test or if it fails because of a slow environment.
> Issue #775 Add test timeout to print thread dump

- core/src/main/java/org/ehcache/spi/cache/tiering/BinaryValueHolder.java
- impl/src/main/java/org/ehcache/impl/internal/store/disk/EhcachePersistentConcurrentOffHeapClockCache.java
- impl/src/main/java/org/ehcache/impl/internal/store/disk/factories/EhcachePersistentSegmentFactory.java
- impl/src/main/java/org/ehcache/impl/internal/store/heap/OnHeapStore.java
- impl/src/main/java/org/ehcache/impl/internal/store/heap/holders/SerializedOnHeapValueHolder.java
- impl/src/main/java/org/ehcache/impl/internal/store/offheap/AbstractOffHeapStore.java
- impl/src/main/java/org/ehcache/impl/internal/store/offheap/BasicOffHeapValueHolder.java
- impl/src/main/java/org/ehcache/impl/internal/store/offheap/BinaryOffHeapValueHolder.java
- impl/src/main/java/org/ehcache/impl/internal/store/offheap/EhcacheConcurrentOffHeapClockCache.java
- impl/src/main/java/org/ehcache/impl/internal/store/offheap/EhcacheOffHeapBackingMap.java
- impl/src/main/java/org/ehcache/impl/internal/store/offheap/LazyOffHeapValueHolder.java
- impl/src/main/java/org/ehcache/impl/internal/store/offheap/OffHeapValueHolder.java
- impl/src/main/java/org/ehcache/impl/internal/store/offheap/factories/EhcacheSegmentFactory.java
- impl/src/main/java/org/ehcache/impl/internal/store/offheap/portability/OffHeapValueHolderPortability.java
- impl/src/test/java/org/ehcache/impl/config/serializer/SerializerCountingTest.java
- impl/src/test/java/org/ehcache/impl/internal/store/disk/OffHeapDiskStoreSPITest.java
- impl/src/test/java/org/ehcache/impl/internal/store/offheap/AbstractEhcacheOffHeapBackingMapTest.java
- impl/src/test/java/org/ehcache/impl/internal/store/offheap/BasicOffHeapValueHolderTest.java
- impl/src/test/java/org/ehcache/impl/internal/store/offheap/BinaryOffHeapValueHolderTest.java
- impl/src/test/java/org/ehcache/impl/internal/store/offheap/LazyOffHeapValueHolderTest.java
- impl/src/test/java/org/ehcache/impl/internal/store/offheap/OffHeapStoreSPITest.java
- impl/src/test/java/org/ehcache/impl/internal/store/offheap/OffHeapValueHolderPortabilityTest.java
- impl/src/test/java/org/ehcache/impl/internal/store/offheap/OffHeapValueHolderTest.java
This is a proposition for a solution to issue #799.
It was refused back when in the context of #369 as the number of deserialisation that we gained were not that high.
However in the face of performance test results, I believe it is worth having the discussion again.
Note that the real effectiveness of this change depends on the outcome of #790
> Issue #799 Lazy OffHeapValueHolder deserialization

- integration-test/src/test/java/org/ehcache/integration/transactions/xa/SampleLoaderWriter.java
- integration-test/src/test/java/org/ehcache/integration/transactions/xa/XACacheTest.java
- transactions/src/main/java/org/ehcache/transactions/xa/internal/XAStore.java
- transactions/src/main/java/org/ehcache/transactions/xa/internal/XATransactionContext.java
- transactions/src/test/java/org/ehcache/transactions/xa/internal/XAStoreTest.java
putIfAbsent, remove(2args) and XA cache iterator have been fixed. replace 2 and 3 args are still missing.
> Issue 829: a bunch of fixes to the XA store

- NOTICE
- build.gradle
- buildSrc/src/main/groovy/EhDistribute.groovy
- impl/build.gradle
* All jar files produced contain the LICENSE file
* impl module and all distributions include NOTICE file
* Fix package in NOTICE file
> Issue #839 Include license and notice files

- core-spi-test/src/main/java/org/ehcache/internal/store/StoreComputeIfAbsentTest.java
- core-spi-test/src/main/java/org/ehcache/internal/store/StoreComputeTest.java
- core-spi-test/src/main/java/org/ehcache/internal/store/StoreGetTest.java
- core-spi-test/src/main/java/org/ehcache/internal/store/StorePutIfAbsentTest.java
- core-spi-test/src/main/java/org/ehcache/internal/store/StorePutTest.java
- core/src/main/java/org/ehcache/core/spi/cache/Store.java
- impl/src/main/java/org/ehcache/impl/internal/store/heap/OnHeapStore.java
- impl/src/main/java/org/ehcache/impl/internal/store/offheap/AbstractOffHeapStore.java
- impl/src/test/java/org/ehcache/impl/internal/store/heap/BaseOnHeapStoreTest.java
- impl/src/test/java/org/ehcache/impl/internal/store/heap/bytesized/ByteAccountingTest.java
- impl/src/test/java/org/ehcache/impl/internal/store/offheap/AbstractOffHeapStoreTest.java
- transactions/src/test/java/org/ehcache/transactions/xa/internal/XAStoreTest.java
* implement inline expiry
* proper return contracts for different methods in the face of inline expiry
* Added SPITests where relevant
> Issue #825: inline expiry

- core/src/main/java/org/ehcache/core/EhcacheManager.java
- core/src/main/java/org/ehcache/core/StatusTransitioner.java
- core/src/test/java/org/ehcache/core/EhcacheManagerTest.java
- core/src/test/java/org/ehcache/core/StatusTransitionerTest.java
This solves cacheholder retrieve problem.
Still making progress on StatusTransitioner stuff
> Failure of cache creation should clean up #822

- core/src/main/java/org/ehcache/core/spi/cache/AbstractValueHolder.java
- impl/src/main/java/org/ehcache/impl/internal/store/offheap/BinaryOffHeapValueHolder.java
- impl/src/main/java/org/ehcache/impl/internal/store/offheap/LazyOffHeapValueHolder.java
- transactions/src/main/java/org/ehcache/transactions/xa/internal/XAValueHolder.java
- transactions/src/test/java/org/ehcache/transactions/xa/internal/XAValueHolderTest.java
* Removed implements Serializable from AbstractValueHolder
* Made XAValueHolder serializable using writeReplace/readResolve
> Issue #817 ValueHolders no longer Serializable

- core/src/main/java/org/ehcache/core/statistics/StoreOperationOutcomes.java
- impl/src/main/java/org/ehcache/impl/internal/store/heap/OnHeapStore.java
- impl/src/test/java/org/ehcache/impl/internal/store/heap/OnHeapStoreEvictionTest.java
- impl/src/test/java/org/ehcache/impl/internal/store/heap/bytesized/ByteAccountingTest.java
* Byte accounting now performed inside lambdas
* Cleaned up the side effects variables to reduce them to the minimum
> Issue #851 Byte accounting changes

- build.gradle
- buildSrc/src/main/groovy/EhDeploy.groovy
- buildSrc/src/main/groovy/EhDistribute.groovy
- buildSrc/src/main/groovy/scripts/Utils.groovy
Git revision retrieved from
* CI environment first
* CLI second
and then placed in Implementation-Version in MANIFEST.MF
> Issue #887 Add git revision to manifest

- impl/src/main/java/org/ehcache/impl/internal/store/heap/Backend.java
- impl/src/main/java/org/ehcache/impl/internal/store/heap/KeyCopyBackend.java
- impl/src/main/java/org/ehcache/impl/internal/store/heap/OnHeapStore.java
- impl/src/main/java/org/ehcache/impl/internal/store/heap/SimpleBackend.java
- impl/src/test/java/org/ehcache/impl/internal/store/heap/bytesized/ByteAccountingTest.java
Made the backend responsible for holding the bye size filed and
implement clear through simple backed re-creation.
> Issue #851 Resolve race in clear when byte sizing

- 107/build.gradle
- 107/src/main/java/org/ehcache/jsr107/DefaultConfigurationResolver.java
- 107/src/main/java/org/ehcache/jsr107/DefaultJsr107SerializationProvider.java
- 107/src/main/java/org/ehcache/jsr107/Eh107CacheStatisticsMXBean.java
- 107/src/main/java/org/ehcache/jsr107/Eh107Configuration.java
- 107/src/main/java/org/ehcache/jsr107/EhcacheCachingProvider.java
- 107/src/main/java/org/ehcache/jsr107/MultiCacheException.java
- 107/src/main/java/org/ehcache/jsr107/config/Jsr107Configuration.java
- 107/src/main/java/org/ehcache/jsr107/config/Jsr107Service.java
- 107/src/main/java/org/ehcache/jsr107/config/package-info.java
- 107/src/main/java/org/ehcache/jsr107/internal/DefaultJsr107Service.java
- 107/src/main/java/org/ehcache/jsr107/internal/Jsr107ServiceConfigurationParser.java
- 107/src/main/java/org/ehcache/jsr107/internal/tck/Eh107MBeanServerBuilder.java
- 107/src/main/java/org/ehcache/jsr107/package-info.java
- 107/src/main/resources/META-INF/services/org.ehcache.xml.CacheManagerServiceConfigurationParser
- 107/src/test/java/org/ehcache/ParsesConfigurationExtensionTest.java
- 107/src/test/java/org/ehcache/docs/EhCache107ConfigurationIntegrationDocTest.java
- 107/src/test/java/org/ehcache/jsr107/ConfigurationMergerTest.java
- buildSrc/src/main/groovy/EhDistribute.groovy
- clustered/dist/gradle.properties
- core/src/main/java/org/ehcache/core/Ehcache.java
- core/src/main/java/org/ehcache/core/EhcacheWithLoaderWriter.java
- core/src/main/java/org/ehcache/core/internal/util/ValueSuppliers.java
- dist/gradle.properties
- impl/src/main/java/org/ehcache/impl/internal/store/heap/OnHeapStore.java
- impl/src/main/java/org/ehcache/impl/internal/store/offheap/AbstractOffHeapStore.java
- impl/src/test/java/org/ehcache/impl/internal/events/FudgingInvocationScopedEventSinkTest.java
- impl/src/test/java/org/ehcache/impl/internal/events/ScopedStoreEventDispatcherTest.java
- impl/src/test/java/org/ehcache/impl/internal/store/offheap/AbstractOffHeapStoreTest.java
- transactions/src/main/java/org/ehcache/transactions/xa/internal/XAStore.java
* Misc javadoc improvements for 107 module
* Reduce default javadoc of distribution jar to public API
* Add additional spi-javadoc artifact containing API and SPI javadoc
> Issue #844 Another batch of javadoc improvements

- 107/src/main/java/org/ehcache/jsr107/Eh107Cache.java
- core/src/main/java/org/ehcache/core/Ehcache.java
- core/src/main/java/org/ehcache/core/EhcacheWithLoaderWriter.java
- core/src/main/java/org/ehcache/core/SpecIterator.java
- core/src/test/java/org/ehcache/core/EhcacheBasicCrudBase.java
- core/src/test/java/org/ehcache/core/EhcacheWithLoaderWriterBasicPutIfAbsentTest.java
- core/src/test/java/org/ehcache/core/EhcacheWithLoaderWriterBasicRemoveValueTest.java
- core/src/test/java/org/ehcache/core/EhcacheWithLoaderWriterBasicReplaceValueTest.java
- impl/src/main/java/org/ehcache/impl/internal/store/heap/OnHeapStore.java
- impl/src/main/java/org/ehcache/impl/internal/store/offheap/AbstractOffHeapStore.java
- impl/src/main/java/org/ehcache/impl/internal/store/offheap/portability/SerializerPortability.java
- transactions/src/main/java/org/ehcache/transactions/xa/configuration/XAStoreConfiguration.java
- transactions/src/main/java/org/ehcache/transactions/xa/internal/XAStore.java
- transactions/src/main/java/org/ehcache/transactions/xa/internal/txmgr/provider/DefaultTransactionManagerProvider.java
I've given a pass to the TODOs in clustered as we are not shipping that code in GA.  We should address these in due time however.
> Issue #909 Remove TODOs - issues have either been filed, or they have been judged unworthy.

- 107/build.gradle
- 107/src/main/java/org/ehcache/jsr107/Eh107Cache.java
- 107/src/main/java/org/ehcache/jsr107/Eh107CacheManager.java
- 107/src/main/java/org/ehcache/jsr107/Eh107CacheStatisticsMXBean.java
- 107/src/main/java/org/ehcache/jsr107/EhcacheCachingProvider.java
- dist/build.gradle
All tests pass, and I even managed to pull the management project out of the settings.gradle without breaking the build (modulo a change in :clustered:dist) - so management is effectively a leaf project now.
> Issue #747 Replace limited management dependency in 107 code with direct statistics API usage

- impl/src/main/java/org/ehcache/impl/internal/spi/serialization/DefaultSerializationProvider.java
- impl/src/main/java/org/ehcache/impl/serialization/ByteArraySerializer.java
- impl/src/test/java/org/ehcache/impl/internal/spi/serialization/DefaultSerializationProviderTest.java
- impl/src/test/java/org/ehcache/impl/serialization/ByteArraySerializerTest.java
Comments are welcome but I'd like to wait for the perf results before this gets merged in.
> #896 add optimized byte array serializer in default config

- impl/src/test/java/org/ehcache/config/builders/ResourcePoolsBuilderTest.java
* ResourcePoolsBuilder.withReplacing test coverage improvement
> Issue #893 Improve test coverage

- docs/src/docs/asciidoc/user/caching-concepts.adoc
- docs/src/docs/asciidoc/user/caching-patterns.adoc
- docs/src/docs/asciidoc/user/caching-terms.adoc
- docs/src/docs/asciidoc/user/index.adoc
particularly relating to terms and concepts.
> more improvements to docs content

- clustered/client/src/main/java/org/ehcache/clustered/client/internal/store/ClusteredStore.java
- clustered/client/src/test/java/org/ehcache/clustered/client/internal/store/ClusteredStoreProviderTest.java
- impl/src/main/java/org/ehcache/impl/internal/store/tiering/TieredStore.java
- impl/src/main/java/org/ehcache/impl/internal/store/tiering/TieredStoreProviderFactory.java
- impl/src/main/resources/META-INF/services/org.ehcache.core.spi.service.ServiceFactory
- impl/src/test/java/org/ehcache/impl/internal/store/tiering/TieredStoreFlushWhileShutdownTest.java
- impl/src/test/java/org/ehcache/impl/internal/store/tiering/TieredStoreSPITest.java
- impl/src/test/java/org/ehcache/impl/internal/store/tiering/TieredStoreTest.java
- impl/src/test/java/org/ehcache/impl/internal/store/tiering/TieredStoreWith3TiersSPITest.java
- transactions/src/test/java/org/ehcache/transactions/xa/internal/XAStoreTest.java
* Rename CacheStoreProviderFactory to TieringStoreProviderFactory
* Rename relevant test classes
> Issue #965 Rename CacheStore to TieringStore

- api/src/main/java/org/ehcache/expiry/Duration.java
- docs/src/docs/asciidoc/user/caching-concepts.adoc
- docs/src/docs/asciidoc/user/expiry.adoc
- docs/src/docs/asciidoc/user/getting-started.adoc
- docs/src/docs/asciidoc/user/index.adoc
- docs/src/docs/asciidoc/user/menu.adoc
- impl/src/test/java/org/ehcache/docs/GettingStarted.java
- xml/src/test/resources/configs/docs/getting-started.xml
* Expiry documentation
* Addition of `Duration.of` static method
> Issue #995 Expiration documentation

- buildSrc/src/main/groovy/MavenToolchain.groovy
For those of you that are unfortunate enough to have to use windows you might need this fix.
> updated toolchain path to work on any OS.  Didn't work on windows

- clustered/client/src/test/java/org/ehcache/clustered/client/docs/GettingStarted.java
- clustered/client/src/test/java/org/ehcache/clustered/client/internal/UnitTestConnectionService.java
- docs/src/docs/asciidoc/user/clustered-cache.adoc
- docs/src/docs/asciidoc/user/getting-started.adoc
- docs/src/docs/asciidoc/user/index.adoc
- docs/src/docs/asciidoc/user/menu.adoc
Please also review the terminology used in the context
> #1002: User facing doc for clustered ehcache creation

- impl/src/main/java/org/ehcache/impl/internal/concurrent/ConcurrentHashMap.java
- impl/src/test/java/org/ehcache/impl/internal/concurrent/ConcurrentHashMapTest.java
Prerequisite of #1007, but obviously only a small subset of it. Could be merged separately of the remaining work or not, at convenience.
>  #1007: implement CHMv8.removeByHash()

- clustered/client/src/main/java/org/ehcache/clustered/client/internal/EhcacheClientEntity.java
- clustered/client/src/main/java/org/ehcache/clustered/client/internal/EhcacheClientEntityFactory.java
- clustered/client/src/main/java/org/ehcache/clustered/client/internal/EhcacheEntityCreationException.java
- clustered/client/src/main/java/org/ehcache/clustered/client/internal/EhcacheEntityOperationException.java
- clustered/client/src/main/java/org/ehcache/clustered/client/service/DefaultClusteringService.java
- clustered/client/src/test/java/org/ehcache/clustered/client/BasicClusteredCacheTest.java
- clustered/common/src/main/java/org/ehcache/clustered/common/ServerStoreCompatibility.java
- clustered/server/src/main/java/org/ehcache/clustered/server/EhcacheActiveEntity.java
- clustered/server/src/test/java/org/ehcache/clustered/server/EhcacheActiveEntityTest.java
This PR introduces unit tests for `EhcacheActiveEntity` and corrections for issues exposed by @lorban.
Additional unit tests to follow in additional PRs.
> Issue #763 EhcacheActiveEntity unit tests and corrections

- clustered/client/src/main/java/org/ehcache/clustered/client/internal/store/ClusteredStore.java
- clustered/client/src/test/java/org/ehcache/clustered/client/BasicClusteredCacheTest.java
- clustered/client/src/test/java/org/ehcache/clustered/client/docs/GettingStarted.java
- clustered/client/src/test/java/org/ehcache/clustered/client/internal/store/ClusteredStoreProviderTest.java
- clustered/client/src/test/resources/configs/simple-cluster.xml
- clustered/integration-test/src/test/java/org/ehcache/clustered/BasicCacheCrudTest.java
- docs/src/docs/asciidoc/user/clustered-cache.adoc
This PR just removes underlying heap store.
> Issue 994 cleanup of underlying heap store

- core/src/main/java/org/ehcache/core/EhcacheManager.java
- core/src/main/java/org/ehcache/core/StatusTransitioner.java
- core/src/main/java/org/ehcache/core/internal/service/ServiceLocator.java
- impl/src/main/java/org/ehcache/config/builders/UserManagedCacheBuilder.java
- impl/src/main/java/org/ehcache/impl/internal/executor/PooledExecutionService.java
- impl/src/main/java/org/ehcache/impl/internal/spi/copy/DefaultCopyProvider.java
- impl/src/main/java/org/ehcache/impl/internal/spi/serialization/DefaultSerializationProvider.java
- impl/src/main/java/org/ehcache/impl/internal/store/heap/OnHeapStore.java
- impl/src/main/java/org/ehcache/impl/persistence/DefaultLocalPersistenceService.java
Contains other logging related fixes
> [release/3.0] #1090 Reduce log level to debug

- core/src/main/java/org/ehcache/core/EhcacheManager.java
- core/src/main/java/org/ehcache/core/StatusTransitioner.java
- core/src/main/java/org/ehcache/core/internal/service/ServiceLocator.java
- impl/src/main/java/org/ehcache/config/builders/UserManagedCacheBuilder.java
- impl/src/main/java/org/ehcache/impl/internal/executor/PooledExecutionService.java
- impl/src/main/java/org/ehcache/impl/internal/spi/copy/DefaultCopyProvider.java
- impl/src/main/java/org/ehcache/impl/internal/spi/serialization/DefaultSerializationProvider.java
- impl/src/main/java/org/ehcache/impl/internal/store/heap/OnHeapStore.java
- impl/src/main/java/org/ehcache/impl/persistence/DefaultLocalPersistenceService.java
Contains other logging related fixes
> [master] #1090 Reduce logging level to debug

- clustered/client/src/main/java/org/ehcache/clustered/client/internal/service/ClusteringServiceFactory.java
- clustered/client/src/main/java/org/ehcache/clustered/client/internal/service/DefaultClusteringService.java
- clustered/client/src/main/java/org/ehcache/clustered/client/internal/store/ClusteredStore.java
- clustered/client/src/main/resources/META-INF/services/org.ehcache.core.spi.service.ServiceFactory
- clustered/client/src/test/java/org/ehcache/clustered/client/internal/service/ClusteringServiceFactoryTest.java
- clustered/client/src/test/java/org/ehcache/clustered/client/internal/service/DefaultClusteringServiceTest.java
And moved some classes around ...
> Issue #1098 Invert service dependencies

- core/src/main/java/org/ehcache/core/EhcacheManager.java
- core/src/main/java/org/ehcache/core/PersistentUserManagedEhcache.java
- impl/src/main/java/org/ehcache/config/builders/UserManagedCacheBuilder.java
- impl/src/main/java/org/ehcache/impl/internal/store/disk/OffHeapDiskStore.java
- impl/src/main/java/org/ehcache/impl/internal/store/heap/OnHeapStore.java
- impl/src/main/java/org/ehcache/impl/persistence/DefaultLocalPersistenceService.java
* Use slf4j substitution instead of string concatenation
* Fix plural
From remarks on PR #1092
> [master] #1090 Minor logging improvements

- core/src/main/java/org/ehcache/core/EhcacheManager.java
- core/src/main/java/org/ehcache/core/PersistentUserManagedEhcache.java
- impl/src/main/java/org/ehcache/config/builders/UserManagedCacheBuilder.java
- impl/src/main/java/org/ehcache/impl/internal/store/disk/OffHeapDiskStore.java
- impl/src/main/java/org/ehcache/impl/internal/store/heap/OnHeapStore.java
- impl/src/main/java/org/ehcache/impl/persistence/DefaultLocalPersistenceService.java
* Use slf4j substitution instead of string concatenation
* Fix plural
From remarks on PR #1092
> [release/3.0] #1090 Minor logging improvements

- 107/src/main/java/org/ehcache/jsr107/DefaultJsr107SerializationProvider.java
- impl/src/main/java/org/ehcache/impl/internal/spi/serialization/DefaultSerializationProvider.java
- impl/src/main/java/org/ehcache/impl/serialization/PlainJavaSerializer.java
- impl/src/test/java/org/ehcache/impl/internal/spi/serialization/DefaultSerializationProviderTest.java
As a workaround until #1107 is done
>  #1123 Temporarily replace optimized serialization with plain java one

- clustered/client/src/main/java/org/ehcache/clustered/client/internal/store/ClusteredStore.java
- clustered/client/src/test/java/org/ehcache/clustered/client/internal/store/ClusteredStoreTest.java
- clustered/client/src/test/java/org/ehcache/clustered/util/StatisticsTestUtils.java
> Issue #1075: Correcting the return value of ClusteredStore.put

- clustered/integration-test/src/test/java/org/ehcache/clustered/BasicClusteredCacheOpsTest.java
- clustered/integration-test/src/test/java/org/ehcache/clustered/EhcacheClientEntityFactoryIntegrationTest.java
- clustered/integration-test/src/test/java/org/ehcache/clustered/TerminatedServerTest.java
Add null for 'entityFragment' parameter on BasicExternalCluster constructor.
> Galvan change updates

- core/src/main/java/org/ehcache/core/config/DefaultConfiguration.java
- impl/src/main/java/org/ehcache/impl/persistence/DefaultLocalPersistenceService.java
- management/src/main/java/org/ehcache/management/providers/CacheBinding.java
- management/src/main/java/org/ehcache/management/providers/CacheBindingManagementProvider.java
- management/src/main/java/org/ehcache/management/providers/ExposedCacheBinding.java
- management/src/main/java/org/ehcache/management/providers/actions/EhcacheActionProvider.java
- management/src/main/java/org/ehcache/management/providers/actions/EhcacheActionWrapper.java
- management/src/main/java/org/ehcache/management/providers/settings/EhcacheSettingsProvider.java
- management/src/main/java/org/ehcache/management/providers/settings/ExposedCacheSettings.java
- management/src/main/java/org/ehcache/management/providers/settings/Reflect.java
- management/src/main/java/org/ehcache/management/providers/statistics/EhcacheStatistics.java
- management/src/main/java/org/ehcache/management/providers/statistics/EhcacheStatisticsProvider.java
- management/src/main/java/org/ehcache/management/registry/DefaultCollectorService.java
- management/src/main/java/org/ehcache/management/registry/DefaultManagementRegistryFactory.java
- management/src/main/java/org/ehcache/management/registry/DefaultManagementRegistryService.java
- management/src/test/java/org/ehcache/management/providers/actions/EhcacheActionProviderTest.java
- management/src/test/java/org/ehcache/management/providers/settings/EhcacheSettingsProviderTestTest.java
- management/src/test/java/org/ehcache/management/providers/statistics/EhcacheStatisticsProviderTest.java
- management/src/test/java/org/ehcache/management/registry/DefaultManagementRegistryServiceTest.java
- management/src/test/java/org/ehcache/management/registry/DefaultSharedManagementServiceTest.java
- management/src/test/resources/settings-capability.json
This PR contains:
- A fix for #1160 : @ljacomet 
- A fix for #1161 : @chrisdennis 
- Work for #1148: the exposure of the minimal cache settings (in a structured way) for management : @GaryWKeim @anthonydahanne @lorban
> Issues #1160, #1161 and #1148 (Expose CacheManager and Cache configuration)

- api/src/main/java/org/ehcache/spi/persistence/StateRepository.java
- clustered/client/src/main/java/org/ehcache/clustered/client/config/ClusteringServiceConfiguration.java
- clustered/client/src/main/java/org/ehcache/clustered/client/config/builders/ClusteringServiceConfigurationBuilder.java
- clustered/client/src/main/java/org/ehcache/clustered/client/config/builders/ServerSideConfigurationBuilder.java
- clustered/client/src/main/java/org/ehcache/clustered/client/internal/config/xml/ClusteringServiceConfigurationParser.java
- clustered/client/src/main/java/org/ehcache/clustered/client/internal/service/DefaultClusteringService.java
- clustered/client/src/test/java/org/ehcache/clustered/client/BasicClusteredCacheExpiryTest.java
- clustered/client/src/test/java/org/ehcache/clustered/client/BasicClusteredCacheTest.java
- clustered/client/src/test/java/org/ehcache/clustered/client/config/ClusteringServiceConfigurationTest.java
- clustered/client/src/test/java/org/ehcache/clustered/client/docs/GettingStarted.java
- clustered/client/src/test/java/org/ehcache/clustered/client/internal/service/DefaultClusteringServiceTest.java
- clustered/common/src/main/java/org/ehcache/clustered/common/ServerSideConfiguration.java
- clustered/integration-test/src/test/java/org/ehcache/clustered/BasicClusteredCacheOpsTest.java
- clustered/integration-test/src/test/java/org/ehcache/clustered/CacheManagerLifecycleEhcacheIntegrationTest.java
- clustered/integration-test/src/test/java/org/ehcache/clustered/EhcacheClientEntityFactoryIntegrationTest.java
- clustered/integration-test/src/test/java/org/ehcache/clustered/TerminatedServerTest.java
- clustered/server/src/main/java/org/ehcache/clustered/server/EhcacheActiveEntity.java
- clustered/server/src/test/java/org/ehcache/clustered/server/EhcacheActiveEntityTest.java
- docs/src/docs/asciidoc/user/clustered-cache.adoc
- impl/src/main/java/org/ehcache/impl/serialization/CompactJavaSerializer.java
- Better separate server configuration from service configuration.
- Move server configuration resolution to the server.
- Support an absent server configuration for connect only cases.
> Issue #1138

- clustered/client/src/test/java/org/ehcache/clustered/client/CacheManagerDestroyTest.java
- clustered/client/src/test/java/org/ehcache/clustered/client/ClusteredCacheDestroyTest.java
Added some tests to verify destroy behavior for cache and cachemanager for user facing apis
> closes #1193 : Issue 1193

- clustered/client/src/main/java/org/ehcache/clustered/client/internal/service/DefaultClusteringService.java
I've gone with what I understood to be the accepted terminology here "server storage manager".  That is I think the most important thing to review here.
> Issue #1184 Better error message on clustering service start failures

- clustered/client/src/test/java/org/ehcache/clustered/client/UnSupportedCombinationsWIthClusteredCacheTest.java
- clustered/common/src/main/java/org/ehcache/clustered/common/exceptions/ServerMisconfigurationException.java
- clustered/integration-test/src/test/java/org/ehcache/clustered/CacheManagerLifecycleEhcacheIntegrationTest.java
- clustered/server/src/main/java/org/ehcache/clustered/server/EhcacheActiveEntity.java
- clustered/server/src/test/java/org/ehcache/clustered/server/EhcacheActiveEntityTest.java
Dependent on https://github.com/Terracotta-OSS/terracotta-platform/pull/96
> Closes #1205 Prevent clients from interacting with a server without any resources configured

- clustered/client/src/main/java/org/ehcache/clustered/client/internal/EhcacheClientEntity.java
- clustered/client/src/main/java/org/ehcache/clustered/client/internal/EhcacheClientEntityFactory.java
- clustered/client/src/main/java/org/ehcache/clustered/client/internal/service/ClusteredTierCreationException.java
- clustered/client/src/main/java/org/ehcache/clustered/client/internal/service/ClusteredTierDestructionException.java
- clustered/client/src/main/java/org/ehcache/clustered/client/internal/service/ClusteredTierException.java
- clustered/client/src/main/java/org/ehcache/clustered/client/internal/service/ClusteredTierManagerConfigurationException.java
- clustered/client/src/main/java/org/ehcache/clustered/client/internal/service/ClusteredTierManagerValidationException.java
- clustered/client/src/main/java/org/ehcache/clustered/client/internal/service/ClusteredTierReleaseException.java
- clustered/client/src/main/java/org/ehcache/clustered/client/internal/service/ClusteredTierValidationException.java
- clustered/client/src/main/java/org/ehcache/clustered/client/internal/service/DefaultClusteringService.java
- clustered/client/src/main/java/org/ehcache/clustered/client/internal/store/ClusteredStore.java
- clustered/client/src/main/java/org/ehcache/clustered/client/internal/store/StrongServerStoreProxy.java
- clustered/client/src/test/java/org/ehcache/clustered/client/CacheManagerDestroyTest.java
- clustered/client/src/test/java/org/ehcache/clustered/client/ClusteredCacheDestroyTest.java
- clustered/client/src/test/java/org/ehcache/clustered/client/UnSupportedCombinationsWIthClusteredCacheTest.java
- clustered/client/src/test/java/org/ehcache/clustered/client/internal/EhcacheClientEntityFactoryTest.java
- clustered/server/src/main/java/org/ehcache/clustered/server/EhcacheActiveEntity.java
- clustered/server/src/test/java/org/ehcache/clustered/server/EhcacheActiveEntityTest.java
I did my best searching for exceptions and log messages but I might have missed something.
>  #1243 align terminology of reported messages with public documentation

- clustered/clustered-dist/build.gradle
- clustered/clustered-dist/src/assemble/README.txt
> Issue 1273

- core/src/main/java/org/ehcache/core/StatusTransitioner.java
- core/src/test/java/org/ehcache/core/StatusTransitionerTest.java
Please centralize Pr review / comments in the matching one here: #1305 :-)
> Bad message reported in status transitioner (branch master)

- clustered/integration-test/build.gradle
- clustered/integration-test/src/test/java/org/ehcache/clustered/BasicClusteredCacheOpsTest.java
- clustered/integration-test/src/test/java/org/ehcache/clustered/CacheManagerLifecycleEhcacheIntegrationTest.java
- clustered/integration-test/src/test/java/org/ehcache/clustered/EhcacheClientEntityFactoryIntegrationTest.java
- clustered/integration-test/src/test/java/org/ehcache/clustered/TerminatedServerTest.java
- clustered/integration-test/src/test/java/org/ehcache/clustered/lock/VoltronReadWriteLockPassiveIntegrationTest.java
…tems.  This is a temporary fix until the Galvan #61 bug is fixed
> Issue #1217 Update to latest galvan

- management/src/test/java/org/ehcache/core/EhcacheManagerToStringTest.java
Some unit test path issues fixed for windows.
> Closes #1346: assertion on paths made generic to work on windows

- core/src/main/java/org/ehcache/core/config/store/StoreEventSourceConfiguration.java
Interested in getting that merged and being able to follow up on the impacts it may have (or not) on load tests.
> Issue #1196 Single queue for event ordering

- clustered/client/src/test/java/org/ehcache/clustered/client/internal/service/DefaultClusteringServiceTest.java
- clustered/client/src/test/java/org/ehcache/clustered/server/ObservableEhcacheServerEntityService.java
- clustered/server/src/main/java/org/ehcache/clustered/server/EhcacheActiveEntity.java
- clustered/server/src/main/java/org/ehcache/clustered/server/EhcacheStateServiceImpl.java
- clustered/server/src/main/java/org/ehcache/clustered/server/ServerStoreEvictionListener.java
- clustered/server/src/main/java/org/ehcache/clustered/server/ServerStoreImpl.java
- clustered/server/src/main/java/org/ehcache/clustered/server/state/EhcacheStateService.java
- clustered/server/src/main/java/org/ehcache/clustered/server/state/EhcacheStateServiceProvider.java
- clustered/server/src/main/java/org/ehcache/clustered/server/state/config/EhcacheStateServiceConfig.java
- clustered/server/src/main/resources/META-INF/services/org.terracotta.entity.ServiceProvider
- clustered/server/src/test/java/org/ehcache/clustered/server/EhcacheActiveEntityTest.java
- clustered/server/src/test/java/org/ehcache/clustered/server/state/EhcacheStateServiceProviderTest.java
Putting ehcache state specifc service in ehcache project only, Need to decide whether this can be moved/even generalised and moved to terracotta-platform.
> Issue #1207

- management/src/main/java/org/ehcache/management/registry/DefaultCollectorService.java
- management/src/test/java/org/ehcache/management/registry/DefaultCollectorServiceTest.java
> Close #1349 : clear stats for given capability when selected set is empty

- management/src/main/java/org/ehcache/management/cluster/DefaultClusteringManagementService.java
> Remove duplicate dependency

- clustered/client/src/main/java/org/ehcache/clustered/client/internal/store/ClusteredStore.java
- clustered/client/src/main/java/org/ehcache/clustered/client/internal/store/ResolvedChain.java
- clustered/client/src/main/java/org/ehcache/clustered/client/internal/store/operations/ChainResolver.java
- clustered/client/src/test/java/org/ehcache/clustered/client/internal/store/ClusteredStoreTest.java
- clustered/client/src/test/java/org/ehcache/clustered/client/internal/store/operations/ChainResolverExpiryTest.java
- clustered/client/src/test/java/org/ehcache/clustered/client/internal/store/operations/ChainResolverTest.java
Still misses some `ClusteredStore` tests but want to get feedback on the general idea already.
> Fix #1342 replaceAtHead only when chain modified

- build.gradle
It seems to cause a test issue - needs investigation
> Revert version bumps

- build.gradle
- management/src/main/java/org/ehcache/management/cluster/DefaultClusteringManagementService.java
- management/src/test/java/org/ehcache/management/cluster/ClusteringManagementServiceTest.java
Compat' with Terracotta-OSS/terracotta-platform#135
@anthonydahanne : needs tc-platform release __5.0.6.beta2__
> Compat' with terracotta-platform#135

- clustered/integration-test/build.gradle
- clustered/integration-test/src/test/java/org/ehcache/clustered/management/AbstractClusteringManagementTest.java
- clustered/integration-test/src/test/java/org/ehcache/clustered/management/EhcacheManagerToStringTest.java
That should contribute to fixing #1436
> Fix clustered management integration tests issues on Windows

- core/src/main/java/org/ehcache/core/PersistentUserManagedEhcache.java
- core/src/main/java/org/ehcache/core/spi/service/DiskResourceService.java
- core/src/main/java/org/ehcache/core/spi/service/LocalPersistenceService.java
- impl/src/main/java/org/ehcache/config/builders/UserManagedCacheBuilder.java
- impl/src/main/java/org/ehcache/impl/internal/persistence/DefaultDiskResourceServiceFactory.java
- impl/src/main/java/org/ehcache/impl/internal/spi/serialization/DefaultSerializationProvider.java
- impl/src/main/java/org/ehcache/impl/internal/store/disk/OffHeapDiskStore.java
- impl/src/main/java/org/ehcache/impl/persistence/DefaultDiskResourceService.java
- impl/src/main/java/org/ehcache/impl/persistence/DefaultLocalPersistenceService.java
- impl/src/main/java/org/ehcache/impl/persistence/FileBasedStateRepository.java
- impl/src/main/java/org/ehcache/impl/persistence/FileUtils.java
- impl/src/main/resources/META-INF/services/org.ehcache.core.spi.service.ServiceFactory
- impl/src/test/java/org/ehcache/config/builders/PersistentCacheManagerTest.java
- impl/src/test/java/org/ehcache/docs/UserManagedCaches.java
- impl/src/test/java/org/ehcache/impl/internal/persistence/CacheManagerDestroyRemovesPersistenceTest.java
- impl/src/test/java/org/ehcache/impl/internal/persistence/TestDiskResourceService.java
- impl/src/test/java/org/ehcache/impl/internal/spi/serialization/DefaultSerializationProviderTest.java
- impl/src/test/java/org/ehcache/impl/internal/store/disk/OffHeapDiskStoreProviderTest.java
- impl/src/test/java/org/ehcache/impl/internal/store/disk/OffHeapDiskStoreSPITest.java
- impl/src/test/java/org/ehcache/impl/internal/store/disk/OffHeapDiskStoreTest.java
- impl/src/test/java/org/ehcache/impl/internal/store/tiering/TieredStoreFlushWhileShutdownTest.java
- impl/src/test/java/org/ehcache/impl/internal/store/tiering/TieredStoreSPITest.java
- impl/src/test/java/org/ehcache/impl/internal/store/tiering/TieredStoreWith3TiersSPITest.java
- impl/src/test/java/org/ehcache/impl/internal/util/FileExistenceMatchers.java
- impl/src/test/java/org/ehcache/impl/persistence/DefaultLocalPersistenceServiceTest.java
- transactions/src/main/java/org/ehcache/transactions/xa/internal/XAStore.java
- transactions/src/main/java/org/ehcache/transactions/xa/internal/journal/DefaultJournalProvider.java
Refactor to separate local persistence service from file based persistence.
> Issue #1192 Separate local persistence from file based persistence

- xml/src/main/java/org/ehcache/xml/ConfigurationParser.java
- xml/src/test/java/org/ehcache/xml/XmlConfigurationTest.java
- xml/src/test/resources/configs/systemprops.xml
Since that came up on the ML, ... and I couldn't sleep, I quickly did this. 
Now, there is wider question wrt the usage of NCname in the XSD that restricts using these _all_ over the place... 
What do you guys think?
> Support system props in xml

- build.gradle
- docs/src/docs/asciidoc/user/management.adoc
- management/src/test/java/org/ehcache/docs/ManagementTest.java
needs tc-platform __5.0.7.beta__ to be released and deployed first
> Version upgrade and ManagementTest fix

- clustered/integration-test/src/test/java/org/ehcache/clustered/management/ClusteringManagementServiceTest.java
- management/src/test/java/org/ehcache/management/registry/DefaultManagementRegistryServiceTest.java
https://github.com/ehcache/ehcache3/issues/1458
> Issue #1458 Descriptor test improvements

- xml/src/main/java/org/ehcache/xml/ConfigurationParser.java
- xml/src/test/java/org/ehcache/xml/XmlConfigurationTest.java
- xml/src/test/resources/configs/systemprops.xml
(cherry picked from commit c76ee06ccd753f4db4365e78b4cda6779fd49c4d)
> Issue #1429: Support system props in xml

- clustered/client/src/test/java/org/ehcache/clustered/client/ActivePassiveSyncTest.java
- clustered/common/src/main/java/org/ehcache/clustered/common/internal/messages/EhcacheEntityMessage.java
- clustered/server/src/main/java/org/ehcache/clustered/server/ConcurrencyStrategies.java
- clustered/server/src/main/java/org/ehcache/clustered/server/EhcacheActiveEntity.java
- clustered/server/src/main/java/org/ehcache/clustered/server/EhcachePassiveEntity.java
- clustered/server/src/main/java/org/ehcache/clustered/server/EhcacheServerEntityService.java
- clustered/server/src/main/java/org/ehcache/clustered/server/EhcacheStateServiceImpl.java
- clustered/server/src/main/java/org/ehcache/clustered/server/messages/EhcacheSyncMessageCodec.java
- clustered/server/src/main/java/org/ehcache/clustered/server/messages/EntityStateSyncMessage.java
- clustered/server/src/main/java/org/ehcache/clustered/server/state/EhcacheStateService.java
- clustered/server/src/test/java/org/ehcache/clustered/server/messages/EhcacheSyncMessageCodecTest.java
Initial implementation of syncing non-data state of entity(the store manager state and server store state). Syncing the client message tracker state is still WIP.
> Closes #1209 Passive sync of entity lifecycle state

- api/src/main/java/org/ehcache/spi/service/MaintainableService.java
- build.gradle
- clustered/client/src/main/java/org/ehcache/clustered/client/internal/service/DefaultClusteringService.java
- clustered/client/src/test/java/org/ehcache/clustered/client/ClusteredCacheDestroyTest.java
- clustered/client/src/test/java/org/ehcache/clustered/client/internal/service/DefaultClusteringServiceTest.java
- core/src/main/java/org/ehcache/core/EhcacheManager.java
- core/src/test/java/org/ehcache/core/EhcacheManagerTest.java
- impl/src/main/java/org/ehcache/impl/persistence/DefaultDiskResourceService.java
- impl/src/main/java/org/ehcache/impl/persistence/DefaultLocalPersistenceService.java
- impl/src/test/java/org/ehcache/config/builders/PersistentCacheManagerTest.java
- impl/src/test/java/org/ehcache/impl/internal/persistence/CacheManagerDestroyRemovesPersistenceTest.java
- impl/src/test/java/org/ehcache/impl/internal/persistence/TestDiskResourceService.java
- impl/src/test/java/org/ehcache/impl/internal/util/FileExistenceMatchers.java
- impl/src/test/java/org/ehcache/impl/internal/util/FileExistenceMatchersTest.java
- impl/src/test/java/org/ehcache/impl/persistence/DefaultDiskResourceServiceTest.java
- impl/src/test/java/org/ehcache/impl/persistence/DefaultLocalPersistenceServiceTest.java
It also adds AssertJ to our dependencies and I'm using `@Enclosed` in one test.
> Fix issue #1192

- build.gradle
- clustered/client/src/main/java/org/ehcache/clustered/client/internal/EhcacheClientEntity.java
- clustered/client/src/test/java/org/ehcache/clustered/client/ActivePassiveSyncTest.java
- clustered/client/src/test/java/org/ehcache/clustered/client/config/ClusteringServiceConfigurationTest.java
- clustered/client/src/test/java/org/ehcache/clustered/client/internal/config/xml/ClusteringServiceConfigurationParserTest.java
- clustered/common/src/main/java/org/ehcache/clustered/common/internal/messages/ClientIDTrackerMessage.java
- clustered/common/src/main/java/org/ehcache/clustered/common/internal/messages/ClientIdTrackerMessageCodec.java
- clustered/common/src/main/java/org/ehcache/clustered/common/internal/messages/EhcacheCodec.java
- clustered/common/src/main/java/org/ehcache/clustered/common/internal/messages/EhcacheEntityMessage.java
- clustered/common/src/main/java/org/ehcache/clustered/common/internal/messages/ServerStoreOpMessage.java
- clustered/common/src/test/java/org/ehcache/clustered/common/internal/messages/ClientIDTrackerMessageCodecTest.java
- clustered/common/src/test/java/org/ehcache/clustered/common/internal/messages/EhcacheCodecTest.java
- clustered/integration-test/src/test/java/org/ehcache/clustered/lock/VoltronReadWriteLockPassiveIntegrationTest.java
- clustered/integration-test/src/test/java/org/ehcache/clustered/replication/BasicClusteredCacheCRUDReplicationTest.java
- clustered/integration-test/src/test/java/org/ehcache/clustered/replication/BasicLifeCyclePassiveReplicationTest.java
- clustered/integration-test/src/test/resources/clusteredConfiguration.txt
- clustered/server/src/main/java/org/ehcache/clustered/server/EhcacheActiveEntity.java
- clustered/server/src/main/java/org/ehcache/clustered/server/EhcachePassiveEntity.java
- clustered/server/src/test/java/org/ehcache/clustered/server/EhcacheActiveEntityTest.java
- clustered/server/src/test/java/org/ehcache/clustered/server/EhcachePassiveEntityTest.java
This only tackles replication. The complete story can be understood from PR #1462.
> Key value replication using IEntityMessenger #1211

- clustered/integration-test/src/test/java/org/ehcache/clustered/management/ClusteringManagementServiceTest.java
- management/src/main/java/org/ehcache/management/providers/statistics/StandardEhcacheStatistics.java
- management/src/test/java/org/ehcache/management/providers/statistics/StandardEhcacheStatisticsTest.java
- management/src/test/java/org/ehcache/management/registry/DefaultManagementRegistryServiceTest.java
* fix hit ratio
* rewrite  some tests assertions
Fix #1537
> Issue #1537 : HitRatio not computed correctly

- docs/src/docs/asciidoc/user/107.adoc
- docs/src/docs/asciidoc/user/cache-event-listeners.adoc
- docs/src/docs/asciidoc/user/caching-concepts.adoc
- docs/src/docs/asciidoc/user/caching-terms.adoc
- docs/src/docs/asciidoc/user/clustered-cache.adoc
- docs/src/docs/asciidoc/user/eviction-advisor.adoc
- docs/src/docs/asciidoc/user/examples.adoc
- docs/src/docs/asciidoc/user/expiry.adoc
- docs/src/docs/asciidoc/user/getting-started.adoc
- docs/src/docs/asciidoc/user/index.adoc
- docs/src/docs/asciidoc/user/management.adoc
- docs/src/docs/asciidoc/user/serializers-copiers.adoc
- docs/src/docs/asciidoc/user/thread-pools.adoc
- docs/src/docs/asciidoc/user/usermanaged.adoc
- docs/src/docs/asciidoc/user/writers.adoc
- docs/src/docs/asciidoc/user/xa.adoc
- docs/src/docs/asciidoc/user/xml.adoc
This is a summary PR for all the changes proposed yesterday by @ChrisBradley001 
Let's review here and once this is ok, I will open the matching PR for master.
> [release/3.1] Documentation fixes

- docs/src/docs/asciidoc/user/107.adoc
- docs/src/docs/asciidoc/user/cache-event-listeners.adoc
- docs/src/docs/asciidoc/user/caching-concepts.adoc
- docs/src/docs/asciidoc/user/caching-terms.adoc
- docs/src/docs/asciidoc/user/clustered-cache.adoc
- docs/src/docs/asciidoc/user/eviction-advisor.adoc
- docs/src/docs/asciidoc/user/examples.adoc
- docs/src/docs/asciidoc/user/expiry.adoc
- docs/src/docs/asciidoc/user/getting-started.adoc
- docs/src/docs/asciidoc/user/index.adoc
- docs/src/docs/asciidoc/user/management.adoc
- docs/src/docs/asciidoc/user/serializers-copiers.adoc
- docs/src/docs/asciidoc/user/thread-pools.adoc
- docs/src/docs/asciidoc/user/usermanaged.adoc
- docs/src/docs/asciidoc/user/writers.adoc
- docs/src/docs/asciidoc/user/xa.adoc
- docs/src/docs/asciidoc/user/xml.adoc
Did some general language tweaks.
> [master] Various documentation updates

- 107/src/main/java/org/ehcache/jsr107/EhcacheCachingProvider.java
- 107/src/test/java/org/ehcache/jsr107/EhCachingProviderTest.java
Issue #1468 Do not create config for existing cachemanager
>  Issue #1468 Do not create config for existing cachemanager

- build.gradle
- clustered/integration-test/build.gradle
- clustered/integration-test/src/test/java/org/ehcache/clustered/management/AbstractClusteringManagementTest.java
- clustered/integration-test/src/test/java/org/ehcache/clustered/management/ClusteringManagementServiceTest.java
- clustered/server/src/main/java/org/ehcache/clustered/server/state/EhcacheStateServiceProvider.java
- clustered/server/src/test/java/org/ehcache/clustered/server/state/EhcacheStateServiceProviderTest.java
- gradle.properties
- management/src/main/java/org/ehcache/management/cluster/DefaultClusteringManagementService.java
:arrow_up: Compat' with new tc-platform 1.0.8 beta and new monitoring service
Depends on:
> Dependency upgrade and compat' with new tc-platform 1.0.8 beta and new monitoring service

- clustered/integration-test/src/test/java/org/ehcache/clustered/management/AbstractClusteringManagementTest.java
- clustered/integration-test/src/test/java/org/ehcache/clustered/management/ClusteringManagementServiceTest.java
:green_heart: Fix unreliable management test
> Fix unreliable management test

- build.gradle
- clustered/common/src/main/java/org/ehcache/clustered/common/internal/messages/ServerStoreOpMessage.java
- clustered/server/src/main/java/org/ehcache/clustered/server/EhcacheExecutionStrategy.java
- clustered/server/src/main/java/org/ehcache/clustered/server/EhcacheServerEntityService.java
* Bump to latest terracotta .9-beta
* ExecutionStrategy first cut
* Make reconfigure invalid for Ehcache
> Fix #1559 Implement ExecutionStrategy

- clustered/client/src/main/java/org/ehcache/clustered/client/internal/store/operations/BaseKeyValueOperation.java
- clustered/client/src/main/java/org/ehcache/clustered/client/internal/store/operations/ChainResolver.java
- clustered/client/src/main/java/org/ehcache/clustered/client/internal/store/operations/ConditionalReplaceOperation.java
* Set limit based on known limit instead of capacity
* rewind instead of flip after decoding
> [master] Fix #1569 Proper ByteBuffer usage

- clustered/server/src/main/java/org/ehcache/clustered/server/EhcacheActiveEntity.java
- clustered/server/src/test/java/org/ehcache/clustered/server/EhcacheActiveEntityTest.java
when the cache manager is not configured with a default server resource
> Closes #1580 Active crashes on sync

- clustered/common/src/main/java/org/ehcache/clustered/common/internal/messages/PassiveReplicationMessage.java
- clustered/server/src/test/java/org/ehcache/clustered/server/EhcacheActiveEntityTest.java
of server store operation messages and replicated messages
> Closes #1577 Align the concurrency keys

- clustered/clustered-dist/src/assemble/README.txt
- docs/src/docs/asciidoc/user/107.adoc
- docs/src/docs/asciidoc/user/cache-event-listeners.adoc
- docs/src/docs/asciidoc/user/caching-concepts.adoc
- docs/src/docs/asciidoc/user/caching-patterns.adoc
- docs/src/docs/asciidoc/user/caching-terms.adoc
- docs/src/docs/asciidoc/user/clustered-cache.adoc
- docs/src/docs/asciidoc/user/common.adoc
- docs/src/docs/asciidoc/user/eviction-advisor.adoc
- docs/src/docs/asciidoc/user/examples.adoc
- docs/src/docs/asciidoc/user/expiry.adoc
- docs/src/docs/asciidoc/user/getting-started.adoc
- docs/src/docs/asciidoc/user/index.adoc
- docs/src/docs/asciidoc/user/management.adoc
- docs/src/docs/asciidoc/user/serializers-copiers.adoc
- docs/src/docs/asciidoc/user/thread-pools.adoc
- docs/src/docs/asciidoc/user/usermanaged.adoc
- docs/src/docs/asciidoc/user/writers.adoc
- docs/src/docs/asciidoc/user/xa.adoc
- docs/src/docs/asciidoc/user/xml.adoc
- docs/src/docs/asciidoc/user/xsds.adoc
* Replace sourcedir31 with sourcedir32 for website generation
* Bump a few 3.1 to 3.2 where needed
> Documentation setup changes for Ehcache 3.2

- gradle.properties
- transactions/build.gradle
* Do not escape sonatype URL from properties
* Activate signing in transactions module
> [release/3.1] Fix release deploy issues

- gradle.properties
- transactions/build.gradle
* Do not escape sonatype URL from properties
* Activate signing in transactions module
> [master] Fix release deploy issues

- management/src/test/java/org/ehcache/management/providers/statistics/EvictionTest.java
- management/src/test/java/org/ehcache/management/providers/statistics/HitCountTest.java
- management/src/test/java/org/ehcache/management/providers/statistics/HitRatioTest.java
- management/src/test/java/org/ehcache/management/providers/statistics/MissCountTest.java
- management/src/test/java/org/ehcache/management/providers/statistics/MissRatioTest.java
- management/src/test/java/org/ehcache/management/providers/statistics/StandardEhcacheStatisticsTest.java
- management/src/test/java/org/ehcache/management/registry/DefaultManagementRegistryServiceTest.java
- management/src/test/java/org/ehcache/management/registry/DefaultSharedManagementServiceTest.java
😞 but we have currently no other option to be able to resume PR building and moving forward on non stats related stuff.
> Ignore all currently broken stats tests

- build.gradle
> [closes #1654] add a gradle property that enables looking up artifacts in maven's local repo

- clustered/integration-test/src/test/java/org/ehcache/clustered/sync/PassiveSyncTest.java
- clustered/server/src/main/java/org/ehcache/clustered/server/EhcacheActiveEntity.java
- clustered/server/src/main/java/org/ehcache/clustered/server/EhcachePassiveEntity.java
- clustered/server/src/main/java/org/ehcache/clustered/server/repo/ServerStateRepository.java
- clustered/server/src/test/java/org/ehcache/clustered/server/EhcacheActiveEntityTest.java
- clustered/server/src/test/java/org/ehcache/clustered/server/EhcachePassiveEntityTest.java
* Includes a fix for `PassiveSyncTest` instability
> Fixes #1657 Error on decoded but unsupported message

- docs/src/docs/asciidoc/user/caching-concepts.adoc
This is the same content as what was reviewed and amended in #1620
> [release/3.1] Clarified some terms around caching tiers and storage areas.

- docs/src/docs/asciidoc/user/caching-concepts.adoc
This is the same content as what was reviewed and amended in #1620
> [master] Clarified some terms around caching tiers and storage areas.

- clustered/integration-test/src/test/java/org/ehcache/clustered/management/ClusteredStatisticRateTest.java
- management/src/test/java/org/ehcache/management/providers/statistics/HitRateTest.java
- management/src/test/java/org/ehcache/management/providers/statistics/MissRateTest.java
- management/src/test/java/org/ehcache/management/providers/statistics/StatsUtil.java
Unit tests for statistics rate tests on all 4 tiers
1. heap
2. offheap
3. disk
4. clustered
task: https://github.com/ehcache/ehcache3/issues/1484
> Close #1484: adds rate tests for all tiers

- clustered/client/src/test/java/org/ehcache/clustered/client/replication/ActivePassiveClientIdTest.java
- clustered/client/src/test/java/org/ehcache/clustered/client/replication/LifeCycleMessageActivePassvieReplicationTest.java
- clustered/client/src/test/java/org/ehcache/clustered/client/replication/ReplicationUtil.java
- clustered/client/src/test/java/org/ehcache/clustered/server/ObservableEhcacheServerEntityService.java
- clustered/server/src/main/java/org/ehcache/clustered/server/EhcacheActiveEntity.java
- clustered/server/src/main/java/org/ehcache/clustered/server/EhcachePassiveEntity.java
- clustered/server/src/main/java/org/ehcache/clustered/server/EhcacheServerEntityService.java
- clustered/server/src/main/java/org/ehcache/clustered/server/internal/messages/EhcacheStateSyncMessage.java
- clustered/server/src/main/java/org/ehcache/clustered/server/internal/messages/EhcacheSyncMessageCodec.java
- clustered/server/src/main/java/org/ehcache/clustered/server/internal/messages/PassiveReplicationMessage.java
- clustered/server/src/main/java/org/ehcache/clustered/server/internal/messages/PassiveReplicationMessageCodec.java
- clustered/server/src/main/java/org/ehcache/clustered/server/state/ClientMessageTracker.java
- clustered/server/src/main/java/org/ehcache/clustered/server/state/MessageTracker.java
- clustered/server/src/test/java/org/ehcache/clustered/server/EhcacheActiveEntityTest.java
- clustered/server/src/test/java/org/ehcache/clustered/server/EhcachePassiveEntityTest.java
- clustered/server/src/test/java/org/ehcache/clustered/server/internal/messages/EhcacheServerCodecTest.java
- clustered/server/src/test/java/org/ehcache/clustered/server/internal/messages/EhcacheSyncMessageCodecTest.java
- clustered/server/src/test/java/org/ehcache/clustered/server/internal/messages/PassiveReplicationMessageCodecTest.java
- clustered/server/src/test/java/org/ehcache/clustered/server/state/ClientMessageTrackerTest.java
> Issue 1591

- build.gradle
- clustered/integration-test/src/test/java/org/ehcache/clustered/management/AbstractClusteringManagementTest.java
- clustered/integration-test/src/test/java/org/ehcache/clustered/management/ClusteredStatisticsCountTest.java
- clustered/integration-test/src/test/java/org/ehcache/clustered/management/ClusteringManagementServiceTest.java
- clustered/server/src/main/java/org/ehcache/clustered/server/EhcacheActiveEntity.java
- clustered/server/src/main/java/org/ehcache/clustered/server/EhcachePassiveEntity.java
- clustered/server/src/main/java/org/ehcache/clustered/server/management/Management.java
- clustered/server/src/main/java/org/ehcache/clustered/server/management/PoolSettingsManagementProvider.java
- clustered/server/src/main/java/org/ehcache/clustered/server/management/PoolStatisticsManagementProvider.java
- clustered/server/src/main/java/org/ehcache/clustered/server/management/ServerStoreSettingsManagementProvider.java
- clustered/server/src/main/java/org/ehcache/clustered/server/management/ServerStoreStatisticsManagementProvider.java
- clustered/server/src/test/java/org/ehcache/clustered/server/EhcacheActiveEntityTest.java
- clustered/server/src/test/java/org/ehcache/clustered/server/EhcachePassiveEntityTest.java
- management/src/main/java/org/ehcache/management/SharedManagementService.java
- management/src/main/java/org/ehcache/management/providers/CacheBindingManagementProvider.java
- management/src/main/java/org/ehcache/management/providers/settings/EhcacheSettingsProvider.java
- management/src/main/java/org/ehcache/management/providers/statistics/StandardEhcacheStatistics.java
- management/src/main/java/org/ehcache/management/registry/DefaultManagementRegistryService.java
- management/src/main/java/org/ehcache/management/registry/DefaultSharedManagementService.java
- management/src/test/java/org/ehcache/docs/ManagementTest.java
- management/src/test/java/org/ehcache/management/providers/actions/EhcacheActionProviderTest.java
- management/src/test/java/org/ehcache/management/providers/settings/EhcacheSettingsProviderTest.java
- management/src/test/java/org/ehcache/management/providers/statistics/EhcacheStatisticsProviderTest.java
- management/src/test/java/org/ehcache/management/registry/DefaultManagementRegistryServiceTest.java
- management/src/test/java/org/ehcache/management/registry/DefaultSharedManagementServiceTest.java
- management calls have been moved to the tms entity (both for clients and entities, prepared work to further support management calls for passives)
- introduced a service to facilitate the use of the tms entity
> tc-platform upgrade with new M&M API

- clustered/client/src/main/java/org/ehcache/clustered/client/internal/EhcacheClientEntityFactory.java
I'm logging exceptions that would suppress other exceptions. This will do until Java 7.
I've also changed some code that felt weird:
* No unlock on `EntityVersionMismatchException` but one on all other exceptions 
* try/catch on `EntityVersionMismatchException` was really broad
> Make sure we don’t suppress exceptions. Close #1651

- clustered/common/src/main/java/org/ehcache/clustered/common/internal/exceptions/UnknownClusterException.java
- clustered/common/src/main/java/org/ehcache/clustered/common/internal/messages/ExceptionCodec.java
- clustered/common/src/main/java/org/ehcache/clustered/common/internal/messages/ResponseCodec.java
depends on teracotta platform snapshot
> Closes #1645 Marshalling/Unmarshalling exceptions using runnel

- demos/01-CacheAside/src/main/java/org/ehcache/demos/peeper/DataCache.java
This removes the last warning in the demo projects
> Remove unchecked cast warning

- docs/src/docs/asciidoc/user/class-loading.adoc
- docs/src/docs/asciidoc/user/index.adoc
- docs/src/docs/asciidoc/user/menu.adoc
Single PR for reviews against master.
Will open other ones against `release/3.1` and `release/3.2` once content is agreed upon.
> [master] Fix #1619 ClassLoading documentation

- clustered/integration-test/README.md
- clustered/integration-test/src/test/java/org/ehcache/clustered/management/ClusteringManagementServiceTest.java
- core/src/main/java/org/ehcache/core/Ehcache.java
- core/src/main/java/org/ehcache/core/statistics/CacheStatistics.java
- core/src/main/java/org/ehcache/core/statistics/TierStatistics.java
- docs/src/docs/asciidoc/user/management.adoc
- impl/src/main/java/org/ehcache/impl/internal/statistics/DefaultCacheStatistics.java
- impl/src/main/java/org/ehcache/impl/internal/statistics/DefaultTierStatistics.java
- impl/src/main/java/org/ehcache/impl/internal/statistics/StatsUtils.java
- impl/src/main/java/org/ehcache/impl/internal/statistics/ZeroOperationStatistic.java
- impl/src/test/java/org/ehcache/impl/internal/statistics/DefaultCacheStatisticsTest.java
- impl/src/test/java/org/ehcache/impl/internal/statistics/DefaultTierStatisticsTest.java
- impl/src/test/java/org/ehcache/impl/internal/statistics/StatsUtilsTest.java
- integration-test/src/test/java/org/ehcache/integration/statistics/AbstractTierCalculationTest.java
- integration-test/src/test/java/org/ehcache/integration/statistics/CacheCalculationTest.java
- integration-test/src/test/java/org/ehcache/integration/statistics/TierCalculationTest.java
- management/src/test/java/org/ehcache/management/registry/DefaultManagementRegistryServiceTest.java
The required statistics available on a cache are now also provided per tier
> Provide statistics per tier

- build.gradle
- clustered/integration-test/src/test/java/org/ehcache/clustered/management/AbstractClusteringManagementTest.java
- clustered/integration-test/src/test/java/org/ehcache/clustered/management/ClusteringManagementServiceTest.java
- clustered/server/src/main/java/org/ehcache/clustered/server/EhcacheActiveEntity.java
- clustered/server/src/main/java/org/ehcache/clustered/server/management/ClientStateSettingsManagementProvider.java
- clustered/server/src/main/java/org/ehcache/clustered/server/management/ClusteredTierManagerSettingsManagementProvider.java
- clustered/server/src/main/java/org/ehcache/clustered/server/management/Management.java
- clustered/server/src/main/java/org/ehcache/clustered/server/management/Notification.java
- clustered/server/src/main/java/org/ehcache/clustered/server/management/PoolSettingsManagementProvider.java
- clustered/server/src/main/java/org/ehcache/clustered/server/management/PoolStatisticsManagementProvider.java
- clustered/server/src/main/java/org/ehcache/clustered/server/management/ServerStoreSettingsManagementProvider.java
- clustered/server/src/main/java/org/ehcache/clustered/server/management/ServerStoreStatisticsManagementProvider.java
- management/src/main/java/org/ehcache/management/providers/EhcacheStatisticCollectorProvider.java
Depends on https://github.com/Terracotta-OSS/terracotta-platform/pull/267
> Management do not rely on event stream ordering now + Version upgrade (-pre9)

- build.gradle
- clustered/client/src/main/java/org/ehcache/clustered/client/internal/EhcacheClientEntityFactory.java
- clustered/integration-test/src/test/java/org/ehcache/clustered/management/ClusteringManagementServiceTest.java
- clustered/server/src/main/java/org/ehcache/clustered/server/management/ClusterTierManagement.java
- clustered/server/src/main/java/org/ehcache/clustered/server/management/Management.java
- clustered/server/src/main/java/org/ehcache/clustered/server/management/ServerStoreSettingsManagementProvider.java
- clustered/server/src/main/java/org/ehcache/clustered/server/store/ClusteredTierActiveEntity.java
- clustered/server/src/main/java/org/ehcache/clustered/server/store/ClusteredTierPassiveEntity.java
> Fix missing link for management between cluster tier manager entity and cluster tier entities (server stores)

- build.gradle
- clustered/integration-test/build.gradle
- clustered/integration-test/src/test/java/org/ehcache/clustered/management/AbstractClusteringManagementTest.java
- clustered/integration-test/src/test/java/org/ehcache/clustered/management/ClusteringManagementServiceTest.java
- clustered/server/build.gradle
- clustered/server/src/main/java/org/ehcache/clustered/server/management/ClusterTierManagement.java
- clustered/server/src/main/java/org/ehcache/clustered/server/management/Management.java
- management/build.gradle
- management/src/main/java/org/ehcache/management/cluster/DefaultClusteringManagementService.java
Compat' with https://github.com/Terracotta-OSS/terracotta-platform/pull/285
> Upgrade to new tc-platform v5.2.0-pre18

- build.gradle
Also upgrade to latest tc-platform that includes the `UNREACHABLE` server state for m&m
> Upgrade to -pre14

- impl/src/main/java/org/ehcache/impl/internal/statistics/DefaultTierStatistics.java
- impl/src/test/java/org/ehcache/impl/internal/statistics/DefaultCacheStatisticsTest.java
- impl/src/test/java/org/ehcache/impl/internal/statistics/DefaultTierStatisticsTest.java
The issue is https://github.com/ehcache/ehcache3/issues/1847
> #1847 put, update and remove counts/rates at the tier level are incorrect

- clustered/common/src/main/java/org/ehcache/clustered/common/PoolAllocation.java
- clustered/server/src/main/java/org/ehcache/clustered/server/management/ServerStoreSettingsManagementProvider.java
to ease other Pool implementations use
> :snowflake: Close #1856 Create 2 subinterfaces 

- build.gradle
- clustered/integration-test/src/test/java/org/ehcache/clustered/replication/BasicClusteredCacheOpsReplicationWithMultipleClientsTest.java
Lib upgrade and bugfixes in tc-paltform
Depends on:
> Upgrade to voltron -pre15

- clustered/server/src/main/java/org/ehcache/clustered/server/store/ClusterTierActiveEntity.java
Previously this was covered by the single entity / multiple store
that made the code happen inside a ConcurrentMap.computeIfPresent()
but since we now have a single entity per store we need to make sure
the inflight invalidations are processed once only.
> Issue #1686 Proper exclusive handling of inflight invalidations

- clustered/client/src/main/java/org/ehcache/clustered/client/internal/ClusterTierManagerClientEntityFactory.java
- clustered/client/src/main/java/org/ehcache/clustered/client/internal/service/AbstractClientEntityFactory.java
- clustered/client/src/main/java/org/ehcache/clustered/client/internal/service/DefaultClusteringService.java
- clustered/client/src/main/java/org/ehcache/clustered/client/internal/store/ClusteredStore.java
- clustered/client/src/main/java/org/ehcache/clustered/client/internal/store/SimpleClusterTierClientEntity.java
- clustered/client/src/main/java/org/ehcache/clustered/client/internal/store/StrongServerStoreProxy.java
- clustered/client/src/test/java/org/ehcache/clustered/client/ClusteredCacheDestroyTest.java
- clustered/client/src/test/java/org/ehcache/clustered/client/internal/service/ClusterTierManagerClientEntityExceptionTest.java
- clustered/client/src/test/java/org/ehcache/clustered/client/internal/service/DefaultClusteringServiceTest.java
- clustered/server/src/main/java/org/ehcache/clustered/server/ClusterTierManagerActiveEntity.java
- clustered/server/src/main/java/org/ehcache/clustered/server/EhcacheStateServiceImpl.java
- clustered/server/src/main/java/org/ehcache/clustered/server/store/ClusterTierActiveEntity.java
- clustered/server/src/main/java/org/ehcache/clustered/server/store/ClusterTierPassiveEntity.java
- clustered/server/src/test/java/org/ehcache/clustered/server/store/ClusterTierActiveEntityTest.java
- docs/src/docs/asciidoc/user/clustered-cache.adoc
> Closes #1854 Align the term clustered tier to cluster tier

- build.gradle
(including https://github.com/Terracotta-OSS/terracotta-platform/pull/291)
> Upgrade voltron -pre16 (including Terracotta-OSS/terracotta-platform#291)

- 107/src/test/resources/org/ehcache/docs/public-xsds-location.xml
- build.gradle
- docs/src/docs/asciidoc/user/107.adoc
- docs/src/docs/asciidoc/user/cache-event-listeners.adoc
- docs/src/docs/asciidoc/user/caching-concepts.adoc
- docs/src/docs/asciidoc/user/caching-patterns.adoc
- docs/src/docs/asciidoc/user/caching-terms.adoc
- docs/src/docs/asciidoc/user/class-loading.adoc
- docs/src/docs/asciidoc/user/clustered-cache.adoc
- docs/src/docs/asciidoc/user/common.adoc
- docs/src/docs/asciidoc/user/eviction-advisor.adoc
- docs/src/docs/asciidoc/user/examples.adoc
- docs/src/docs/asciidoc/user/expiry.adoc
- docs/src/docs/asciidoc/user/getting-started.adoc
- docs/src/docs/asciidoc/user/index.adoc
- docs/src/docs/asciidoc/user/management.adoc
- docs/src/docs/asciidoc/user/migration-guide.adoc
- docs/src/docs/asciidoc/user/serializers-copiers.adoc
- docs/src/docs/asciidoc/user/thread-pools.adoc
- docs/src/docs/asciidoc/user/tiering.adoc
- docs/src/docs/asciidoc/user/usermanaged.adoc
- docs/src/docs/asciidoc/user/writers.adoc
- docs/src/docs/asciidoc/user/xa.adoc
- docs/src/docs/asciidoc/user/xml.adoc
- docs/src/docs/asciidoc/user/xsds.adoc
* Documentation changes in preparation of 3.3.0 release
* Bump to latest Terracotta versions
> Issue #1896 3.3.0 release preparation

- clustered/common/src/main/java/org/ehcache/clustered/common/PoolAllocation.java
- clustered/common/src/main/java/org/ehcache/clustered/common/internal/ServerStoreConfiguration.java
- clustered/server/src/test/java/org/ehcache/clustered/server/ServerStoreCompatibilityTest.java
- clustered/server/src/test/java/org/ehcache/clustered/server/store/ClusterTierActiveEntityTest.java
Delegate the checks from server store configuration level to individual pool allocation types
> Delegate pool allocation compatibility checks

- clustered/integration-test/build.gradle
See: https://github.com/ehcache/ehcache3/pull/1953 for history
> Fixing IDe compilation issues because dist module does not have transitive dependencies anymore

- build.gradle
- clustered/client/src/main/java/org/ehcache/clustered/client/internal/ClusterTierManagerClientEntityFactory.java
- clustered/client/src/main/java/org/ehcache/clustered/client/internal/ClusterTierManagerClientEntityService.java
- clustered/client/src/main/java/org/ehcache/clustered/client/internal/lock/VoltronReadWriteLock.java
- clustered/client/src/main/java/org/ehcache/clustered/client/internal/lock/VoltronReadWriteLockEntityClientService.java
- clustered/client/src/main/java/org/ehcache/clustered/client/internal/service/AbstractClientEntityFactory.java
- clustered/client/src/main/java/org/ehcache/clustered/client/internal/service/DefaultClusteringService.java
- clustered/client/src/main/java/org/ehcache/clustered/client/internal/store/ClusterTierClientEntityService.java
- clustered/client/src/test/java/org/ehcache/clustered/client/internal/ClusterTierManagerClientEntityFactoryTest.java
- clustered/client/src/test/java/org/ehcache/clustered/client/internal/UnitTestConnectionService.java
- clustered/client/src/test/java/org/ehcache/clustered/client/internal/lock/VoltronReadWriteLockClientTest.java
- clustered/client/src/test/java/org/ehcache/clustered/client/internal/lock/VoltronReadWriteLockTest.java
- clustered/client/src/test/java/org/ehcache/clustered/client/internal/service/DefaultClusteringServiceDestroyTest.java
- clustered/integration-test/src/test/java/org/ehcache/clustered/BasicEntityInteractionTest.java
- clustered/integration-test/src/test/java/org/ehcache/clustered/CacheManagerLifecycleEhcacheIntegrationTest.java
- clustered/integration-test/src/test/java/org/ehcache/clustered/management/AbstractClusteringManagementTest.java
- clustered/integration-test/src/test/java/org/ehcache/clustered/management/ClusteringManagementServiceTest.java
Depends on https://github.com/Terracotta-OSS/terracotta-platform/pull/300
> Compat with async management message receiving + Upgrade to 5.3.0-pre1

- CONTRIBUTING.adoc
> [master] Update contribute section

- CONTRIBUTING.adoc
> [release/3.2] Update contribute section

- CONTRIBUTING.adoc
> [release/3.1] Update contribute section

- CONTRIBUTING.adoc
> [release/3.0] Update contribute section

- CONTRIBUTING.adoc
> [release/3.3] Update contribute section

- build.gradle
- clustered/server/src/main/java/org/ehcache/clustered/server/ClusterTierManagerActiveEntity.java
- clustered/server/src/main/java/org/ehcache/clustered/server/ClusterTierManagerPassiveEntity.java
- clustered/server/src/main/java/org/ehcache/clustered/server/management/ClusterTierManagement.java
- clustered/server/src/main/java/org/ehcache/clustered/server/management/Management.java
- clustered/server/src/main/java/org/ehcache/clustered/server/store/ClusterTierActiveEntity.java
- clustered/server/src/main/java/org/ehcache/clustered/server/store/ClusterTierPassiveEntity.java
- clustered/server/src/test/java/org/ehcache/clustered/server/ClusterTierManagerActiveEntityTest.java
- clustered/server/src/test/java/org/ehcache/clustered/server/ClusterTierManagerPassiveEntityTest.java
- clustered/server/src/test/java/org/ehcache/clustered/server/store/ClusterTierActiveEntityTest.java
- clustered/server/src/test/java/org/ehcache/clustered/server/store/ClusterTierPassiveEntityTest.java
Also brings new way of supported management for plugins and services
See: https://github.com/Terracotta-OSS/terracotta-platform/pull/311
> Upgrade to new tc-platform with no leak on passive for m&M

- build.gradle
core -> 5.3.0-pre8
platform -> 5.3.0-pre11
> Bump Terracotta versions

- CONTRIBUTING.adoc
* Indicate process before opening issue
* Delete outdated information
* Reformat asciidoc file to 1 sentence per line at most
> [master] Improvements to contributing documentation

- build.gradle
- clustered/client/build.gradle
- clustered/integration-test/build.gradle
- clustered/integration-test/src/test/java/org/ehcache/clustered/management/AbstractClusteringManagementTest.java
- clustered/server/build.gradle
- integration-test/build.gradle
- management/src/main/java/org/ehcache/management/cluster/DefaultClusteringManagementService.java
Note: NmsAgent is now a permanent entity so it does not need to be created.
> Upgrade to new tc-platform version 5.3.0-pre13

- clustered/integration-test/build.gradle
- clustered/server/src/main/java/org/ehcache/clustered/server/ClusterTierManagerActiveEntity.java
- clustered/server/src/main/java/org/ehcache/clustered/server/ClusterTierManagerPassiveEntity.java
- clustered/server/src/main/java/org/ehcache/clustered/server/ClusterTierManagerServerEntityService.java
- clustered/server/src/main/java/org/ehcache/clustered/server/store/ClusterTierActiveEntity.java
- clustered/server/src/main/java/org/ehcache/clustered/server/store/ClusterTierPassiveEntity.java
- clustered/server/src/test/java/org/ehcache/clustered/server/ClusterTierManagerActiveEntityTest.java
- clustered/server/src/test/java/org/ehcache/clustered/server/ClusterTierManagerPassiveEntityTest.java
- clustered/server/src/test/java/org/ehcache/clustered/server/store/ClusterTierActiveEntityTest.java
- clustered/server/src/test/java/org/ehcache/clustered/server/store/ClusterTierPassiveEntityTest.java
The PR also contains a few clean up commits.
> Fix #2040 Adopt Terracotta Entity API changes

- clustered/integration-test/src/test/java/org/ehcache/clustered/management/DiagnosticTest.java
- clustered/server/src/main/java/org/ehcache/clustered/lock/server/VoltronReadWriteLockActiveEntity.java
- clustered/server/src/main/java/org/ehcache/clustered/server/ClusterTierManagerActiveEntity.java
- clustered/server/src/main/java/org/ehcache/clustered/server/ClusterTierManagerDump.java
- clustered/server/src/main/java/org/ehcache/clustered/server/ClusterTierManagerPassiveEntity.java
- clustered/server/src/main/java/org/ehcache/clustered/server/state/EhcacheStateServiceProvider.java
- clustered/server/src/main/java/org/ehcache/clustered/server/store/ClusterTierActiveEntity.java
- clustered/server/src/main/java/org/ehcache/clustered/server/store/ClusterTierDump.java
- clustered/server/src/main/java/org/ehcache/clustered/server/store/ClusterTierPassiveEntity.java
I'll add a test on tuesday, but let me know if you have some comments.... Thanks!
Note: I have opened:
- https://github.com/Terracotta-OSS/terracotta-apis/issues/240
- https://github.com/Terracotta-OSS/terracotta-apis/issues/241
- https://github.com/Terracotta-OSS/terracotta-apis/issues/242
> Close #2038: Dumping Ehcache state to state dump

- build.gradle
- clustered/server/src/main/java/org/ehcache/clustered/server/management/PoolSettingsManagementProvider.java
- clustered/server/src/main/java/org/ehcache/clustered/server/management/PoolStatisticsManagementProvider.java
- management/src/main/java/org/ehcache/management/providers/ExposedCacheBinding.java
- management/src/main/java/org/ehcache/management/providers/actions/EhcacheActionProvider.java
- management/src/main/java/org/ehcache/management/providers/statistics/EhcacheStatisticsProvider.java
- management/src/main/java/org/ehcache/management/registry/DefaultManagementRegistryService.java
which brings some m&m changes 
__DEPENDS ON:__
- ~~https://github.com/Terracotta-OSS/terracotta-platform/pull/348~~ => v5.3.0-pre24
> Upgrade to new tc-platform version

- build.gradle
- clustered/server/src/main/resources/offheap-message.properties
Add the custom offheap-message.properties for Ehcache
> Bump to latest Terracotta platform

- build.gradle
- clustered/server/src/main/java/org/ehcache/clustered/lock/server/VoltronReadWriteLockActiveEntity.java
- clustered/server/src/main/java/org/ehcache/clustered/server/ClusterTierManagerActiveEntity.java
- clustered/server/src/main/java/org/ehcache/clustered/server/state/EhcacheStateServiceDump.java
- clustered/server/src/main/java/org/ehcache/clustered/server/store/ClusterTierActiveEntity.java
updates statedumpable implementation and changes tc-platform to version 5.3.0-pre31
> Issue #2074 updates statedumpable implementation and changes tc-platform  to version 5.3.0-pre31

- clustered/client/src/main/java/org/ehcache/clustered/client/config/ClusteringServiceConfiguration.java
Fixes findbug error in ClusteringServiceConfiguration by using StringBuilder instead of String in loop
> Issue #2080 Fixes findbug error in ClusteringServiceConfiguration

- .gitignore
- clustered/client/src/test/java/org/ehcache/clustered/client/internal/UnitTestConnectionService.java
- clustered/client/src/test/java/org/ehcache/clustered/client/internal/store/EventualServerStoreProxyTest.java
- core/src/main/java/org/ehcache/core/events/CacheEvents.java
- core/src/test/java/org/ehcache/core/events/CacheEventsTest.java
- impl/src/main/java/org/ehcache/impl/config/persistence/CacheManagerPersistenceConfiguration.java
- impl/src/main/java/org/ehcache/impl/internal/store/tiering/TieredStore.java
- integration-test/src/test/java/org/ehcache/integration/util/JavaExec.java
- management/src/main/java/org/ehcache/management/cluster/DefaultClusteringManagementService.java
Backport of:
* #2089 Cache closing sequence
* Misc fixes
> [release/3.2] Backport fixes

- buildSrc/src/main/groovy/EhPomGenerate.groovy
Jar embedded pom files and repo ones are now identical.
> Adding missing dependencies to EhPomGenerate

- clustered/client/src/main/java/org/ehcache/clustered/client/internal/config/DedicatedClusteredResourcePoolImpl.java
- clustered/client/src/main/java/org/ehcache/clustered/client/internal/config/SharedClusteredResourcePoolImpl.java
- clustered/integration-test/src/test/java/org/ehcache/clustered/management/EhcacheManagerToStringTest.java
- clustered/integration-test/src/test/resources/clusteredConfiguration.txt
* also tweak the test to test ClusteredShared
> Close #2093 : better ClusteredDedicated representation

- 107/src/main/java/org/ehcache/jsr107/Eh107Cache.java
- clustered/client/src/main/java/org/ehcache/clustered/client/internal/store/CommonServerStoreProxy.java
- clustered/client/src/main/java/org/ehcache/clustered/client/internal/store/StrongServerStoreProxy.java
- clustered/common/src/main/java/org/ehcache/clustered/common/internal/messages/ChainCodec.java
- clustered/common/src/main/java/org/ehcache/clustered/common/internal/messages/ExceptionCodec.java
- clustered/common/src/main/java/org/ehcache/clustered/common/internal/messages/ResponseCodec.java
- clustered/common/src/main/java/org/ehcache/clustered/common/internal/messages/ServerStoreOpCodec.java
- clustered/common/src/main/java/org/ehcache/clustered/common/internal/store/Util.java
- clustered/server/src/main/java/org/ehcache/clustered/server/internal/messages/EhcacheSyncMessageCodec.java
- clustered/server/src/main/java/org/ehcache/clustered/server/internal/messages/PassiveReplicationMessageCodec.java
- clustered/server/src/main/java/org/ehcache/clustered/server/offheap/OffHeapChainMap.java
- clustered/server/src/main/java/org/ehcache/clustered/server/offheap/OffHeapServerStore.java
- clustered/server/src/test/java/org/ehcache/clustered/server/store/ClusterTierActiveEntityTest.java
- core/src/main/java/org/ehcache/core/internal/util/ClassLoading.java
- impl/src/main/java/org/ehcache/impl/internal/concurrent/ForkJoinPool.java
- impl/src/main/java/org/ehcache/impl/internal/executor/OnDemandExecutionService.java
- impl/src/main/java/org/ehcache/impl/internal/executor/PartitionedScheduledExecutor.java
- impl/src/main/java/org/ehcache/impl/internal/store/tiering/TieredStore.java
- impl/src/test/java/org/ehcache/impl/internal/concurrent/otherPackage/V8FeaturesTest.java
- impl/src/test/java/org/ehcache/impl/internal/executor/PartitionedOrderedExecutorTest.java
- impl/src/test/java/org/ehcache/impl/internal/executor/PartitionedScheduledExecutorTest.java
- impl/src/test/java/org/ehcache/impl/internal/executor/PartitionedUnorderedExecutorTest.java
- impl/src/test/java/org/ehcache/impl/internal/executor/PooledExecutionServiceTest.java
- impl/src/test/java/org/ehcache/impl/internal/store/heap/holders/SerializedOnHeapValueHolderTest.java
- impl/src/test/java/org/ehcache/impl/internal/store/tiering/TieredStoreMutatorTest.java
- management/src/main/java/org/ehcache/management/providers/statistics/EhcacheStatisticsProvider.java
- management/src/main/java/org/ehcache/management/registry/DefaultCollectorService.java
Includes taking into account comments from #2141
> Issue #2138 Use method references

- demos/00-NoCache/src/main/java/org/ehcache/demos/peeper/DataStore.java
- demos/01-CacheAside/src/main/java/org/ehcache/demos/peeper/DataStore.java
Changing to try with resource made some nested code appear wrong. It is
not a real issue, most likely a missing support in FB of that special
case.
> Issue #2138 Fix findbugs issues

- build.gradle
- core/src/main/java/org/ehcache/core/Ehcache.java
- core/src/main/java/org/ehcache/core/EhcacheWithLoaderWriter.java
- core/src/main/java/org/ehcache/core/InternalCache.java
- core/src/test/java/org/ehcache/core/EhcacheBasicGetAllTest.java
- impl/src/main/java/org/ehcache/impl/internal/statistics/DefaultCacheStatistics.java
> bugfix in tc-platform for m&m, statistics 1.5.0, latest tc-core versions

- clustered/client/src/test/java/org/ehcache/clustered/client/BasicClusteredCacheTest.java
This fix makes the test go from 1 minute to 3 seconds
> Do not do a toString on BigInteger. It is super slow

- gradle.properties
__Depends on https://github.com/Terracotta-OSS/terracotta-platform/pull/420__
> Upgrade to new tc-core version

- clustered/client/src/main/java/org/ehcache/clustered/client/config/ClusteringServiceConfiguration.java
- clustered/client/src/main/java/org/ehcache/clustered/client/internal/service/DefaultClusteringService.java
Provide a way to pass connection properties in DefaultClusteringService.
> Issue #2219: Provide a way to pass connection properties in DefaultClusteringService

- clustered/client/src/test/java/org/ehcache/clustered/client/internal/store/AbstractServerStoreProxyTest.java
- clustered/integration-test/src/test/java/org/ehcache/clustered/replication/BasicClusteredCacheOpsReplicationMultiThreadedTest.java
- gradle.properties
Depends on new releases of:
- https://github.com/Terracotta-OSS/statistics/pull/44
- https://github.com/Terracotta-OSS/terracotta-platform/pull/426
> Upgrade of core + statistics + platform

- docs/README.adoc
- docs/src/docs/asciidoc/developer/design.resilience.adoc
- docs/src/docs/asciidoc/developer/index.adoc
This is the design on resilience. It contains the current implementation and some thoughts left for later.
> Design document on resilience

- clustered/integration-test/src/test/java/org/ehcache/clustered/management/AbstractClusteringManagementTest.java
- clustered/integration-test/src/test/java/org/ehcache/clustered/management/AfterFailoverManagementServiceTest.java
- clustered/integration-test/src/test/java/org/ehcache/clustered/management/ClusteringManagementServiceTest.java
- clustered/integration-test/src/test/java/org/ehcache/clustered/management/DiagnosticTest.java
- clustered/integration-test/src/test/java/org/ehcache/clustered/util/BeforeAll.java
- clustered/integration-test/src/test/java/org/ehcache/clustered/util/BeforeAllRule.java
- clustered/server/src/main/java/org/ehcache/clustered/server/ClusterTierManagerActiveEntity.java
- clustered/server/src/main/java/org/ehcache/clustered/server/ClusterTierManagerPassiveEntity.java
- clustered/server/src/main/java/org/ehcache/clustered/server/management/ClusterTierManagement.java
- clustered/server/src/main/java/org/ehcache/clustered/server/management/Management.java
- clustered/server/src/main/java/org/ehcache/clustered/server/store/ClusterTierActiveEntity.java
- clustered/server/src/main/java/org/ehcache/clustered/server/store/ClusterTierPassiveEntity.java
- gradle.properties
Requires https://github.com/Terracotta-OSS/terracotta-platform/pull/445
See https://github.com/Terracotta-OSS/terracotta-platform/pull/445 for explanations
> Fix #2289: Management provider information lost after failover

- clustered/server/src/main/java/org/ehcache/clustered/server/internal/messages/EhcacheSyncMessageCodec.java
- clustered/server/src/main/java/org/ehcache/clustered/server/store/ClusterTierActiveEntity.java
This should avoid some rehashing for large messages and save some CPU.
> #2318 : create hash map of correct size as hash map size in message

- impl/src/test/java/org/ehcache/impl/internal/statistics/DefaultCacheStatisticsTest.java
Fixes org.ehcache.impl.internal.statistics.DefaultCacheStatisticsTest.getCacheGetLatencyHistory fail.
AssertionError: Expecting <149966336L> to be greater than or equal to: <150000000L>
at org.ehcache.impl.internal.statistics.DefaultCacheStatisticsTest.getCacheGetLatencyHistory(DefaultCacheStatisticsTest.java:246)
on ehcache-windows-checks-3.x publisher build.
> Fix DefaultCacheStatisticsTest on Windows by ensuring sleep is long enough

- clustered/client/src/main/java/org/ehcache/clustered/client/config/ClusteringServiceConfiguration.java
- clustered/client/src/main/java/org/ehcache/clustered/client/config/builders/ClusteringServiceConfigurationBuilder.java
- clustered/client/src/main/java/org/ehcache/clustered/client/internal/ConnectionSource.java
- clustered/client/src/main/java/org/ehcache/clustered/client/internal/config/xml/ClusteringServiceConfigurationParser.java
- clustered/client/src/main/java/org/ehcache/clustered/client/internal/service/ConnectionState.java
- clustered/client/src/main/java/org/ehcache/clustered/client/internal/service/DefaultClusteringService.java
- clustered/client/src/main/resources/ehcache-clustered-ext.xsd
- clustered/client/src/test/java/org/ehcache/clustered/client/config/ClusteringServiceConfigurationTest.java
- clustered/client/src/test/java/org/ehcache/clustered/client/internal/MockConnectionService.java
- clustered/client/src/test/java/org/ehcache/clustered/client/internal/UnitTestConnectionService.java
- clustered/client/src/test/java/org/ehcache/clustered/client/internal/config/xml/ClusteringServiceConfigurationParserTest.java
- clustered/client/src/test/java/org/ehcache/clustered/client/internal/service/ConnectionStateTest.java
- clustered/client/src/test/java/org/ehcache/clustered/client/internal/service/ReconnectTest.java
- clustered/integration-test/src/test/java/org/ehcache/clustered/replication/BasicClusteredCacheOpsReplicationWithServersApiTest.java
- gradle.properties
New APIs and xsd changes to enable us to specify multiple IPv6 server addresses.
> Issue#2291: Adapt to the new ConnectionFactory.connect API

- clustered/client/src/main/java/org/ehcache/clustered/client/config/ClusteringServiceConfiguration.java
- clustered/client/src/main/java/org/ehcache/clustered/client/config/builders/ClusteringServiceConfigurationBuilder.java
> Issue#2291: Added javadoc to the newly added public APIs

- 107/src/main/java/org/ehcache/jsr107/internal/Jsr107CacheConfigurationParser.java
- 107/src/main/java/org/ehcache/jsr107/internal/Jsr107ServiceConfigurationParser.java
- clustered/client/src/main/java/org/ehcache/clustered/client/internal/config/xml/ClusteredResourceConfigurationParser.java
- clustered/client/src/main/java/org/ehcache/clustered/client/internal/config/xml/ClusteringCacheManagerServiceConfigurationParser.java
- clustered/client/src/main/java/org/ehcache/clustered/client/internal/config/xml/ClusteringCacheServiceConfigurationParser.java
- clustered/client/src/main/resources/META-INF/services/org.ehcache.xml.CacheManagerServiceConfigurationParser
- clustered/client/src/main/resources/META-INF/services/org.ehcache.xml.CacheServiceConfigurationParser
- clustered/client/src/test/java/org/ehcache/clustered/client/internal/config/xml/ClusteringCacheManagerServiceConfigurationParserTest.java
- clustered/client/src/test/java/org/ehcache/clustered/client/internal/config/xml/ClusteringCacheServiceConfigurationParserTest.java
- management/src/main/java/org/ehcache/management/registry/ManagementRegistryServiceConfigurationParser.java
- transactions/src/main/java/org/ehcache/transactions/xa/internal/xml/TxCacheManagerServiceConfigurationParser.java
- transactions/src/main/java/org/ehcache/transactions/xa/internal/xml/TxCacheServiceConfigurationParser.java
- xml/src/main/java/org/ehcache/xml/CacheManagerServiceConfigurationParser.java
- xml/src/main/java/org/ehcache/xml/CacheResourceConfigurationParser.java
- xml/src/main/java/org/ehcache/xml/CacheServiceConfigurationParser.java
- xml/src/main/java/org/ehcache/xml/DomUtil.java
- xml/src/test/java/org/ehcache/xml/BarParser.java
- xml/src/test/java/org/ehcache/xml/BazParser.java
- xml/src/test/java/org/ehcache/xml/FancyParser.java
- xml/src/test/java/org/ehcache/xml/FooParser.java
The idea is to generate an XML config file from a ServiceCreationConfiguration and ServiceConfiguration.
This PR does the following:
1) SPIs and dummy implementation for the SPIs.
2) Basic orchestrator for the translation flow. This is the file ConfigurationTranslator.
3) Implementation in which xml documents will be generated from a given ServiceCreationConfiguration and from a given ServiceConfiguration.
> Implement Java to XML translation of extension config elements

- clustered/client/src/main/java/org/ehcache/clustered/client/internal/config/xml/ClusteringCacheManagerServiceConfigurationParser.java
- clustered/client/src/main/java/org/ehcache/clustered/client/internal/config/xml/ClusteringCacheServiceConfigurationParser.java
Refactoring code so that it can be effectively extended
> Refactoring code so that it can be effectively extended

- clustered/client/src/main/java/org/ehcache/clustered/client/internal/config/xml/ClusteredResourceConfigurationParser.java
- xml/src/main/java/org/ehcache/xml/BaseConfigParser.java
Changes required for translation of EnterpriseResourcePoolConfig.
> Changes required for Clustered ResourcePool Extensions.

- clustered/client/src/main/java/org/ehcache/clustered/client/internal/store/ClusteredStore.java
- impl/src/main/java/org/ehcache/impl/internal/store/disk/OffHeapDiskStore.java
- impl/src/main/java/org/ehcache/impl/internal/store/heap/OnHeapStore.java
- impl/src/main/java/org/ehcache/impl/internal/store/offheap/AbstractOffHeapStore.java
- impl/src/main/java/org/ehcache/impl/internal/store/offheap/OffHeapStore.java
- impl/src/test/java/org/ehcache/impl/internal/events/InvocationScopedEventSinkTest.java
- impl/src/test/java/org/ehcache/impl/internal/loaderwriter/writebehind/WriteBehindTest.java
This is a useful refactoring by itself but also preparatory work for being able to disable store statistics whenever useful.
> Refactor observer creations

- xml/src/test/resources/configs/ehcache-complete.xml
Hi,
Please review the changes done to the test, which always fails in Windows. Comments in the code explains the issue and the fix.
Regards,
Bhaskar.
> Fixed testcase failure in Windows environment.

- clustered/integration-test/src/test/java/org/ehcache/clustered/management/ClusteringManagementServiceTest.java
- impl/src/main/java/org/ehcache/impl/internal/statistics/DefaultTierStatistics.java
- management/src/test/java/org/ehcache/management/registry/DefaultManagementRegistryServiceTest.java
If someone can merge this m&m bugfix. 
Thanks :-)
> Ehcache was **reporting** MappingCount as a counter instead of a gauge

- impl/src/main/java/org/ehcache/impl/internal/concurrent/ConcurrentHashMap.java
- impl/src/main/java/org/ehcache/impl/internal/concurrent/ThreadLocalRandomUtil.java
Now using Java 9 CHM migrated back to Java 8. We need to benchmark to see what we should use.
> Migrate to Java 9 CHM

- impl/src/main/java/org/ehcache/impl/internal/store/heap/OnHeapStore.java
A put is about 20% faster with this code.
> Use a local variable to calculate delta

- clustered/client/src/main/java/org/ehcache/clustered/client/internal/ClusterTierManagerClientEntityFactory.java
- clustered/client/src/main/java/org/ehcache/clustered/client/internal/service/ConnectionState.java
- clustered/client/src/main/java/org/ehcache/clustered/client/internal/store/SimpleClusterTierClientEntity.java
- clustered/client/src/test/java/org/ehcache/clustered/client/internal/store/SimpleClusterTierClientEntityTest.java
- clustered/integration-test/src/test/java/org/ehcache/clustered/BasicCacheOpsMultiThreadedTest.java
- clustered/integration-test/src/test/java/org/ehcache/clustered/ClusterTierManagerClientEntityFactoryIntegrationTest.java
- clustered/integration-test/src/test/java/org/ehcache/clustered/DestroyLoopTest.java
This resolves issue #2437 and #2439
> Fix #2437 : Wait for the client entity to complete init while processing server messages

- clustered/server/src/test/java/org/ehcache/clustered/server/TestInvokeContext.java
- gradle.properties
bump versions to the latest release of tc-platform.
> update tc-platform to the latest

- clustered/client/src/main/java/org/ehcache/clustered/client/config/ClusteringServiceConfiguration.java
- clustered/client/src/test/java/org/ehcache/clustered/client/config/ClusteringServiceConfigurationTest.java
- clustered/integration-test/src/test/java/org/ehcache/clustered/BasicEntityInteractionTest.java
- management/src/main/java/org/ehcache/management/cluster/DefaultClusteringManagementService.java
- management/src/main/java/org/ehcache/management/registry/DefaultManagementRegistryService.java
> Misc. minor MnM bug fixes

- docs/src/docs/asciidoc/user/index.adoc
- docs/src/docs/asciidoc/user/menu.adoc
- docs/src/docs/asciidoc/user/performance.adoc
- integration-test/src/test/java/org/ehcache/docs/Performance.java
It's not complete because other PRs must be merged first. However, you can validate the concept.
> Add performance documentation

- gradle.properties
Offheap thread interruption handling
clustering replication performance improvements
> Bump dependencies.

- gradle.properties
Fixes a memory leak on the active server
> tc-core version bump

- docs/src/docs/asciidoc/user/caching-terms.adoc
- docs/src/docs/asciidoc/user/performance.adoc
- docs/src/docs/asciidoc/user/xsds.adoc
Still misses a fix for the plantuml diagrams.
> Doc fixes and improvements

- clustered/clustered-dist/src/assemble/server/conf/cluster.properties
- gradle.properties
- ~~[ ] Merge PR https://github.com/Terracotta-OSS/terracotta-platform/pull/757~~
> Upgrade to new tc-platform version (stripe name support in DC and M&M)

- gradle.properties
Includes:
- DC config versioning and backward compat'
- M&M changes from Gary
>  (DC config versioning and backward compat)

- clustered/client/src/main/java/org/ehcache/clustered/client/internal/ConnectionSource.java
- gradle.properties
~~__REQUIRES https://github.com/Terracotta-OSS/terracotta-platform/pull/861/__~~
Please see the description of https://github.com/Terracotta-OSS/terracotta-platform/pull/861/
> Correctly remove and add addresses based on user input

- clustered/clustered-dist/build.gradle
client directory exclusion is causing problems with voter script
> Remove client directory exclusion from platform kit

- azure-pipelines.yml
- clustered/client/src/test/java/org/ehcache/clustered/client/replication/ActivePassiveClientIdTest.java
- clustered/common-api/src/main/java/org/ehcache/clustered/common/internal/messages/EhcacheMessageType.java
- clustered/common/src/main/java/org/ehcache/clustered/common/internal/messages/BaseCodec.java
- clustered/integration-test/src/test/java/org/ehcache/clustered/replication/BasicClusteredCacheOpsReplicationMultiThreadedTest.java
- clustered/integration-test/src/test/java/org/ehcache/clustered/replication/BasicClusteredCacheOpsReplicationTest.java
- clustered/integration-test/src/test/java/org/ehcache/clustered/replication/BasicClusteredCacheOpsReplicationWithMultipleClientsTest.java
- clustered/integration-test/src/test/java/org/ehcache/clustered/replication/BasicClusteredCacheOpsReplicationWithServersApiTest.java
- clustered/integration-test/src/test/java/org/ehcache/clustered/replication/BasicLifeCyclePassiveReplicationTest.java
- clustered/integration-test/src/test/java/org/ehcache/clustered/replication/DuplicateTest.java
- clustered/integration-test/src/test/java/org/ehcache/clustered/replication/OversizedCacheOpsPassiveTest.java
- clustered/integration-test/src/test/java/org/ehcache/clustered/sync/PassiveSyncTest.java
- clustered/server/entity/src/main/java/org/ehcache/clustered/server/ConcurrencyStrategies.java
- clustered/server/entity/src/main/java/org/ehcache/clustered/server/EhcacheExecutionStrategy.java
- clustered/server/entity/src/main/java/org/ehcache/clustered/server/internal/messages/EhcacheMessageTrackerCatchup.java
- clustered/server/entity/src/main/java/org/ehcache/clustered/server/internal/messages/EhcacheServerCodec.java
- clustered/server/entity/src/main/java/org/ehcache/clustered/server/internal/messages/EhcacheSyncMessageCodec.java
- clustered/server/entity/src/main/java/org/ehcache/clustered/server/store/ClusterTierActiveEntity.java
- clustered/server/entity/src/main/java/org/ehcache/clustered/server/store/ClusterTierPassiveEntity.java
- clustered/server/entity/src/test/java/org/ehcache/clustered/server/internal/messages/EhcacheMessageTrackerMessageTest.java
- clustered/server/entity/src/test/java/org/ehcache/clustered/server/internal/messages/EhcacheSyncMessageCodecTest.java
- clustered/server/entity/src/test/java/org/ehcache/clustered/server/store/ClusterTierActiveEntityTest.java
- clustered/server/entity/src/test/java/org/ehcache/clustered/server/store/ClusterTierPassiveEntityTest.java
- gradle.properties
Tests for 3-node passive sync need to be built.  This fixes compilation for now.
> sync message tracker changes.  send catchup when failing over

- gradle.properties
See also https://github.com/Terracotta-OSS/terracotta-platform/pull/965
> upgrade to latest jackson-databind (2.12.2 from 2.12.1)

- gradle.properties
Depends on https://github.com/Terracotta-OSS/terracotta-platform/pull/1033
> Upgrade to latest versions

- gradle.properties
PR: https://github.com/Terracotta-OSS/terracotta-platform/pull/1036
Another one found by Gary (similar cause than the previous one). This time I went to all the synchronized / lock code that was placed in DC from the start to verify them.
> Upgrade platform to fix another old deadlock in Nomad

- gradle.properties
PR will fail since releases not yet available.
Please approve to speed up the release train.
> Core 5.8.2 and Platform 5.8.6

- clustered/integration-test/src/test/java/org/ehcache/clustered/management/AbstractClusteringManagementTest.java
- gradle.properties
updating to core 5.8.3-pre2 and platform 5.8.7-pre1
> core and platform version bump

- gradle.properties
Brings https://github.com/Terracotta-OSS/terracotta-platform/pull/1059 down to EE
> Upgrade tc-platform

- clustered/ehcache-client/build.gradle
- clustered/integration-test/build.gradle
- ehcache-management/build.gradle
- gradle.properties
Pickup Jackson Databind 2.12.2.1 (CVE-2020-36518)
> Upgrade to Platform 5.8.13

- clustered/client/build.gradle
- clustered/integration-test/build.gradle
- gradle.properties
- management/build.gradle
**Upgraded to:**
* terracotta-utilities = 0.0.10
* terracottaPlatformVersion = 5.8.14
* terracottaCoreVersion = 5.8.7
* jacksonVersion = 2.13.2.20220328
> [3.9] Version upgrades

- build-logic/src/main/java/org/ehcache/build/plugins/PackagePlugin.java
- clustered/integration-test/build.gradle
- ehcache-xml/build.gradle
- ehcache/build.gradle
- gradle.properties
**Upgraded to:**
* terracotta-utilities = 0.0.10
* terracottaPlatformVersion = 5.8.14
* terracottaCoreVersion = 5.8.7
* jacksonVersion = 2.13.2.20220328
> [master] Version upgrades

- azure-pipelines-windows.yml
- demos/build.gradle
- gradle.properties
Terracotta Core 5.6.6
Terracotta Platform 5.7.4
SLF4J 1.7.36
Logback 1.2.11
OffHeap Store 2.5.3
Statistics 2.1.2
Jackson 2.13.4
> Upgrade Dependencies

- gradle.properties
For https://github.com/Terracotta-OSS/terracotta-platform/pull/1146
> [master] platform 5.9.17

- gradle.properties
For https://github.com/Terracotta-OSS/terracotta-platform/pull/1146
> [3.9] platform 5.9.17

- ehcache-107/src/main/java/org/ehcache/jsr107/Eh107CacheManager.java
- ehcache-107/src/test/java/org/ehcache/jsr107/UnwrapTest.java
Fixing cache visibility at JSR107 layer post unwrap()
this is daggy fix over - https://github.com/ehcache/ehcache3/commit/025c15f4beeee63f01615fceb63c457e25fa9803
the actual PR for this fix from the current master - https://github.com/ehcache/ehcache3/pull/3109
> issue-2494 : daggy fix cache visibility for javaxCacheManager

- gradle.properties
Brings that: https://github.com/Terracotta-OSS/terracotta-platform/pull/1145
> Upgrade to platform 5.10.12

- clustered/ehcache-clustered/build.gradle
- gradle.properties
I leave this PR in draft until a next platform release is done.
> Use platform-layout instead of platform-kit since platform 5.10.17

- clustered/ehcache-clustered/build.gradle
- ehcache-management/build.gradle
- ehcache-management/src/test/java/org/ehcache/management/providers/settings/EhcacheSettingsProviderTest.java
- ehcache-management/src/test/resources/settings-capability.json
- gradle.properties
This PR depends on:
1. [x] https://github.com/Terracotta-OSS/terracotta-platform/pull/1183
> Jackson => Gson

- buildSrc/src/main/groovy/EhDeploy.groovy
- buildSrc/src/main/groovy/EhPomMangle.groovy
Currently broken after nexus publish plugin upgrade on 3.9
> Remove references to deployUser to fix releasing

- ehcache-impl/src/main/java/org/ehcache/impl/internal/store/heap/Backend.java
- ehcache-impl/src/main/java/org/ehcache/impl/internal/store/heap/KeyCopyBackend.java
- ehcache-impl/src/main/java/org/ehcache/impl/internal/store/heap/OnHeapStore.java
- ehcache-impl/src/main/java/org/ehcache/impl/internal/store/heap/SimpleBackend.java
- ehcache-impl/src/test/java/org/ehcache/impl/internal/concurrent/ConcurrentHashMapTest.java
- ehcache-impl/src/unsafe/java/org/ehcache/impl/internal/concurrent/ConcurrentHashMap.java
- ehcache-impl/src/unsafe/java/org/ehcache/impl/internal/concurrent/EvictingConcurrentMap.java
(cherry picked from commit d97adf7d67700f564e95805cd3ffbe4c15bae3c6)
> Traversers start at the start and are recycled
