ehcache/ehcache3

core/src/test/java/org/ehcache/EhcacheBasicCrudBase.java, core/src/test/java/org/ehcache/EhcacheBasicRemoveAllTest.java
* Adds an implementation for EhcacheBasicCrudBase.FakeCacheWriter.deleteAll`.
* Adds `EhcacheBasicRemoveAllTest`.
This update **does not** include coverage for bulk statistics and event notification.
=> Issue #235 - Add Ehcache.removeAll unit tests

core/src/main/java/org/ehcache/Ehcache.java, core/src/test/java/org/ehcache/EhcacheBasicRemoveAllTest.java
This is based of @cljohnso 's branch, as this also fixes some tests in there (I'll let him double check these for correctness) 
Basically we need to differentiate between known failures and possible failures of given keys to being deleted from the SoR. Given the user can now observe the actual outcome, maybe we should introduce that concept in the `BulkCacheWriterException` as well... wdyt? Though this is somewhat akward to users maybe now (a third optional arg to its constructor maybe?) ...
Also, the `Cache.remove(K)` isn't consistent with behavior here... Probably want to align these. Anyways, have a look and let me know.
=> Issue #242 — can be merged once #260 is merged (and if someone's happy)

dist/build.gradle, xml/build.gradle
* Bump to freshly released 1.3.5 for jaxb plugin
* Adapt to new plugin declaration syntax in Gradle 2.1
* Bump shadow plugin version to 1.2.0
=> Issue #241 - Resolve jaxb plugin dependencies issue

107/src/main/java/org/ehcache/jsr107/Eh107Cache.java, api/src/main/java/org/ehcache/spi/loaderwriter/CacheLoaderWriter.java, core/src/main/java/org/ehcache/Ehcache.java, core/src/main/java/org/ehcache/Jsr107Cache.java, core/src/test/java/org/ehcache/EhcacheTest.java
Clarifies/Fixes the way results returned from `CacheLoader.loadAll` are processed.
=> Issue #245 Ignore keys returned from CacheLoader.loadAll

107/src/test/java/org/ehcache/jsr107/Eh107CacheTypeTest.java, 107/src/test/resources/ehcache-107-types.xml, xml/src/main/java/org/ehcache/config/xml/XmlConfiguration.java, xml/src/test/java/org/ehcache/config/xml/XmlConfigurationTest.java
Relaxing the type restriction imposed by the XMLTemplate. Instead of checking for equal names, checking if cache configuration type can be assigned to types defined in the xml template. This will allow JSR 107 caches to be constructed when no types are defined by templates. Should we relax it further?
Also adding JSR-107 type safety tests.
=> Allowing caches to override types in XML Template. 

107/src/main/java/org/ehcache/jsr107/DefaultJsr107Service.java, 107/src/main/java/org/ehcache/jsr107/Eh107CacheLoaderWriterFactory.java, 107/src/main/java/org/ehcache/jsr107/Jsr107Service.java, api/src/main/java/org/ehcache/spi/ServiceProvider.java, api/src/main/java/org/ehcache/spi/service/Service.java, core/src/main/java/org/ehcache/spi/ServiceLocator.java, core/src/test/java/org/ehcache/EhcacheManagerTest.java, core/src/test/java/org/ehcache/spi/ServiceLocatorTest.java, impl/src/main/java/org/ehcache/internal/EhcacheProvider.java, impl/src/main/java/org/ehcache/internal/HeapCachingTierResource.java, impl/src/main/java/org/ehcache/internal/classes/ClassInstanceProvider.java, impl/src/main/java/org/ehcache/internal/executor/DefaultThreadPoolsService.java, impl/src/main/java/org/ehcache/internal/persistence/DefaultLocalPersistenceService.java, impl/src/main/java/org/ehcache/internal/serialization/JavaSerializationProvider.java, impl/src/main/java/org/ehcache/internal/store/OnHeapStore.java, impl/src/test/java/org/ehcache/internal/persistence/DefaultLocalPersistenceServiceTest.java, integration-test/src/test/java/org/ehcache/integration/EhcacheBulkMethodsITest.java
Actually we were already passing the `ServiceProvider` to the factory on `Service` creation time. 
That's nice, so the factory can look up _all_ dependencies and inject them in the actual `Service` implementation on instantiation. Now... not all services are required the factory indirection, so I still think this changeset is meaningful, as discussed here:
https://www.youtube.com/watch?v=Yt1NjgDVQyQ&list=UU43PVCp2j0b2og2DtxNOU1A
=> Issue #279 Passing ServiceProvider on Service.start()

core-spi-test/src/main/java/org/ehcache/internal/store/StoreEventListenerTest.java
Test found to be asserting eviction event rather than expiration event
=> issue #269 : fixing ComputeIfPresent fails to remove the entry on expiration

core-spi-test/src/main/java/org/ehcache/internal/store/StoreBulkComputeIfAbsentTest.java, core-spi-test/src/main/java/org/ehcache/internal/store/StoreBulkComputeTest.java, core-spi-test/src/main/java/org/ehcache/internal/store/StoreClearTest.java, core-spi-test/src/main/java/org/ehcache/internal/store/StoreCloseTest.java, core-spi-test/src/main/java/org/ehcache/internal/store/StoreComputeIfAbsentTest.java, core-spi-test/src/main/java/org/ehcache/internal/store/StoreComputeIfPresentTest.java, core-spi-test/src/main/java/org/ehcache/internal/store/StoreComputeTest.java, core-spi-test/src/main/java/org/ehcache/internal/store/StoreContainsKeyTest.java, core-spi-test/src/main/java/org/ehcache/internal/store/StoreDestroyTest.java, core-spi-test/src/main/java/org/ehcache/internal/store/StoreEventListenerTest.java, core-spi-test/src/main/java/org/ehcache/internal/store/StoreGetTest.java, core-spi-test/src/main/java/org/ehcache/internal/store/StoreIteratorHasNextTest.java, core-spi-test/src/main/java/org/ehcache/internal/store/StoreIteratorNextTest.java, core-spi-test/src/main/java/org/ehcache/internal/store/StoreIteratorTest.java, core-spi-test/src/main/java/org/ehcache/internal/store/StorePutIfAbsentTest.java, core-spi-test/src/main/java/org/ehcache/internal/store/StorePutTest.java, core-spi-test/src/main/java/org/ehcache/internal/store/StoreRemoveKeyTest.java, core-spi-test/src/main/java/org/ehcache/internal/store/StoreRemoveKeyValueTest.java, core-spi-test/src/main/java/org/ehcache/internal/store/StoreReplaceKeyValueTest.java, core-spi-test/src/main/java/org/ehcache/internal/store/StoreReplaceKeyValueValueTest.java, spi-tester/src/main/java/org/ehcache/spi/test/After.java, spi-tester/src/main/java/org/ehcache/spi/test/Before.java, spi-tester/src/main/java/org/ehcache/spi/test/SPITester.java
Tests missing DiskStore.close(), causing failure of file.delete
=> Fixing issue #294 : DiskStoreSpi Tests failing on windows

core/src/test/java/org/ehcache/EhcacheBasicGetAllTest.java
As stated in the commit:
Fix tests to respect following behaviour:
* On CacheAccessException, forget about all cache hits and only return CacheLoderWriter result,
* On subsequent CacheLoaderWriter exception, triage as usual - BulkCacheLoadingException vs. generic exception - between successes and failures
PR also contains the removal of a todo related to issue #226
=> Issue #227: Resolve getAll and failures questions

core-spi-test/src/main/java/org/ehcache/internal/store/StoreEventListenerTest.java, impl/src/test/java/org/ehcache/internal/store/BaseOnHeapStoreTest.java
I have reviewed the tests in StoreEventListenerTest that are related to tests in BaseOnHeapStoreTest and to me, it makes sense to retain these tests as they can validate the listener if behaviour of Store is changed. I've also added a few negative tests for OnEviction and OnExpiration events. However I did not add tests for each and every store operation as eviction and expiration events would be same for each of them. 
Please provide comments/suggestions on the same
=> Fixing issue #284 : Reviewed unit tests related tests in BaseOnHeapStoreTest

docs/generate
Bash script to generate `ehcache.github.io` HTML content from `ehcache3` adoc files.  Requires `asciidoctor` to be available in path.
=> Add script to generate ehcache.github.io content from adocs

api/src/main/java/org/ehcache/event/CacheEventListenerFactory.java, core/src/main/java/org/ehcache/EhcacheManager.java, impl/src/main/java/org/ehcache/config/event/CacheEventListenerBuilder.java, impl/src/main/java/org/ehcache/config/event/DefaultCacheEventListenerConfiguration.java, impl/src/main/java/org/ehcache/config/event/DefaultCacheEventListenerFactoryConfiguration.java, impl/src/main/java/org/ehcache/internal/classes/ClassInstanceProvider.java, impl/src/main/java/org/ehcache/spi/event/DefaultCacheEventListenerFactory.java, impl/src/main/java/org/ehcache/spi/event/DefaultCacheEventListenerFactoryProvider.java, impl/src/main/resources/META-INF/services/org.ehcache.spi.service.ServiceFactory, impl/src/test/java/org/ehcache/GettingStarted.java, impl/src/test/java/org/ehcache/spi/event/CacheEventListenerBuilderTest.java, impl/src/test/java/org/ehcache/spi/event/DefaultCacheEventListenerFactoryTest.java, xml/src/main/java/org/ehcache/config/xml/ConfigurationParser.java, xml/src/main/java/org/ehcache/config/xml/XmlConfiguration.java, xml/src/main/resources/ehcache-core.xsd, xml/src/test/java/com/pany/ehcache/integration/TestCacheEventListener.java, xml/src/test/java/com/pany/ehcache/integration/TestSecondCacheEventListener.java, xml/src/test/java/org/ehcache/config/xml/IntegrationConfigTest.java, xml/src/test/java/org/ehcache/config/xml/XmlConfigurationTest.java, xml/src/test/resources/configs/ehcache-cacheEventListener.xml, xml/src/test/resources/configs/ehcache-multipleCacheEventListener.xml
Issue #278 : Incorporated changes as per review comments
Issue #278 : Rebasing
Issue #278 : Fixing test failures from rebasing
Issue #278 : Narrowing ServiceConfiguration type in DefaultCacheEventListenerFactory + cleanUp
Issue #278 : Changes wrt review comments
Issue #278 : Added sample listener to GettingStarted.java
Issue #278 : Renaming and Improving DefaultCacheEventListenerBuilder functionality
=> Issue #278 : Renaming and Improving DefaultCacheEventListenerBuilder functionality

107/src/main/java/org/ehcache/jsr107/Eh107CacheManager.java, core/src/main/java/org/ehcache/config/Builder.java, core/src/main/java/org/ehcache/config/CacheConfigurationBuilder.java, core/src/main/java/org/ehcache/config/writebehind/WriteBehindConfigurationBuilder.java, core/src/test/java/org/ehcache/config/CacheConfigurationBuilderTest.java, impl/src/main/java/org/ehcache/config/event/CacheEventListenerBuilder.java, impl/src/test/java/org/ehcache/GettingStarted.java, impl/src/test/java/org/ehcache/loaderwriter/writebehind/WriteBehindEvictionTest.java, impl/src/test/java/org/ehcache/loaderwriter/writebehind/WriteBehindTest.java, impl/src/test/java/org/ehcache/spi/event/DefaultCacheEventListenerFactoryTest.java, impl/src/test/java/org/ehcache/spi/loaderwriter/DefaultCacheLoaderWriterFactoryTest.java, integration-test/src/test/java/org/ehcache/integration/ExpiryEhcacheTestBase.java, xml/src/main/java/org/ehcache/config/xml/XmlConfiguration.java
* Always copy when modifying
* Rename addServiceConfig to add and removeServiceConfig to remove
* Overload add to take a Builder<? extends ServiceConfiguration<?>>, introducing that new interface
* WriteBehindConfigurationBuilder and CacheEventListenerBuilder now implements Builder
* Fix all CacheConfigurationBuilder usage to take method return into account
=> Issue #391 Clean up CacheConfigurationBuilder

impl/src/main/java/org/ehcache/internal/classes/ClassInstanceProvider.java, impl/src/main/java/org/ehcache/loaderwriter/writebehind/WriteBehindDecoratorLoaderWriterProviderFactory.java, impl/src/main/java/org/ehcache/spi/loaderwriter/DefaultCacheLoaderWriterFactory.java, impl/src/test/java/org/ehcache/WriteBehindDecoratorLoaderWriterProviderFactoryTest.java, impl/src/test/java/org/ehcache/internal/classes/ClassInstanceProviderTest.java, impl/src/test/java/org/ehcache/spi/event/DefaultCacheEventListenerFactoryTest.java, impl/src/test/java/org/ehcache/spi/loaderwriter/DefaultCacheLoaderWriterFactoryTest.java
Added validations to disallow cache specific configurations to be added at cache manager level
=> Issue #413 : Fixing WriteBehind writer blocks cache put operation

core/src/main/java/org/ehcache/Ehcache.java
I left out specializing the 2-arg version because it's only called from mutative methods, and hence the gc cost will probably be lost (until proven otherwise at least).
=> Issue #448 : extract out single arg null check method

core/src/main/java/org/ehcache/spi/service/FileBasedPersistenceContext.java, impl/src/main/java/org/ehcache/internal/persistence/DefaultLocalPersistenceService.java, impl/src/main/java/org/ehcache/internal/store/disk/OffHeapDiskStore.java
* a directory for each context, and no assumptions about index and data files.
* a reworked naming scheme that avoids escaping capital letters and instead relies on a SHA1 suffix to prevent FS limitation induced collisions.
=> Issue #355 rework persistence service

core/src/test/java/org/ehcache/util/ConcurrentWeakIdentityHashMapTest.java
@chrisdennis @ljacomet or anyone?... Pure theory, can't reproduce the failure, but basically the issue was this:
```
java.lang.AssertionError:Expected: is <9127>     but: was <10239>
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
at org.junit.Assert.assertThat(Assert.java:865)
at org.junit.Assert.assertThat(Assert.java:832)
at org.ehcache.util.ConcurrentWeakIdentityHashMapTest.testIteration(ConcurrentWeakIdentityHashMapTest.java:116)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:483)
at …
```
=> Issue #406 Don't assert things you can't assert!

core/src/main/java/org/ehcache/CacheManagerBuilder.java, core/src/main/java/org/ehcache/config/ConfigurationBuilder.java, core/src/test/java/org/ehcache/EhcacheManagerTest.java, impl/src/test/java/org/ehcache/loaderwriter/writebehind/WriteBehindEvictionTest.java, impl/src/test/java/org/ehcache/loaderwriter/writebehind/WriteBehindTest.java, integration-test/src/test/java/org/ehcache/integration/LoaderWriterErrorEhcacheTest.java, integration-test/src/test/java/org/ehcache/integration/LoaderWriterSimpleEhcacheTest.java
- Ensure CacheManagerBuilder and ConfigurationBuilder are immutable and return new instances for each build step.
- Use ConfigurationBuilder in CacheManagerBuilder to handle configuration building.
=> Issue #502

docs/src/docs/asciidoc/user/xsds.adoc
Changes to the XSD had caused the doc include to no longer be valid as the end of the file was indicated explicitly. Using -1 allows inclusion up to the end of the file.
=> Fix XSD includes: use -1 as end of file indicator

107/src/test/resources/ehcache-107-stats.xml, xml/src/main/resources/ehcache-core.xsd, xml/src/test/java/org/ehcache/config/xml/XmlConfigurationTest.java, xml/src/test/resources/configs/persistence-config.xml
@cschanck wisely recommended that the simplest solution to the disk path trimming problem would be to move to using an attribute rather than an element body to hold the disk path.  This is my attempt at doing exactly that.
=> Issue #525 Switch to using an attribute for disk path

api/src/main/java/org/ehcache/spi/loaderwriter/WriteBehindConfiguration.java, core/src/main/java/org/ehcache/config/writebehind/DefaultWriteBehindConfiguration.java, core/src/main/java/org/ehcache/config/writebehind/WriteBehindConfigurationBuilder.java, core/src/test/java/org/ehcache/config/writebehind/DefaultWriteBehindConfigurationTest.java, impl/src/test/java/org/ehcache/loaderwriter/writebehind/WriteBehindEvictionTest.java, xml/src/main/java/org/ehcache/config/xml/ConfigurationParser.java, xml/src/main/resources/ehcache-core.xsd, xml/src/test/java/org/ehcache/config/xml/IntegrationConfigurationTest.java, xml/src/test/java/org/ehcache/config/xml/XmlConfigurationTest.java, xml/src/test/resources/configs/writebehind-cache.xml
* Enforce the contract
* Improve javadocs
* Change default min write delay to 0
* As a consequence, build is faster as write behind related tests run faster
=> Issue #534 Enforce min write delay smaller or equal to max write delay

impl/src/main/java/org/ehcache/internal/store/heap/OnHeapStore.java, impl/src/test/java/org/ehcache/internal/store/heap/OnHeapStoreByValueTest.java, impl/src/test/java/org/ehcache/internal/store/tiering/CompoundCachingTierSPITest.java
A straight bug fix, with a couple extra null checks on top.
=>  #554: OnHeapStore.getOrComputeIfAbsent() now calls the key copier

api/src/main/java/org/ehcache/spi/loaderwriter/WriteBehindConfiguration.java, core/src/main/java/org/ehcache/config/writebehind/DefaultWriteBehindConfiguration.java, core/src/main/java/org/ehcache/config/writebehind/WriteBehindConfigurationBuilder.java, core/src/test/java/org/ehcache/config/writebehind/DefaultWriteBehindConfigurationTest.java, impl/src/main/java/org/ehcache/loaderwriter/writebehind/AbstractWriteBehindQueue.java, impl/src/test/java/org/ehcache/loaderwriter/writebehind/WriteBehindEvictionTest.java, impl/src/test/java/org/ehcache/loaderwriter/writebehind/WriteBehindTest.java, xml/src/main/java/org/ehcache/config/xml/ConfigurationParser.java, xml/src/main/java/org/ehcache/config/xml/XmlConfiguration.java, xml/src/main/resources/ehcache-core.xsd, xml/src/test/java/org/ehcache/config/xml/XmlConfigurationTest.java, xml/src/test/resources/configs/writebehind-cache.xml
First part for issue #543, addresses defaults and legal values for:
* queue size
* rate limit
* min and max write delay
Follow ups will be added here or in a new PR if this gets merged before.
=> Issue #543 write behind config defaults and legal values

107/src/main/java/org/ehcache/EhcacheHackAccessor.java, 107/src/main/java/org/ehcache/jsr107/Eh107CacheStatisticsMXBean.java, 107/src/test/java/org/ehcache/jsr107/StatisticsTest.java, api/src/main/java/org/ehcache/statistics/BulkOps.java, core/src/main/java/org/ehcache/Ehcache.java, core/src/main/java/org/ehcache/statistics/CacheOperationOutcomes.java
* Added `OperationObserver` for getAll, putAll and removeAll
* Added counter for `getAll` miss
* Replace `AtomicLong` with `LongAdder` for bulk counters
=> Issue #468 bulk ops statistics

impl/config/checkstyle-suppressions.xml
Compilation fails on windows with checkstyle errors as the config has incorrect path
=> Incorrect checkstyle config path

impl/src/main/java/org/ehcache/internal/store/heap/holders/LookupOnlyOnHeapKey.java
* As wrapper objects, comparing OnHeapKey subclasses fully delegates to getting a hold of their key reference
=> Issue #369 Ignore introduced findbugs warning

core/src/main/java/org/ehcache/spi/cache/tiering/CachingTier.java, core/src/main/java/org/ehcache/spi/cache/tiering/HigherCachingTier.java, impl/src/main/java/org/ehcache/internal/store/heap/OnHeapStore.java, impl/src/main/java/org/ehcache/internal/store/tiering/CacheStore.java, impl/src/main/java/org/ehcache/internal/store/tiering/CompoundCachingTier.java, impl/src/main/java/org/ehcache/internal/store/tiering/CompoundCachingTierServiceConfiguration.java, impl/src/test/java/org/ehcache/integration/SerializerCountingTest.java, impl/src/test/java/org/ehcache/internal/store/tiering/CompoundCachingTierTest.java
* Skip pushing down to lower tier and flush to authority directly instead
* Rename and move invalidate variant taking a function to HigherCachingTier
=> Issue #369 Improve CompoundCachingTier.invalidate(K key)

107/src/main/java/org/ehcache/jsr107/ConfigurationMerger.java, 107/src/test/java/com/pany/domain/Client.java, 107/src/test/java/com/pany/ehcache/ClientCopier.java, 107/src/test/java/org/ehcache/jsr107/Eh107XmlIntegrationTest.java, 107/src/test/resources/ehcache-107-default-copiers.xml
The ConfigurationMerger was not taking into account the CacheManager
level settings, which can contain default copier configurations.
=> Issue #611 Fix JSR-107 + template + default copiers

107/src/test/java/org/ehcache/jsr107/LongSerializer.java, 107/src/test/java/org/ehcache/jsr107/StringSerializer.java, api/src/main/java/org/ehcache/event/CacheEventListenerProvider.java, api/src/main/java/org/ehcache/spi/loaderwriter/CacheLoaderWriterProvider.java, api/src/main/java/org/ehcache/spi/serialization/SerializationProvider.java, api/src/main/java/org/ehcache/spi/serialization/Serializer.java, core/src/main/java/org/ehcache/EhcacheManager.java, core/src/main/java/org/ehcache/UserManagedCacheBuilder.java, core/src/test/java/org/ehcache/EhcacheManagerTest.java, impl/src/main/java/org/ehcache/internal/classes/ClassInstanceProvider.java, impl/src/main/java/org/ehcache/internal/serialization/CompactJavaSerializer.java, impl/src/main/java/org/ehcache/internal/serialization/CompactPersistentJavaSerializer.java, impl/src/main/java/org/ehcache/spi/event/DefaultCacheEventListenerProvider.java, impl/src/main/java/org/ehcache/spi/loaderwriter/DefaultCacheLoaderWriterProvider.java, impl/src/main/java/org/ehcache/spi/serialization/DefaultSerializationProvider.java, impl/src/test/java/org/ehcache/config/serializer/DefaultSerializationProviderConfigurationTest.java, impl/src/test/java/org/ehcache/docs/GettingStarted.java, impl/src/test/java/org/ehcache/integration/SerializerCountingTest.java, impl/src/test/java/org/ehcache/internal/classes/ClassInstanceProviderTest.java, impl/src/test/java/org/ehcache/internal/serialization/JavaSerializer.java, impl/src/test/java/org/ehcache/internal/store/heap/holders/SerializedOnHeapValueHolderTest.java, impl/src/test/java/org/ehcache/spi/serialization/DefaultSerializationProviderTest.java, integration-test/src/test/java/org/ehcache/integration/CacheCopierTest.java, transactions/src/main/java/org/ehcache/transactions/xa/SoftLockSerializer.java, transactions/src/main/java/org/ehcache/transactions/xa/SoftLockValueCombinedSerializer.java, transactions/src/main/java/org/ehcache/transactions/xa/XAStore.java, transactions/src/test/java/org/ehcache/transactions/xa/utils/JavaSerializer.java, xml/src/test/java/com/pany/ehcache/serializer/TestSerializer.java
1. The responsibility of closing a persistent serializer has been moved to the SerializationProvider via the releaseSerializer method. This way we achieve consistency in handling the life cycle of the provided objects.
2. Serializers are not Closeable anymore. So caches or rather the serialization provider won't be closing the serializers when they are closed.
=> Introduce a resource releaser method for SerializationProvider as a precursor to the real fix for #635

api/src/main/java/org/ehcache/config/Eviction.java, core-spi-test/src/main/java/org/ehcache/internal/store/StoreClearTest.java, core-spi-test/src/main/java/org/ehcache/internal/store/StoreCloseTest.java, core-spi-test/src/main/java/org/ehcache/internal/store/StoreComputeIfAbsentTest.java, core-spi-test/src/main/java/org/ehcache/internal/store/StoreComputeIfPresentTest.java, core-spi-test/src/main/java/org/ehcache/internal/store/StoreComputeTest.java, core-spi-test/src/main/java/org/ehcache/internal/store/StoreContainsKeyTest.java, core-spi-test/src/main/java/org/ehcache/internal/store/StoreGetTest.java, core-spi-test/src/main/java/org/ehcache/internal/store/StoreIteratorHasNextTest.java, core-spi-test/src/main/java/org/ehcache/internal/store/StoreIteratorNextTest.java, core-spi-test/src/main/java/org/ehcache/internal/store/StorePutIfAbsentTest.java, core-spi-test/src/main/java/org/ehcache/internal/store/StorePutTest.java, core-spi-test/src/main/java/org/ehcache/internal/store/StoreRemoveKeyTest.java, core-spi-test/src/main/java/org/ehcache/internal/store/StoreRemoveKeyValueTest.java, core-spi-test/src/main/java/org/ehcache/internal/store/StoreReplaceKeyValueTest.java, core-spi-test/src/main/java/org/ehcache/internal/store/StoreReplaceKeyValueValueTest.java, impl/src/test/java/org/ehcache/internal/store/heap/BaseOnHeapStoreTest.java
Since vetoing everything is equivalent to vetoing nothing while
taking a performance hit, decision has been made to remove this.
And clearly some of our Store SPI test where using it, most likely
misunderstanding what it does.
=> Issue #676 Remove Eviction.all() veto

dist/build.gradle, osgi-test/build.gradle, osgi-test/src/test/java/org/ehcache/osgi/Jsr107OsgiTest.java, osgi-test/src/test/java/org/ehcache/osgi/OffHeapOsgiTest.java
Up to now, offheap and management-model dependencies were left as
external and so needed to be picked by users when needed.
This changeset now changes that so they are shaded inside the
main ehcache jar produced.
=> Issue #684 Shade offheap and management jars in

gradle/wrapper/gradle-wrapper.properties, impl/src/test/java/org/ehcache/internal/store/disk/OffHeapDiskStoreSPITest.java, impl/src/test/java/org/ehcache/internal/store/offheap/OffHeapStoreSPITest.java
The motivation is our cloudbees build showing that executors are out
of memory and paging just before the gradle test tasks exits.
Also bumped the gradle version to 2.9
=> Test changes to reduce memory footprint

core-spi-test/src/main/java/org/ehcache/internal/store/StoreBulkComputeIfAbsentTest.java, core-spi-test/src/main/java/org/ehcache/internal/store/StoreBulkComputeTest.java, core-spi-test/src/main/java/org/ehcache/internal/store/StoreClearTest.java, core-spi-test/src/main/java/org/ehcache/internal/store/StoreCloseTest.java, core-spi-test/src/main/java/org/ehcache/internal/store/StoreComputeIfAbsentTest.java, core-spi-test/src/main/java/org/ehcache/internal/store/StoreComputeIfPresentTest.java, core-spi-test/src/main/java/org/ehcache/internal/store/StoreComputeTest.java, core-spi-test/src/main/java/org/ehcache/internal/store/StoreContainsKeyTest.java, core-spi-test/src/main/java/org/ehcache/internal/store/StoreEvictionEventListenerTest.java, core-spi-test/src/main/java/org/ehcache/internal/store/StoreExpiryEventListenerTest.java, core-spi-test/src/main/java/org/ehcache/internal/store/StoreGetTest.java, core-spi-test/src/main/java/org/ehcache/internal/store/StoreIteratorHasNextTest.java, core-spi-test/src/main/java/org/ehcache/internal/store/StoreIteratorNextTest.java, core-spi-test/src/main/java/org/ehcache/internal/store/StoreIteratorTest.java, core-spi-test/src/main/java/org/ehcache/internal/store/StorePutIfAbsentTest.java, core-spi-test/src/main/java/org/ehcache/internal/store/StorePutTest.java, core-spi-test/src/main/java/org/ehcache/internal/store/StoreRemoveKeyTest.java, core-spi-test/src/main/java/org/ehcache/internal/store/StoreRemoveKeyValueTest.java, core-spi-test/src/main/java/org/ehcache/internal/store/StoreReplaceKeyValueTest.java, core-spi-test/src/main/java/org/ehcache/internal/store/StoreReplaceKeyValueValueTest.java
I stumbled upon this when trying to understand failures in Cloudbees on Java 1.8
=> Properly close the Store in SPI tests tear down

core/src/main/java/org/ehcache/util/ConcurrentWeakIdentityHashMap.java, core/src/test/java/org/ehcache/util/ConcurrentWeakIdentityHashMapTest.java
Fix the implementations so that the returned sets do reflect map changes. The IBM JDK 1.6's Collections.newSetFromMap() implementation directly relies on this contract which made the problem obviously apparent, but we could have run into the same kind of problem with other JDKs too.
=> #739: fix ConcurrentWeakIdentityHashMap keySet() and entrySet()

core/src/main/java/org/ehcache/EhcacheManager.java, core/src/main/java/org/ehcache/spi/ServiceLocator.java, core/src/test/java/org/ehcache/EhcacheManagerTest.java, impl/src/main/java/org/ehcache/CacheManagerBuilder.java, impl/src/main/java/org/ehcache/config/CacheConfigurationBuilder.java, impl/src/main/java/org/ehcache/config/ConfigurationBuilder.java, impl/src/main/java/org/ehcache/config/copy/DefaultCopyProviderConfiguration.java, impl/src/main/java/org/ehcache/config/serializer/DefaultSerializationProviderConfiguration.java, impl/src/main/java/org/ehcache/internal/classes/ClassInstanceProvider.java, impl/src/main/java/org/ehcache/internal/events/CacheEventDispatcherFactoryImpl.java, impl/src/main/java/org/ehcache/spi/loaderwriter/DefaultCacheLoaderWriterProvider.java, impl/src/test/java/org/ehcache/CacheManagerBuilderTest.java, impl/src/test/java/org/ehcache/docs/GettingStarted.java
When creating the cache configuration, most service configuration are
expected to exist as a single instance. The builder now takes care of
achieving this. At the same time, service consuming these configuration
now properly check that no duplicates are found when this is not valid.
This pull requests takes care of the `CacheConfigurationBuilder` level, `CacheManagerBuilder` level to come later.
=> Issue #740 Prevent duplicate service configuration in builder

core/src/main/java/org/ehcache/events/CacheEventDispatcherImpl.java, impl/src/main/java/org/ehcache/internal/events/CacheEventDispatcherFactoryImpl.java, impl/src/test/java/org/ehcache/internal/events/CacheEventDispatcherFactoryImplTest.java
Without this patch, a default thread pool is always needed for events even if a specific events pool is configured.
=> #165: fix event listener configuration

impl/src/main/java/org/ehcache/impl/internal/store/offheap/AbstractOffHeapStore.java
When investigating performance and churn, AbstractOffHeapStore.getAndFault
was found slower than AbstractOffHeapStore.computeIfAbsentAndFault.
The issue was a remaining call to backingMap.getAndPin. This is now
removed.
=> Issue #507 Remove not needed call to backing map

impl/src/main/java/org/ehcache/impl/internal/store/heap/Backend.java, impl/src/main/java/org/ehcache/impl/internal/store/heap/KeyCopyBackend.java, impl/src/main/java/org/ehcache/impl/internal/store/heap/OnHeapStore.java, impl/src/main/java/org/ehcache/impl/internal/store/heap/SimpleBackend.java
This enables two different implementation:
* Existing one which store OnHeapKey<K> to handle copy semantics
for the key
* New one which acts as a passthrough when the key copier is an
IdentityCopier
=> Issue #791 Extract MapWrapper from OnHeapStore

core/src/main/java/org/ehcache/core/EhcacheManager.java, core/src/main/java/org/ehcache/core/PersistentUserManagedEhcache.java, core/src/test/java/org/ehcache/core/CacheConfigurationChangeListenerTest.java, core/src/test/java/org/ehcache/core/EhcacheBasicClearTest.java, core/src/test/java/org/ehcache/core/EhcacheBasicContainsKeyTest.java, core/src/test/java/org/ehcache/core/EhcacheBasicGetAllTest.java, core/src/test/java/org/ehcache/core/EhcacheBasicGetTest.java, core/src/test/java/org/ehcache/core/EhcacheBasicIteratorTest.java, core/src/test/java/org/ehcache/core/EhcacheBasicPutAllTest.java, core/src/test/java/org/ehcache/core/EhcacheBasicPutIfAbsentTest.java, core/src/test/java/org/ehcache/core/EhcacheBasicPutTest.java, core/src/test/java/org/ehcache/core/EhcacheBasicRemoveAllTest.java, core/src/test/java/org/ehcache/core/EhcacheBasicRemoveTest.java, core/src/test/java/org/ehcache/core/EhcacheBasicRemoveValueTest.java, core/src/test/java/org/ehcache/core/EhcacheBasicReplaceTest.java, core/src/test/java/org/ehcache/core/EhcacheBasicReplaceValueTest.java, core/src/test/java/org/ehcache/core/EhcacheBulkMethodsTest.java, core/src/test/java/org/ehcache/core/EhcacheLoaderWriterTest.java, core/src/test/java/org/ehcache/core/EhcacheTest.java, impl/src/main/java/org/ehcache/config/builders/UserManagedCacheBuilder.java, impl/src/test/java/org/ehcache/docs/plugs/ListenerObject.java, integration-test/src/test/java/org/ehcache/integration/EventNotificationTest.java
Logging systems use package separator to filter
`<logger name="org.ehcache.spi" level="WARN"/>`
So a suggestion would be to use that so that we can filter the different cache names in logs, if you are using cache names in logger names.
REPLACES PR #801
=> Suggestion: use standard logger name for logging (replaces #801)

build.gradle, impl/src/main/java/org/ehcache/impl/internal/store/disk/EhcachePersistentConcurrentOffHeapClockCache.java, impl/src/main/java/org/ehcache/impl/internal/store/disk/factories/EhcachePersistentSegmentFactory.java, impl/src/main/java/org/ehcache/impl/internal/store/offheap/EhcacheConcurrentOffHeapClockCache.java, impl/src/main/java/org/ehcache/impl/internal/store/offheap/EhcacheOffHeapBackingMap.java, impl/src/test/java/org/ehcache/impl/config/serializer/SerializerCountingTest.java, impl/src/test/java/org/ehcache/impl/internal/store/disk/EhcachePersistentConcurrentOffHeapClockCacheTest.java, impl/src/test/java/org/ehcache/impl/internal/store/offheap/AbstractEhcacheOffHeapBackingMapTest.java, impl/src/test/java/org/ehcache/impl/internal/store/offheap/EhcacheConcurrentOffHeapClockCacheTest.java
* Bump offheap-store to 2.2.1
* Replace EhcachePersistentSegmentFactory.computeIfPinned with an
impl in EhcachePersistentConcurrentOffHeapClockCache
* Further specify the contract of the method with tests
* Extract abstract test class to reduce duplication
* Javadoc cleanup
=> Issue #797 Update computeIfPinned to leverage offheap 2.2.1

impl/src/main/java/org/ehcache/impl/internal/store/offheap/AbstractOffHeapStore.java, impl/src/main/java/org/ehcache/impl/internal/store/offheap/BasicOffHeapValueHolder.java, impl/src/main/java/org/ehcache/impl/internal/store/offheap/BinaryOffHeapValueHolder.java, impl/src/main/java/org/ehcache/impl/internal/store/offheap/LazyOffHeapValueHolder.java, impl/src/main/java/org/ehcache/impl/internal/store/offheap/OffHeapValueHolder.java, impl/src/main/java/org/ehcache/impl/internal/store/offheap/portability/OffHeapValueHolderPortability.java, impl/src/test/java/org/ehcache/impl/internal/store/offheap/BasicOffHeapValueHolderTest.java, impl/src/test/java/org/ehcache/impl/internal/store/offheap/BinaryOffHeapValueHolderTest.java, impl/src/test/java/org/ehcache/impl/internal/store/offheap/LazyOffHeapValueHolderTest.java
* Fixed `BinaryOffHeapValueHolder.value()`
* Clean up of `OffHeapValueHolder` subtypes
=> Issue #828

impl/src/main/java/org/ehcache/impl/internal/store/DefaultStoreProvider.java, transactions/src/main/java/org/ehcache/transactions/xa/internal/XAStore.java, transactions/src/test/java/org/ehcache/transactions/xa/internal/XAStoreTest.java
This commit changes the 'rank' and 'createStore' methods in XAStore.Provider
to use discover the proper Store.Provider to use for the underlying provider
instead of being tied to DefaultStoreProvider.
This commit **does not** close this issue.
=> Issue #798 Add underlying Provider discovery to XAStore.Provider

impl/src/main/java/org/ehcache/impl/internal/spi/serialization/DefaultSerializationProvider.java, impl/src/test/java/org/ehcache/impl/internal/spi/serialization/DefaultSerializationProviderTest.java
The default serializers that were added, while compatible with
persistent caches, were not properly configured. This is now resolved
and there are tests covering that.
=> Issue #860 Default persistent serializers

core/src/main/java/org/ehcache/core/events/StoreEventDispatcher.java, impl/src/main/java/org/ehcache/impl/internal/events/AbstractStoreEventDispatcher.java, impl/src/main/java/org/ehcache/impl/internal/events/CloseableStoreEventSink.java, impl/src/main/java/org/ehcache/impl/internal/events/FireableStoreEventHolder.java, impl/src/main/java/org/ehcache/impl/internal/events/InvocationScopedEventSink.java, impl/src/main/java/org/ehcache/impl/internal/events/NullStoreEventDispatcher.java, impl/src/main/java/org/ehcache/impl/internal/store/offheap/AbstractOffHeapStore.java, impl/src/test/java/org/ehcache/impl/internal/events/InvocationScopedEventSinkTest.java, impl/src/test/java/org/ehcache/impl/internal/events/TestStoreEventDispatcher.java
`compute()` (and friends) might be called many times in case a OversizeMappingException happens. In that case, all pre-recorded events should be dropped as the repeated call recreates those events.
=> #836: fix ordered event handling when OversizeMappingException happens

107/src/main/java/org/ehcache/jsr107/ConfigurationMerger.java, 107/src/main/java/org/ehcache/jsr107/Eh107IdentityCopier.java, 107/src/test/java/org/ehcache/docs/EhCache107ConfigurationIntegrationDocTest.java, 107/src/test/java/org/ehcache/jsr107/ConfigurationMergerTest.java, 107/src/test/resources/ehcache-107-copiers-immutable-types.xml, 107/src/test/resources/ehcache-107-default-copiers.xml, 107/src/test/resources/ehcache-107-immutable-types-cm-level-copiers.xml, 107/src/test/resources/org/ehcache/docs/ehcache-jsr107-template-override.xml
* Creating a copy of IdentityCopier in JSR i.e. 'Eh107IdentityCopier' since thye logic of deciding whether as cache is storebyval or not depends on the kind of Copier configured for val type(in case of template overriding).
=> Adding Default Copiers for better perf in jsr #806

107/src/main/java/org/ehcache/jsr107/Eh107Configuration.java, api/src/main/java/org/ehcache/CacheManager.java, api/src/main/java/org/ehcache/config/Builder.java, api/src/main/java/org/ehcache/config/CacheRuntimeConfiguration.java, clustered/client/src/main/java/org/ehcache/clustered/client/config/builders/ClusteringServiceConfigurationBuilder.java, core/src/main/java/org/ehcache/core/EhcacheManager.java, core/src/main/java/org/ehcache/core/EhcacheRuntimeConfiguration.java, core/src/main/java/org/ehcache/core/events/CacheEventListenerConfiguration.java, core/src/test/java/org/ehcache/core/EhcacheManagerTest.java, impl/src/main/java/org/ehcache/config/builders/CacheConfigurationBuilder.java, impl/src/main/java/org/ehcache/config/builders/CacheEventListenerConfigurationBuilder.java, impl/src/main/java/org/ehcache/config/builders/CacheManagerBuilder.java, impl/src/main/java/org/ehcache/config/builders/ConfigurationBuilder.java, impl/src/main/java/org/ehcache/config/builders/PooledExecutionServiceConfigurationBuilder.java, impl/src/main/java/org/ehcache/config/builders/ResourcePoolsBuilder.java, impl/src/main/java/org/ehcache/config/builders/UserManagedCacheBuilder.java, impl/src/main/java/org/ehcache/config/builders/WriteBehindConfigurationBuilder.java, impl/src/main/java/org/ehcache/impl/config/event/DefaultCacheEventListenerConfiguration.java, impl/src/test/java/org/ehcache/impl/internal/spi/event/DefaultCacheEventListenerProviderTest.java, integration-test/src/test/java/org/ehcache/integration/SimpleEhcacheTest.java, xml/src/main/java/org/ehcache/xml/XmlConfiguration.java
* Enables CacheManager.createCache to be seeded with a Builder of
CacheConfiguration
* Took the opportunity to add some more overloaded methods taking
builders when there was a version taking a configuration
=> Issue #961 Move Builder type to API

docs/src/docs/asciidoc/user/107.adoc, docs/src/docs/asciidoc/user/examples.adoc, docs/src/docs/asciidoc/user/getting-started.adoc, docs/src/docs/asciidoc/user/serializers-copiers.adoc, docs/src/docs/asciidoc/user/xml.adoc, docs/src/docs/asciidoc/user/xsds.adoc
* Use proper asciidoc syntax
* Specify explicit section IDs when referenced
=> Issue #975 Fix inter document links

build.gradle
Its presence causes more grief than anything. Developers needing to
pull locally built artifacts can add it temporarily.
=> Remove mavenLocal() from repo list

107/src/main/java/org/ehcache/jsr107/ConfigurationMerger.java, 107/src/main/java/org/ehcache/jsr107/config/ConfigurationElementState.java, 107/src/main/java/org/ehcache/jsr107/config/Jsr107CacheConfiguration.java, 107/src/main/java/org/ehcache/jsr107/config/Jsr107Configuration.java, 107/src/main/java/org/ehcache/jsr107/config/Jsr107Service.java, 107/src/main/java/org/ehcache/jsr107/internal/DefaultJsr107Service.java, 107/src/main/java/org/ehcache/jsr107/internal/Jsr107CacheConfigurationParser.java, 107/src/main/java/org/ehcache/jsr107/internal/Jsr107ServiceConfigurationParser.java, 107/src/test/java/org/ehcache/jsr107/ConfigStatsManagementActivationTest.java
Instead of using Boolean, enum with unspecified, disabled and enabled
is used to extract configuration information for MBeans in 107.
=> :bug: #992 Replace Boolean with enum for 3 states

clustered/client/src/main/java/org/ehcache/clustered/client/internal/store/operations/BaseOperation.java, clustered/client/src/main/java/org/ehcache/clustered/client/internal/store/operations/OperationCode.java, clustered/client/src/main/java/org/ehcache/clustered/client/internal/store/operations/PutOperation.java, clustered/client/src/main/java/org/ehcache/clustered/client/internal/store/operations/codecs/OperationCodec.java, clustered/client/src/main/java/org/ehcache/clustered/client/internal/store/operations/codecs/OperationCodecFactory.java, clustered/client/src/main/java/org/ehcache/clustered/client/internal/store/operations/codecs/OperationCodecProvider.java, clustered/client/src/main/java/org/ehcache/clustered/client/internal/store/operations/codecs/OperationsCodec.java, clustered/client/src/main/java/org/ehcache/clustered/client/internal/store/operations/codecs/PutOperationCodec.java, clustered/client/src/test/java/org/ehcache/clustered/client/internal/store/operations/codecs/OperationsCodecTest.java, clustered/client/src/test/java/org/ehcache/clustered/client/internal/store/operations/codecs/PutOperationCodecTest.java
A few assumptions made during the operation definition:
- The design was limited to simple get and put operations only.
- A sequence of PUT operations get resolved to the last PUT operation. A need for a different type to represent the resolved value does not exist at the moment as there is not metadata associated with operations. Hence PUT operation can be reused. A new type can be added if the need arises in future.
- Since the initial iteration is not gonna have expiry support the metadata has been completely omitted. Addition of metadata for expiry calculations will depend upon the decision taken on #1015.
=> Issue #1005 Add PUT operation and the codec for the same

impl/src/main/java/org/ehcache/impl/internal/store/disk/OffHeapDiskStore.java, impl/src/main/java/org/ehcache/impl/internal/store/disk/factories/EhcachePersistentSegmentFactory.java, impl/src/main/java/org/ehcache/impl/internal/store/offheap/AbstractOffHeapStore.java, impl/src/main/java/org/ehcache/impl/internal/store/offheap/OffHeapStore.java, impl/src/main/java/org/ehcache/impl/internal/store/offheap/SwitchableEvictionAdvisor.java, impl/src/main/java/org/ehcache/impl/internal/store/offheap/factories/EhcacheSegmentFactory.java, impl/src/test/java/org/ehcache/impl/internal/store/disk/EhcachePersistentConcurrentOffHeapClockCacheTest.java, impl/src/test/java/org/ehcache/impl/internal/store/disk/factories/EhcachePersistentSegmentTest.java, impl/src/test/java/org/ehcache/impl/internal/store/offheap/EhcacheConcurrentOffHeapClockCacheTest.java, impl/src/test/java/org/ehcache/impl/internal/store/offheap/factories/EhcacheSegmentTest.java
* Introduce sub interface of EvictionAdvisor that can be disabled
* Wire said interface in all the offheap related types that knew
about EvictionAdvisor
* Simplify OverSizeMappingException handling following what's
currently done in offheap
* Trigger the InvalidationValve and disable EvictionAdvisor
=> :construction: Fix #1030 Update handling of over size mappings

clustered/client/src/main/java/org/ehcache/clustered/client/internal/store/ClusteredStore.java, clustered/client/src/main/java/org/ehcache/clustered/client/internal/store/ClusteredValueHolder.java, clustered/client/src/main/java/org/ehcache/clustered/client/internal/store/ResolvedChain.java, clustered/client/src/main/java/org/ehcache/clustered/client/internal/store/operations/BaseKeyValueOperation.java, clustered/client/src/main/java/org/ehcache/clustered/client/internal/store/operations/BaseOperation.java, clustered/client/src/main/java/org/ehcache/clustered/client/internal/store/operations/ChainResolver.java, clustered/client/src/main/java/org/ehcache/clustered/client/internal/store/operations/KeyValueOperation.java, clustered/client/src/main/java/org/ehcache/clustered/client/internal/store/operations/Operation.java, clustered/client/src/main/java/org/ehcache/clustered/client/internal/store/operations/OperationCode.java, clustered/client/src/main/java/org/ehcache/clustered/client/internal/store/operations/OperationResolver.java, clustered/client/src/main/java/org/ehcache/clustered/client/internal/store/operations/PutIfAbsentOperation.java, clustered/client/src/main/java/org/ehcache/clustered/client/internal/store/operations/PutOperation.java, clustered/client/src/main/java/org/ehcache/clustered/client/internal/store/operations/RemoveOperation.java, clustered/client/src/main/java/org/ehcache/clustered/client/internal/store/operations/codecs/BaseKeyValueOperationCodec.java, clustered/client/src/main/java/org/ehcache/clustered/client/internal/store/operations/codecs/BaseOperationCodec.java, clustered/client/src/main/java/org/ehcache/clustered/client/internal/store/operations/codecs/CodecException.java, clustered/client/src/main/java/org/ehcache/clustered/client/internal/store/operations/codecs/OperationCodecFactory.java, clustered/client/src/main/java/org/ehcache/clustered/client/internal/store/operations/codecs/OperationCodecProvider.java, clustered/client/src/main/java/org/ehcache/clustered/client/internal/store/operations/codecs/OperationsCodec.java, clustered/client/src/main/java/org/ehcache/clustered/client/internal/store/operations/codecs/PutIfAbsentOperationCodec.java, clustered/client/src/main/java/org/ehcache/clustered/client/internal/store/operations/codecs/PutOperationCodec.java, clustered/client/src/main/java/org/ehcache/clustered/client/internal/store/operations/codecs/RemoveOperationCodec.java, clustered/client/src/main/java/org/ehcache/clustered/client/internal/store/operations/codecs/RootOperationCodec.java, clustered/client/src/test/java/org/ehcache/clustered/client/BasicClusteredCacheTest.java, clustered/client/src/test/java/org/ehcache/clustered/client/docs/GettingStarted.java, clustered/client/src/test/java/org/ehcache/clustered/client/internal/store/operations/ChainResolverTest.java, clustered/client/src/test/java/org/ehcache/clustered/client/internal/store/operations/codecs/PutOperationCodecTest.java, clustered/integration-test/src/test/java/org/ehcache/clustered/BasicCacheCrudTest.java, impl/src/main/java/org/ehcache/impl/internal/store/AbstractValueHolder.java
This is my initial work on how to do the chain resolution. `OperationResolver` and `OperationResolverTest` are the pieces of interest here. The `Operation` classes were also modified to handle the resolution in a "functional" way. I took the liberty of adding the remove and putIfAbsent operations to better demonstrate the resolve logic that I have implemented. These can be removed before the final commit. Keeping those wouldn't hurt either.
=> Clustered store get and put implementation

clustered/client/src/test/java/org/ehcache/clustered/client/BasicClusteredCacheTest.java, clustered/client/src/test/java/org/ehcache/clustered/client/SimpleClusteredCacheByXmlTest.java, clustered/client/src/test/java/org/ehcache/clustered/client/docs/GettingStarted.java, clustered/client/src/test/java/org/ehcache/clustered/client/internal/UnitTestConnectionService.java, clustered/client/src/test/java/org/ehcache/clustered/client/internal/store/ServerStoreProxyTest.java, clustered/client/src/test/java/org/ehcache/clustered/client/service/DefaultClusteringServiceTest.java
This commit moves `UnitTestConnectionService` to support test-specific server configuration -- for all intents and purposes, `UnitTestConnectionService` is rewritten.  All existing uses of `UnitTestConnectionService` are changed to make use of the updates.
=> Issue #763 Rewrite UnitTestConnectionService

clustered/client/src/main/java/org/ehcache/clustered/client/internal/EhcacheClientEntityFactory.java, clustered/client/src/main/java/org/ehcache/clustered/client/internal/EhcacheEntityBusyException.java, clustered/client/src/main/java/org/ehcache/clustered/client/internal/EhcacheEntityNotFoundException.java, clustered/client/src/main/java/org/ehcache/clustered/client/internal/service/DefaultClusteringService.java, clustered/client/src/main/java/org/ehcache/clustered/client/service/ClusteringService.java, clustered/client/src/test/java/org/ehcache/clustered/client/internal/EhcacheClientEntityFactoryTest.java, clustered/client/src/test/java/org/ehcache/clustered/client/internal/UnitTestConnectionService.java, clustered/client/src/test/java/org/ehcache/clustered/client/internal/service/DefaultClusteringServiceTest.java, clustered/client/src/test/java/org/ehcache/clustered/client/internal/service/TestServiceProvider.java, clustered/client/src/test/java/org/ehcache/clustered/client/internal/store/ServerStoreProxyTest.java, clustered/client/src/test/java/org/ehcache/clustered/server/ObservableEhcacheServerEntityService.java, clustered/client/src/test/java/org/ehcache/clustered/server/package-info.java, clustered/integration-test/src/test/java/org/ehcache/clustered/EhcacheClientEntityFactoryIntegrationTest.java, clustered/server/src/main/java/org/ehcache/clustered/server/EhcacheActiveEntity.java
This commit focuses on implementing unit tests on
DefaultClusteringService.  It also includes corrections for defects
discovered during unit test construction.
* DefaultClusteringServiceTest is substantially extended; this was the
primary objective of this commit.
* ObservableEhcacheServerEntityService is added to permit making
assertions about the EhcacheActiveEntity during unit tests performed
with the aid of PassthroughServer.  This class is intentionally
added in a package "owned" by the clustered/server module to permit
access to otherwise package-private details during unit tests.
* DefaultClusteringService.create was creating and holding a client
entity (logical connection); this commit closes that entity and no
longer returns an EhcacheClientEntity from create.
* …
=> Issue #763 DefaultClusteringService unit tests

clustered/client/src/main/java/org/ehcache/clustered/client/internal/store/ClusteredStore.java, clustered/client/src/main/java/org/ehcache/clustered/client/internal/store/ServerStoreProxy.java, clustered/client/src/test/java/org/ehcache/clustered/client/docs/GettingStarted.java, clustered/client/src/test/java/org/ehcache/clustered/client/internal/store/ServerStoreProxyTest.java, clustered/common/src/main/java/org/ehcache/clustered/common/messages/ServerStoreMessageFactory.java, clustered/common/src/main/java/org/ehcache/clustered/common/messages/ServerStoreOpCodec.java, clustered/common/src/main/java/org/ehcache/clustered/common/messages/ServerStoreOpMessage.java, clustered/common/src/main/java/org/ehcache/clustered/common/store/ServerStore.java, clustered/common/src/test/java/org/ehcache/clustered/common/messages/ServerStoreOpCodecTest.java, clustered/integration-test/src/test/java/org/ehcache/clustered/BasicCacheCrudTest.java, clustered/server/src/main/java/org/ehcache/clustered/server/EhcacheActiveEntity.java, clustered/server/src/main/java/org/ehcache/clustered/server/ServerStoreImpl.java, clustered/server/src/main/java/org/ehcache/clustered/server/offheap/OffHeapChainMap.java, clustered/server/src/main/java/org/ehcache/clustered/server/offheap/OffHeapServerStore.java, clustered/server/src/test/java/org/ehcache/clustered/server/store/impl/ReferenceStoreImpl.java
The message encoding of `ServerStoreOpMessage.ClearMessage` can  definitely be improved. Currently it is unnecessarily encoding a key along with the *cacheId*. This is really not required but to fix that I'd have had to refactor some code in the codec class. Since @AbfrmBlr is already working on refactoring that part of the code I did not want to cause a conflict. So I'll fix this once his work gets merged.
Now containsKey could have been implemented like _return get(key) != null_ as @lorban suggested.
But just to avoid the new `ClusteredValueHolder` creation and the meta-data updates that would happen with a get in future, I have done it differently(which caused some code duplication). If no one really cares about that difference then I could revert. I was just trying to keep it as …
=> Issue #1075 Completing CRUD operations on clustered store

clustered/client/src/test/java/org/ehcache/clustered/client/internal/UnitTestConnectionService.java
This commit changes UnitTestConnectionService.remove to absorb the
AssertionError that may be thrown by PassthroughConnection.close after
PassthroughServer.stop is called.  The PassthroughConnection.close
behavior appears to be introduced at Terracotta-OSS/terracotta-apis
build 65.
This commit closes issue #1112.
=> Issue #1112 Prevent test failures closing PassthroughConnection

clustered/client/src/test/java/org/ehcache/clustered/client/NonClusteredCacheTest.java, clustered/client/src/test/java/org/ehcache/clustered/client/config/ClusteringServiceConfigurationTest.java, clustered/client/src/test/java/org/ehcache/clustered/client/internal/EhcacheClientEntityFactoryTest.java, clustered/client/src/test/java/org/ehcache/clustered/client/internal/service/DefaultClusteringServiceTest.java, clustered/integration-test/src/test/java/org/ehcache/clustered/EhcacheClientEntityFactoryIntegrationTest.java, transactions/src/test/java/org/ehcache/transactions/NonXACacheTest.java
This commit stream closes #763 by updating tests for `EhcacheClientEntityFactory`, `ClusteringServiceConfiguration`, and `DefaultClusteringService`.  This commit stream enables previously disabled tests for the `EhcacheClientEntity.destroy` and `DefaultClusteringService.destroyAll` methods.
A test for #1098 along with a parallel test for XA is also included in this commit stream.
=> Issue #763 Unit tests for EhcacheClientEntityFactory

clustered/client/src/main/java/org/ehcache/clustered/client/internal/EhcacheClientEntity.java, clustered/client/src/main/java/org/ehcache/clustered/client/internal/store/ClusteredStore.java, clustered/client/src/main/java/org/ehcache/clustered/client/internal/store/EventualServerStoreProxy.java, clustered/client/src/main/java/org/ehcache/clustered/client/internal/store/NoInvalidationServerStoreProxy.java, clustered/client/src/main/java/org/ehcache/clustered/client/internal/store/ServerStoreProxy.java, clustered/client/src/main/java/org/ehcache/clustered/client/internal/store/StrongServerStoreProxy.java, clustered/client/src/test/java/org/ehcache/clustered/client/internal/EhcacheClientEntityHelper.java, clustered/client/src/test/java/org/ehcache/clustered/client/internal/store/EventualServerStoreProxyTest.java, clustered/client/src/test/java/org/ehcache/clustered/client/internal/store/StrongServerStoreProxyTest.java, clustered/common/src/main/java/org/ehcache/clustered/common/messages/EhcacheEntityResponse.java, clustered/common/src/main/java/org/ehcache/clustered/common/messages/ResponseCodec.java, clustered/common/src/main/java/org/ehcache/clustered/common/messages/ServerStoreMessageFactory.java, clustered/common/src/main/java/org/ehcache/clustered/common/messages/ServerStoreOpCodec.java, clustered/common/src/main/java/org/ehcache/clustered/common/messages/ServerStoreOpMessage.java, clustered/server/src/main/java/org/ehcache/clustered/server/EhcacheActiveEntity.java, clustered/server/src/test/java/org/ehcache/clustered/server/EhcacheActiveEntityTest.java
I added a couple more TODO's in `ServerStoreOpMessage` as we now have two messages that do not need a key but do have to send 8 bytes on the wire to act as that key.
=>  #1007 ServerStore.clear() invalidation handling, both strong and eventual

build.gradle, management/build.gradle
Replaces #1128 to solve classpath issue.
- management jars must be the same everywhere
- Ehcache master can point to management's snapshots
=> Replaces #1128 to solve classpath issue.

clustered/client/src/main/java/org/ehcache/clustered/client/internal/service/DefaultClusteringService.java, clustered/integration-test/build.gradle, clustered/integration-test/src/test/java/com/tc/logging/TestLoggingService.java, clustered/integration-test/src/test/java/org/ehcache/Diagnostics.java, clustered/integration-test/src/test/java/org/ehcache/clustered/TerminatedServerTest.java, clustered/integration-test/src/test/resources/META-INF/services/com.tc.logging.TCLoggingService
This commit changes the behavior of DefaultClusteringService.close to
avoid Entity calls that might result in an interaction with the server.
Server interactions made when the server is disconnected can result in
operation stalls which are not resolved until the server returns to
service.  This kind of stall makes little sense when closing a
CacheManager.
This commit also adds an integration-test test case to reproduce the
symptoms of the issue.  TestLoggingService is added to enable
client-side logging from integration-test unit tests.
Fixes #1108.
=> Issue #1108 Prevent client stall on CacheManager.close

clustered/common/src/main/java/org/ehcache/clustered/common/messages/ServerStoreOpCodec.java, clustered/common/src/main/java/org/ehcache/clustered/common/messages/ServerStoreOpMessage.java, clustered/common/src/test/java/org/ehcache/clustered/common/messages/ServerStoreMessageFactoryTest.java, clustered/common/src/test/java/org/ehcache/clustered/common/messages/ServerStoreOpCodecTest.java, clustered/server/src/main/java/org/ehcache/clustered/server/EhcacheActiveEntity.java
The intention was to avoid using the extra 8 bytes for key in the clear message and the invalidation ack message. But while I was at it I could minimize the byte consumption of the get message and replace message as well by doing some reordering of the fields in encoding and decoding.
=> Improving the byte consumption of store operation messages

clustered/client/src/main/java/org/ehcache/clustered/client/internal/store/ClusteredStore.java, clustered/client/src/test/java/org/ehcache/clustered/client/internal/store/ClusteredStoreTest.java, clustered/integration-test/src/test/java/org/ehcache/clustered/BasicClusteredCacheOpsTest.java, core/src/main/java/org/ehcache/core/Ehcache.java
This is a bloody hack of the store's bulk compute methods tailored to work with only cache's get, put and remove methods ONLY. The stats are not wired in. There is no test coverage except for an integration test that I wrote to check if things would work with this hack. Raising this PR just to validate my approach. Don't wanna waste time doing this if this isn't what's expected.
=> Issue #1144 Clustered store bulk operations

buildSrc/src/main/groovy/EhDistribute.groovy, buildSrc/src/main/groovy/EhDocs.groovy, clustered/clustered-dist/gradle.properties
Some modules do not need to produce an SPI jar (ie clustered-dist)
Also removed unused imports from plugins
=> Conditional disable flag for generation of SPI javadocs and jar

clustered/client/src/main/java/org/ehcache/clustered/client/internal/EhcacheClientEntityFactory.java, clustered/client/src/main/java/org/ehcache/clustered/client/internal/service/AbstractClientEntityFactory.java, clustered/client/src/main/java/org/ehcache/clustered/client/internal/service/DefaultClusteringService.java, clustered/client/src/main/java/org/ehcache/clustered/client/service/ClientEntityFactory.java, clustered/client/src/main/java/org/ehcache/clustered/client/service/EntityBusyException.java, clustered/client/src/main/java/org/ehcache/clustered/client/service/EntityService.java, clustered/client/src/test/java/org/ehcache/clustered/client/EntityServiceTest.java
This is a proposal for #1003.
The goal is to be able from other Ehcache services (such as management) to fetch other entities through the same cluster connection. This will come in another PR later (that will depend on this one).
I didn't want to reuse the existing `EhcacheClientEntityFactory` which does really special things concerning Ehcache config validation. 
So I instead created an isolated `ClientEntityFactory`, accessible from the `ClusteringService`, responsible to create, retrieve and destroy entities... This only depends on spi stuff and does not expose internal stuff.
Note: I moved `EhcacheEntityBusyException ` to `EntityBusyException `, into the non internal package since this exception is also used and not really related to a special Ehcache op, because it is used the same …
=> Closes #1003 - Expose a way to fetch/create entities re-using the same connetion

clustered/server/src/main/java/org/ehcache/clustered/server/EhcacheActiveEntity.java, clustered/server/src/main/java/org/ehcache/clustered/server/ServerStoreImpl.java, clustered/server/src/main/java/org/ehcache/clustered/server/offheap/OffHeapServerStore.java
During rapid creation/destruction of caches/cache managers,
I observed that GC did not cleanup the dangling offheap resources
leading to extremely high memory consumption and an eventual
failure to allocate more buffers.
The theory was that the object was to complex for easy GC'ing in the
direct buffer allocation path. By closing the server store, we
eventually remove the reference to each of the ChainMaps, which then
makes it easy for the GC to clean up the memory.
=> #1282 Add close() method down ServerStoreImpl chain.

management/src/main/java/org/ehcache/management/registry/DefaultCollectorService.java, management/src/test/java/org/ehcache/management/registry/DefaultCollectorServiceTest.java
Prepares #1004, do not include any clustering work.
Collector service, if setup, is automatically started once CM is initialized.
=> Improving collector speed and auto-start at CM init (#1004)

clustered/client/src/main/java/org/ehcache/clustered/client/internal/EhcacheClientEntity.java, clustered/client/src/test/java/org/ehcache/clustered/client/internal/service/EhcacheClientEntityExceptionTest.java, clustered/common/src/main/java/org/ehcache/clustered/common/internal/exceptions/ClusteredEhcacheException.java, clustered/common/src/main/java/org/ehcache/clustered/common/internal/exceptions/IllegalMessageException.java, clustered/common/src/main/java/org/ehcache/clustered/common/internal/exceptions/InvalidServerSideConfigurationException.java, clustered/common/src/main/java/org/ehcache/clustered/common/internal/exceptions/InvalidServerStoreConfigurationException.java, clustered/common/src/main/java/org/ehcache/clustered/common/internal/exceptions/InvalidStoreException.java, clustered/common/src/main/java/org/ehcache/clustered/common/internal/exceptions/InvalidStoreManagerException.java, clustered/common/src/main/java/org/ehcache/clustered/common/internal/exceptions/LifecycleException.java, clustered/common/src/main/java/org/ehcache/clustered/common/internal/exceptions/ResourceBusyException.java, clustered/common/src/main/java/org/ehcache/clustered/common/internal/exceptions/ResourceConfigurationException.java, clustered/common/src/main/java/org/ehcache/clustered/common/internal/exceptions/ServerMisconfigurationException.java, clustered/common/src/test/java/org/ehcache/clustered/common/internal/exceptions/BaseClusteredEhcacheExceptionTest.java, clustered/common/src/test/java/org/ehcache/clustered/common/internal/exceptions/IllegalMessageExceptionTest.java, clustered/common/src/test/java/org/ehcache/clustered/common/internal/exceptions/InvalidServerSideConfigurationExceptionTest.java, clustered/common/src/test/java/org/ehcache/clustered/common/internal/exceptions/InvalidServerStoreConfigurationExceptionTest.java, clustered/common/src/test/java/org/ehcache/clustered/common/internal/exceptions/InvalidStoreExceptionTest.java, clustered/common/src/test/java/org/ehcache/clustered/common/internal/exceptions/InvalidStoreManagerExceptionTest.java, clustered/common/src/test/java/org/ehcache/clustered/common/internal/exceptions/LifecycleExceptionTest.java, clustered/common/src/test/java/org/ehcache/clustered/common/internal/exceptions/ResourceBusyExceptionTest.java, clustered/common/src/test/java/org/ehcache/clustered/common/internal/exceptions/ResourceConfigurationExceptionTest.java, clustered/common/src/test/java/org/ehcache/clustered/common/internal/exceptions/ServerMisconfigurationExceptionTest.java
This commit restores the behavior of wrapping a server-wide exception
received as a clustered operation response in a client-side exception.
This ensures that the client-side stack trace is available in the thrown
exception.
Closes #1256
=> Issue #1256 Wrap Exception in server response in client-side exception

clustered/integration-test/src/test/java/org/ehcache/clustered/TerminatedServerTest.java
Reduce TerminatedServerTest concurrency from 1/2 of the tests (and no
more the number of processors) to 1/3 of the tests (and no more than
the number of processors).  1/2 was too much under some load conditions
in the build environment.
=> Amend TerminatedServerTest concurrency

build.gradle, clustered/integration-test/src/test/java/org/ehcache/clustered/TerminatedServerTest.java
Test concurrency is disabled in TerminatedServerTest if the
'disable.concurrent.tests' Java system property is set.  build.gradle
is changed to set this property to 'true' if running on CloudBees.
The concurrency level for non-CloudBees environments is changed
to the lesser of 1/2 the number of tests and the number of available
processors.
CloudBees detection is done by checking for 'cloudbees' in the
JENKINS_URL environment variable.  Setting JENKINS_URL to
'cloudbees' can be used to inhibit concurrent test execution in
non-CloudBees environments.
=> Conditionally disable TerminatedServerTest concurrency

clustered/client/src/main/java/org/ehcache/clustered/client/internal/store/ClusteredStore.java, clustered/client/src/test/java/org/ehcache/clustered/client/internal/store/ClusteredStoreTest.java, core/src/main/java/org/ehcache/core/statistics/StoreOperationOutcomes.java
Added the outcome only for get operations. Handling of mutative operations yet to be decided.
=> Closes #1276 Add TIMEOUT as an operation outcome for get operation stats

clustered/client/src/main/java/org/ehcache/clustered/client/config/ClusteringServiceConfiguration.java, clustered/client/src/main/resources/ehcache-clustered-ext.xsd, clustered/client/src/test/java/org/ehcache/clustered/client/config/ClusteringServiceConfigurationTest.java, management/build.gradle, management/src/main/java/org/ehcache/management/cluster/Clustering.java, management/src/main/java/org/ehcache/management/cluster/ClusteringManagementService.java, management/src/main/java/org/ehcache/management/cluster/DefaultClusteringManagementService.java, management/src/main/java/org/ehcache/management/registry/DefaultCollectorService.java, management/src/main/java/org/ehcache/management/registry/DefaultManagementRegistryService.java, management/src/main/java/org/ehcache/management/registry/DefaultSharedManagementService.java, management/src/test/java/org/ehcache/management/cluster/ClusteringManagementServiceTest.java, management/src/test/resources/META-INF/services/org.terracotta.connection.ConnectionService, management/src/test/resources/ehcache-management-clustered.xml
In a nutshell, we "just" need to figure out what to do with the "passthrough" scheme
Closes #1004. 
Adds support for clustering in management module.
Several notes:
__1.__ I moved several versions from `clustered` to the top build file because some versions are common from management and clustered and management depends on clustered (provided)
=> Confirmed with @chrisdennis and @cljohnso : OK (only impact on clustered is the dependency on tc-platform, which still compile fine and pass the IT tests)
__2.__ To avoid creating another module depending on both management AND clustered, I put the clustering work in an isolated package which won't impact the standalone usage. Thus, the clustering management service is started by the Management registry service ONLY if the `EntityService` is …
=> Issue #1004 - Clustered management support 

clustered/client/src/main/java/org/ehcache/clustered/client/internal/EhcacheClientEntity.java, clustered/client/src/main/java/org/ehcache/clustered/client/internal/service/DefaultClusteringService.java, clustered/client/src/test/java/org/ehcache/clustered/client/CacheManagerDestroyTest.java, clustered/client/src/test/java/org/ehcache/clustered/client/ClusteredCacheDestroyTest.java, clustered/server/src/main/java/org/ehcache/clustered/server/EhcacheActiveEntity.java
When a cache cannot be destroyed because it is still in use, the
message was limited to the bottom cause. This makes it apparent from
the top of the exception hierarchy.
Also cleaned up tests related to destroyCache
=> Fix #1275 Improve error message for destroyCache

impl/src/main/java/org/ehcache/config/builders/UserManagedCacheBuilder.java, integration-test/src/test/java/org/ehcache/integration/PersistentUserManagedCacheTest.java
For user managed caches, the persistence space created was not
released and thus for disk based caches no serializer state was ever
saved.
=> Fix #1298 Release of persistence space for user managed

clustered/client/src/main/java/org/ehcache/clustered/client/config/ClusteringServiceConfiguration.java, clustered/client/src/main/java/org/ehcache/clustered/client/config/builders/ClusteringServiceConfigurationBuilder.java, clustered/client/src/main/java/org/ehcache/clustered/client/internal/EhcacheClientEntity.java, clustered/client/src/main/java/org/ehcache/clustered/client/internal/config/xml/ClusteringServiceConfigurationParser.java, clustered/client/src/main/java/org/ehcache/clustered/client/internal/service/DefaultClusteringService.java, clustered/client/src/test/java/org/ehcache/clustered/client/config/ClusteringServiceConfigurationTest.java, clustered/client/src/test/java/org/ehcache/clustered/client/internal/config/xml/ClusteringServiceConfigurationParserTest.java, management/src/test/resources/clusteredConfiguration.txt
Previously the ClusteringServiceConfiguration could have a null field
. This commit changes that by making sure to use the defined default.
This simplifies configuration handling by not having to perform null
checks.
=> Fix #1344 Default timeout in configuration

core/src/main/java/org/ehcache/core/config/store/StoreEventSourceConfiguration.java
Since this change has no major impact on load tests that are effectively using ordered events - let's go with it.
=> Issue #1196 Single queue for event ordering

management/src/main/java/org/ehcache/management/cluster/Clustering.java, management/src/main/java/org/ehcache/management/cluster/ClusteringManagementServiceConfiguration.java, management/src/main/java/org/ehcache/management/cluster/DefaultClusteringManagementService.java, management/src/main/java/org/ehcache/management/cluster/DefaultClusteringManagementServiceConfiguration.java, management/src/main/java/org/ehcache/management/cluster/LoggingExecutor.java, management/src/main/java/org/ehcache/management/registry/DefaultManagementRegistryService.java
When using the client communicator, the execution should be delegated to another thread.
So this PR is to use the ehcache execution service to create an executor specialized in executing the management call requests in another thread.
=> clustered management - fix missing thread delegation when receiving management call requests

management/src/main/java/org/ehcache/management/cluster/ClusteringManagementServiceConfiguration.java, management/src/main/java/org/ehcache/management/cluster/DefaultClusteringManagementService.java, management/src/main/java/org/ehcache/management/cluster/DefaultClusteringManagementServiceConfiguration.java, management/src/main/java/org/ehcache/management/registry/DefaultCollectorService.java
do not call cacheManager.getStatus() into a scheduled task
because it would block the shutdown of the executor
=> do not call cacheManager.getStatus() into a scheduled task because it would block the shutdown of the executor

build.gradle, management/src/main/java/org/ehcache/management/cluster/DefaultClusteringManagementService.java, management/src/test/java/org/ehcache/management/cluster/ClusteringManagementServiceTest.java
Updates:
- apis - 1.0.4.beta
- passthrough-testing - 1.0.4.beta
- config - 10.0.4.beta
- core - 5.0.4-beta
- galvan - 1.0.4-beta
- tc-platform - 5.0.4.beta
Compat' with Terracotta-OSS/terracotta-platform#129
(new tc-platform snapshot)
@anthonydahanne : this can be merged when Terracotta-OSS/terracotta-platform#129 will be merged AND tc-platform __5.0.4.beta__ will be released.
This is part of the work for #1008
=> Compat' with new tc-platform and tc-apis

clustered/client/src/main/java/org/ehcache/clustered/client/internal/store/operations/BaseKeyValueOperation.java, clustered/client/src/main/java/org/ehcache/clustered/client/internal/store/operations/ChainResolver.java, clustered/client/src/main/java/org/ehcache/clustered/client/internal/store/operations/ConditionalReplaceOperation.java, clustered/client/src/main/java/org/ehcache/clustered/client/internal/store/operations/LazyValueHolder.java, clustered/client/src/test/java/org/ehcache/clustered/client/internal/store/operations/ChainResolverTest.java, clustered/client/src/test/java/org/ehcache/clustered/client/internal/store/operations/LazyValueHolderTest.java
The chain resolution now handles the following cases:
1. Decode value of target operations only when required
2. Avoid decoding values of non-target operations
3. No expiry calculations and expiryTime updates when expiry is not configured
4. Avoid rebuilding the chain after resolution if no compaction has happened
=> Closes #1343 On-demand encode/decode of Operation values during chain resolution

build.gradle, clustered/client/src/main/java/org/ehcache/clustered/client/internal/EhcacheClientEntityFactory.java, clustered/client/src/main/java/org/ehcache/clustered/client/internal/lock/VoltronReadWriteLock.java, clustered/client/src/main/java/org/ehcache/clustered/client/internal/service/AbstractClientEntityFactory.java, clustered/client/src/test/java/org/ehcache/clustered/client/internal/EhcacheClientEntityFactoryTest.java, clustered/client/src/test/java/org/ehcache/clustered/client/internal/lock/VoltronReadWriteLockClientTest.java, clustered/client/src/test/java/org/ehcache/clustered/client/internal/lock/VoltronReadWriteLockTest.java, management/build.gradle, management/src/main/java/org/ehcache/management/cluster/DefaultClusteringManagementService.java, management/src/test/java/org/ehcache/core/EhcacheManagerToStringTest.java, management/src/test/java/org/ehcache/management/cluster/ClusteringManagementServiceTest.java
__Updates:__
- apis - 1.0.6.beta
- passthrough-testing - 1.0.6.beta
- config - 10.0.6.beta
- core - 5.0.6-beta
- galvan - 1.0.6-beta
Before merging this PR, tc-platform __5.0.5.beta__ needs to be released.
Notes:
- Needed to adapt to changes from Terracotta-OSS/terracotta-platform#132
- Using new test entity to test the state of the monitoring tree
- monitoring service is now a builtin service
- management packages have been "normalized"
=> Switching to next releases (1.0.6 and 5.0.6)

clustered/clustered-dist/build.gradle
The dependency on :dist:jar was missing and code has been refactored
to be more compact. The installDist task is now properly configured
as well.
=> Fix #1393 Proper task dependencies for distribution creation

build.gradle, management/src/main/java/org/ehcache/management/providers/statistics/EhcacheStatistics.java, management/src/test/java/org/ehcache/management/cluster/AbstractClusteringManagementTest.java, management/src/test/java/org/ehcache/management/cluster/ClusteringManagementServiceTest.java
This PR is just a rewriting of a big integration test in the management module.
It will help also #1390.
The idea is:
1. split the test in several smaller ones (which is done in this PR)
2. Separate the passthrough part from the tests (see below for reason)
Then, after:
1. Rebase #1390 on top of this PR so that #1390 uses this new test: #1390 will just need to adapt the statistic part, IF needed.
2. Move this test in the clusterd-it module (which will be done after because it requires to get rid of the passthrough things, use galvan instead, use the new release of tc-platform, and also requires that an issue in platform is fixed first: Terracotta-OSS/terracotta-core#297)
=> Rewriting ClusteredManagementServiceTest

clustered/integration-test/src/test/java/org/ehcache/clustered/management/ClusteringManagementServiceTest.java, clustered/integration-test/src/test/java/org/ehcache/clustered/management/EhcacheManagerToStringTest.java, clustered/integration-test/src/test/resources/clusteredConfiguration.txt, core/src/main/java/org/ehcache/core/config/ResourcePoolsImpl.java, core/src/test/java/org/ehcache/core/config/ResourcePoolsImplTest.java
Resolves https://github.com/ehcache/ehcache3/issues/883
sorts the tiers by reverse tier priority (e.g. Heap precedes Off-Heap) instead of by enum index
=> Resolves #883

clustered/server/src/main/java/org/ehcache/clustered/server/ServerStoreImpl.java, clustered/server/src/main/java/org/ehcache/clustered/server/offheap/OffHeapChainMap.java, clustered/server/src/main/java/org/ehcache/clustered/server/offheap/OffHeapServerStore.java, clustered/server/src/test/java/org/ehcache/clustered/server/offheap/ChainMapTest.java, clustered/server/src/test/java/org/ehcache/clustered/server/offheap/OffHeapServerStoreTest.java
This PR introduces a put operations on `ServerStoreImpl` only to be used by `EhcachePassiveEntity`, i.e. why it is not part of the `ServerStore` api as it is not supposed to be used by clients.
Also the implementation is kind of a provisional thing for now, so that work for AP can move forward. The implementation for put needs to be rewritten in much proper way
=> Put operation for passive in serverstore impl

api/src/main/java/org/ehcache/spi/persistence/StateHolder.java, api/src/main/java/org/ehcache/spi/persistence/StateRepository.java, clustered/client/src/main/java/org/ehcache/clustered/client/internal/service/ClusteredStateHolder.java, clustered/client/src/main/java/org/ehcache/clustered/client/internal/service/ClusteredStateRepository.java, clustered/client/src/test/java/org/ehcache/clustered/client/internal/service/ClusteredStateRepositoryReplicationTest.java, docs/src/docs/asciidoc/user/serializers-copiers.adoc, impl/src/main/java/org/ehcache/impl/persistence/FileBasedStateRepository.java, impl/src/main/java/org/ehcache/impl/serialization/CompactJavaSerializer.java, impl/src/main/java/org/ehcache/impl/serialization/TransientStateHolder.java, impl/src/main/java/org/ehcache/impl/serialization/TransientStateRepository.java, impl/src/test/java/org/ehcache/impl/persistence/FileBasedStateRepositoryTest.java, impl/src/test/java/org/ehcache/impl/serialization/TransientStateRepositoryTest.java
In a lot of places variables are still named "xxxMap" instead of "xxxStateHolder". Will do that if the name `StateHolder` gets finalized.
=> Closes #1433 StateRepository provides StateHolder instead of ConcurrentMap

buildSrc/src/main/groovy/EhDistribute.groovy, buildSrc/src/main/groovy/EhOsgi.groovy, buildSrc/src/main/groovy/EhPomMangle.groovy, clustered/clustered-dist/build.gradle, dist/build.gradle
In order to be minimally disruptive I've done this by creating a shadowCompile configuration that we use everywhere, and then using that rather than the "shadow" configuration created by the plugin.  This way all our usage of the configuration should stay intact, but the shadow plugin won't populate the jar classpath manifest entry.
=> Issue #1467 Prevents shadow plugin from populating the 'Class-Path' manifest key

buildSrc/src/main/groovy/EhDistribute.groovy, buildSrc/src/main/groovy/EhOsgi.groovy, buildSrc/src/main/groovy/EhPomMangle.groovy, clustered/clustered-dist/build.gradle, dist/build.gradle
Release 3.1 version of the classpath dist jar build fixes - merge this after reviewing and merging the PR against master.
=> Issue #1467 [release/3.1] Prevents shadow plugin from populating the 'Class-Path' manifest key

clustered/common/build.gradle, clustered/common/src/main/java/org/ehcache/clustered/common/internal/lock/LockMessaging.java, clustered/server/src/main/java/org/ehcache/clustered/lock/server/VoltronReadWriteLockServerEntityService.java, clustered/server/src/main/java/org/ehcache/clustered/lock/server/messages/LockSyncMessaging.java
* clustered common module only depends on common apis
* passive sync codes for the lock have been moved to the server module
=> Fix #1535 Clean up server dependencies that leaked on client

clustered/client/src/main/java/org/ehcache/clustered/client/internal/service/DefaultClusteringService.java, clustered/client/src/test/java/org/ehcache/clustered/client/ClusteredConcurrencyTest.java
The strategy is to try to create the cache on the client. If it works, fine, if is doesn't, the cache validation should then pass. So it's the other way around from what was there.
=> Support concurrent cache creation (close #1278)

build.gradle, clustered/client/build.gradle, clustered/integration-test/build.gradle, clustered/integration-test/src/test/java/org/ehcache/clustered/management/AbstractClusteringManagementTest.java, clustered/integration-test/src/test/java/org/ehcache/clustered/management/ClusteringManagementServiceTest.java, clustered/integration-test/src/test/java/org/ehcache/clustered/management/EhcacheConfigWithManagementTest.java, clustered/integration-test/src/test/java/org/ehcache/clustered/management/EhcacheManagerToStringTest.java, clustered/integration-test/src/test/resources/clusteredConfiguration.txt, clustered/server/build.gradle, clustered/server/src/main/java/org/ehcache/clustered/server/ClientState.java, clustered/server/src/main/java/org/ehcache/clustered/server/EhcacheActiveEntity.java, clustered/server/src/main/java/org/ehcache/clustered/server/EhcachePassiveEntity.java, clustered/server/src/main/java/org/ehcache/clustered/server/EhcacheStateServiceImpl.java, clustered/server/src/main/java/org/ehcache/clustered/server/ServerStoreImpl.java, clustered/server/src/main/java/org/ehcache/clustered/server/management/ClientStateBinding.java, clustered/server/src/main/java/org/ehcache/clustered/server/management/ClientStateSettingsManagementProvider.java, clustered/server/src/main/java/org/ehcache/clustered/server/management/Management.java, clustered/server/src/main/java/org/ehcache/clustered/server/management/OffHeapResourceBinding.java, clustered/server/src/main/java/org/ehcache/clustered/server/management/OffHeapResourceSettingsManagementProvider.java, clustered/server/src/main/java/org/ehcache/clustered/server/management/PoolBinding.java, clustered/server/src/main/java/org/ehcache/clustered/server/management/PoolSettingsManagementProvider.java, clustered/server/src/main/java/org/ehcache/clustered/server/management/ServerStoreBinding.java, clustered/server/src/main/java/org/ehcache/clustered/server/management/ServerStoreSettingsManagementProvider.java, clustered/server/src/main/java/org/ehcache/clustered/server/offheap/OffHeapServerStore.java, clustered/server/src/main/java/org/ehcache/clustered/server/state/EhcacheStateService.java, clustered/server/src/test/java/org/ehcache/clustered/server/EhcacheActiveEntityTest.java, clustered/server/src/test/java/org/ehcache/clustered/server/EhcachePassiveEntityTest.java, management/src/main/java/org/ehcache/management/providers/CacheBindingManagementProvider.java, management/src/main/java/org/ehcache/management/providers/ExposedCacheBinding.java, management/src/main/java/org/ehcache/management/registry/DefaultManagementRegistryService.java
Depends on Terracotta-OSS/terracotta-platform#165
Depends on tc-platform release __5.0.8.beta3__
Close #1008
New events:
- EHCACHE_CLIENT_RECONNECTED
- EHCACHE_RESOURCE_POOLS_CONFIGURED
- EHCACHE_CLIENT_VALIDATED
- EHCACHE_SERVER_STORE_CREATED
- EHCACHE_SERVER_STORE_ATTACHED
- EHCACHE_SERVER_STORE_RELEASED
- EHCACHE_SERVER_STORE_DESTROYED
Exposes management descriptors for stores, client states, pools and server resources.
=> Close Issue #1008 - Expose management data from ehcache server entity

build.gradle, clustered/client/src/test/java/org/ehcache/clustered/client/internal/UnitTestConnectionService.java, clustered/server/build.gradle, clustered/server/src/main/java/org/ehcache/clustered/server/EhcacheStateServiceImpl.java, clustered/server/src/main/java/org/ehcache/clustered/server/ServerStoreImpl.java, clustered/server/src/test/java/org/ehcache/clustered/server/offheap/OffHeapServerStoreTest.java
This check in includes the server side allocatedMemory statistic.  Also I had to increase the build.gradle maxHeapSize to 2048m otherwise 48 of the :clustered:client tests failed because the JVM ran out of memory.  I did try to to avoid this by forcing the passthrough server to call the serverside destroy method but this didn't seem to work.
=> Issue 1530

clustered/server/src/main/java/org/ehcache/clustered/server/EhcacheActiveEntity.java, clustered/server/src/main/java/org/ehcache/clustered/server/EhcacheStateServiceImpl.java, clustered/server/src/main/java/org/ehcache/clustered/server/state/ClientMessageTracker.java
Since most of the *state* of the classes in the change-set have data structures holding life-cycle related state, I didn't have to do much to address concurrent mutations as that will never happen since all the life-cycle operations are run on the same concurrency key. The only thing that I had to ensure was the visibility of these mutating operations. I could address that mostly by replacing non-thread safe data structures with the ones that provide visibility guarantees.
Now am not sure if I'm supposed to write tests for these changes. If yes, I'm gonna need some guidance on writing tests for these kinda changes.
=> Closes #1525 Closes #1418 Making server side data strutures thread-safe

clustered/client/src/main/java/org/ehcache/clustered/client/internal/store/operations/BaseKeyValueOperation.java, clustered/client/src/main/java/org/ehcache/clustered/client/internal/store/operations/ChainResolver.java, clustered/client/src/main/java/org/ehcache/clustered/client/internal/store/operations/ConditionalReplaceOperation.java
* Set limit based on known limit instead of capacity
* rewind instead of flip after decoding
=> [release/3.1] Fix #1569 Proper ByteBuffer usage

build.gradle, clustered/integration-test/src/test/java/org/ehcache/clustered/management/ClusteringManagementServiceTest.java, clustered/server/build.gradle, clustered/server/src/main/java/org/ehcache/clustered/server/EhcacheActiveEntity.java, clustered/server/src/main/java/org/ehcache/clustered/server/EhcacheStateServiceImpl.java, clustered/server/src/main/java/org/ehcache/clustered/server/management/AbstractExposedStatistics.java, clustered/server/src/main/java/org/ehcache/clustered/server/management/AbstractStatisticsManagementProvider.java, clustered/server/src/main/java/org/ehcache/clustered/server/management/Management.java, clustered/server/src/main/java/org/ehcache/clustered/server/management/PoolSettingsManagementProvider.java, clustered/server/src/main/java/org/ehcache/clustered/server/management/PoolStatisticsManagementProvider.java, clustered/server/src/main/java/org/ehcache/clustered/server/management/ServerStoreStatisticsManagementProvider.java, clustered/server/src/main/java/org/ehcache/clustered/server/management/StatisticCollectorManagementProvider.java, clustered/server/src/main/java/org/ehcache/clustered/server/management/StatisticConfiguration.java, clustered/server/src/main/java/org/ehcache/clustered/server/state/EhcacheStateService.java, clustered/server/src/main/java/org/ehcache/clustered/server/state/ResourcePageSource.java
Close #1551 and close #1530.
**Important notes for Ehcache / M&M people:**
__THESE ARE NOT BLOCKERS for M&M: JUST THINGS TO TAKE CARE OF__
1. **TimeSource**
We need in management to get the server time in a uniform way both from ehcache server entity and within the monitoring service. Currently, we are calling: `System.currentTimeMillis()` because there is no time service in voltron.
See `StatisticCollectorManagementProvider` in this PR.
I started a discussion for that: Terracotta-OSS/terracotta-apis#167
1. **Scheduling tasks**
There is no way to schedule a task in voltron yet, so I needed to start a scheduled executor service (the thread is set to daemon) used only by management to compute stats.
See `Management` in this PR
I started an issue for that: Terracotta-OSS/terracotta-apis#158 …
=> Resource usage stats from Ehcache server entity (close #1551 and close #1530)

clustered/server/src/main/java/org/ehcache/clustered/server/EhcachePassiveEntity.java
The creation of client invalidation trackers was missing during the lifecycle state sync phase.
=> Closes #1590 Create eventual client invalidation trackers during lifecycle sync

clustered/client/src/main/java/org/ehcache/clustered/client/internal/EhcacheClientEntity.java, clustered/client/src/main/java/org/ehcache/clustered/client/internal/service/DefaultClusteringService.java, clustered/client/src/main/java/org/ehcache/clustered/client/internal/store/EventualServerStoreProxy.java, clustered/client/src/main/java/org/ehcache/clustered/client/internal/store/NoInvalidationServerStoreProxy.java, clustered/client/src/main/java/org/ehcache/clustered/client/internal/store/ServerStoreProxy.java, clustered/client/src/main/java/org/ehcache/clustered/client/internal/store/StrongServerStoreProxy.java, clustered/client/src/test/java/org/ehcache/clustered/client/internal/service/DefaultClusteringServiceTest.java, clustered/server/src/main/java/org/ehcache/clustered/server/EhcacheActiveEntity.java
Apart from fixing the bug, I have left some of the log statements in different classes  that I used to debug the issue. Most of those are at debug/trace level. Will extend similar logging to the rest of the code base if this is approved.
=> Closes #1593 Avoid response listener registration race during store creation

management/src/test/java/org/ehcache/management/providers/statistics/EvictionTest.java, management/src/test/java/org/ehcache/management/providers/statistics/HitCountTest.java, management/src/test/java/org/ehcache/management/providers/statistics/HitRatioTest.java, management/src/test/java/org/ehcache/management/providers/statistics/MissCountTest.java, management/src/test/java/org/ehcache/management/providers/statistics/MissRatioTest.java
As an attempt to restore build stability.
However if that does not cut it then the tests will need to be looked with more care.
=> Bumping stats tests timeouts

build.gradle, clustered/server/src/main/java/org/ehcache/clustered/server/EhcacheActiveEntity.java, clustered/server/src/main/java/org/ehcache/clustered/server/EhcachePassiveEntity.java, clustered/server/src/main/java/org/ehcache/clustered/server/management/Management.java
to fix management service lifecycle, closing entity requested services from the monitoring service when the entity is gone, to avoid having ehcache knowing it needs to close the management service
In 5.0.13.beta3, I got rid of all weak references and do the cleanup of client descriptors and consumer services thanks to some listeners on the topology changes (when client disconnects and entities are destroyed). This change allows also to get rid of the close() methods that were required before.
=> Upgrade to new tc-platform

build.gradle, clustered/client/src/main/java/org/ehcache/clustered/client/internal/EhcacheClientEntityFactory.java, clustered/client/src/main/java/org/ehcache/clustered/client/internal/lock/VoltronReadWriteLock.java, clustered/client/src/main/java/org/ehcache/clustered/client/internal/service/AbstractClientEntityFactory.java, clustered/client/src/test/java/org/ehcache/clustered/client/internal/UnitTestConnectionService.java, clustered/integration-test/src/test/java/org/ehcache/clustered/replication/BasicLifeCyclePassiveReplicationTest.java
* Adapt to EntityRef.create and EntityRef.destroy API changes
* Adapt to the passthrough changes
=> Bump to latest Terracotta version

clustered/client/src/main/java/org/ehcache/clustered/client/internal/EhcacheClientEntityService.java, clustered/common/src/main/java/org/ehcache/clustered/common/internal/messages/CommonConfigCodec.java, clustered/common/src/main/java/org/ehcache/clustered/common/internal/messages/ConfigCodec.java, clustered/common/src/main/java/org/ehcache/clustered/common/internal/messages/EhcacheCodec.java, clustered/common/src/main/java/org/ehcache/clustered/common/internal/messages/LifeCycleMessageCodec.java, clustered/common/src/main/java/org/ehcache/clustered/common/internal/messages/MessageCodecUtils.java, clustered/common/src/main/java/org/ehcache/clustered/common/internal/messages/ResponseCodec.java, clustered/common/src/main/java/org/ehcache/clustered/common/internal/messages/ServerStoreOpCodec.java, clustered/common/src/main/java/org/ehcache/clustered/common/internal/messages/StateRepositoryOpCodec.java, clustered/common/src/test/java/org/ehcache/clustered/common/internal/messages/CommonConfigCodecTest.java, clustered/common/src/test/java/org/ehcache/clustered/common/internal/messages/LifeCycleMessageCodecTest.java, clustered/server/src/main/java/org/ehcache/clustered/server/EhcacheServerEntityService.java, clustered/server/src/main/java/org/ehcache/clustered/server/internal/messages/EhcacheServerCodec.java, clustered/server/src/main/java/org/ehcache/clustered/server/internal/messages/EhcacheSyncMessageCodec.java, clustered/server/src/main/java/org/ehcache/clustered/server/internal/messages/PassiveReplicationMessageCodec.java, clustered/server/src/test/java/org/ehcache/clustered/server/internal/messages/EhcacheSyncMessageCodecTest.java, clustered/server/src/test/java/org/ehcache/clustered/server/internal/messages/PassiveReplicationMessageCodecTest.java
Encoding and decoding of `ServerSideConfiguration` and `ServerStoreConfiguration` has been refactored out to a common `ConfigCodec` class. This eliminates the encoding/decoding code that was duplicated in lifecycle, replication and sync message codecs. This refactoring will enable extensibility of the codecs as as well.
=> Closes #1678 Refactor codecs to reuse configuration encoding and decoding logic for extensibility

107/src/main/java/org/ehcache/jsr107/Eh107CacheStatisticsMXBean.java, core/src/main/java/org/ehcache/core/Ehcache.java, core/src/main/java/org/ehcache/core/EhcacheWithLoaderWriter.java, core/src/main/java/org/ehcache/core/statistics/CacheOperationOutcomes.java, core/src/test/java/org/ehcache/core/EhcacheBasicGetTest.java, core/src/test/java/org/ehcache/core/EhcacheWithLoaderWriterBasicGetTest.java, management/src/main/java/org/ehcache/management/providers/statistics/StandardEhcacheStatistics.java
Dropped _NO_LOADER / _WITH_LOADER variants since the implementation
classes are now different, there is no possible confusion.
=> Clean up CacheOperationOutcomes.GetOutcome

build.gradle
This bumps the Terracotta version to the latest preview version which gives us a speed up in full system tests.
=> Update to latest Terracotta preview

build.gradle
Allows jobs to add "closeRepository" or "closeAndPromoteRepository" to the task list.
https://github.com/Codearte/gradle-nexus-staging-plugin/
This is a copy of the closed PR #1345 since it is now possible to do this in the absence of JDK 1.6
=> Adding Nexus Staging Plugin - take 2

clustered/client/src/main/java/org/ehcache/clustered/client/internal/EhcacheClientEntity.java, clustered/client/src/main/java/org/ehcache/clustered/client/internal/EhcacheClientEntityFactory.java, clustered/client/src/main/java/org/ehcache/clustered/client/internal/EhcacheClientEntityService.java, clustered/client/src/test/java/org/ehcache/clustered/client/internal/EhcacheClientEntityFactoryTest.java, clustered/client/src/test/java/org/ehcache/clustered/client/replication/LifeCycleMessageActivePassvieReplicationTest.java, clustered/client/src/test/java/org/ehcache/clustered/server/ObservableEhcacheServerEntityService.java, clustered/common/src/main/java/org/ehcache/clustered/common/internal/ClusteredTierManagerConfiguration.java, clustered/common/src/main/java/org/ehcache/clustered/common/internal/messages/EhcacheMessageType.java, clustered/common/src/main/java/org/ehcache/clustered/common/internal/messages/EntityConfigurationCodec.java, clustered/common/src/main/java/org/ehcache/clustered/common/internal/messages/LifeCycleMessageCodec.java, clustered/common/src/main/java/org/ehcache/clustered/common/internal/messages/LifeCycleMessageFactory.java, clustered/common/src/main/java/org/ehcache/clustered/common/internal/messages/LifecycleMessage.java, clustered/common/src/test/java/org/ehcache/clustered/common/internal/messages/LifeCycleMessageCodecTest.java, clustered/integration-test/src/test/java/org/ehcache/clustered/BasicEntityInteractionTest.java, clustered/integration-test/src/test/java/org/ehcache/clustered/replication/BasicLifeCyclePassiveReplicationTest.java, clustered/server/src/main/java/org/ehcache/clustered/server/EhcacheActiveEntity.java, clustered/server/src/main/java/org/ehcache/clustered/server/EhcacheExecutionStrategy.java, clustered/server/src/main/java/org/ehcache/clustered/server/EhcachePassiveEntity.java, clustered/server/src/main/java/org/ehcache/clustered/server/EhcacheServerEntityService.java, clustered/server/src/main/java/org/ehcache/clustered/server/EhcacheStateServiceImpl.java, clustered/server/src/main/java/org/ehcache/clustered/server/state/ClientMessageTracker.java, clustered/server/src/main/java/org/ehcache/clustered/server/state/EhcacheStateService.java, clustered/server/src/main/java/org/ehcache/clustered/server/state/EhcacheStateServiceProvider.java, clustered/server/src/main/java/org/ehcache/clustered/server/state/config/EhcacheStateServiceConfig.java, clustered/server/src/test/java/org/ehcache/clustered/server/EhcacheActiveEntityTest.java, clustered/server/src/test/java/org/ehcache/clustered/server/EhcachePassiveEntityTest.java, clustered/server/src/test/java/org/ehcache/clustered/server/state/EhcacheStateServiceProviderTest.java
* Entity receives configuration during create - much more than the previous `UUID`
* An identifier - currently a `String` by default sourced from the entity URL in the connection
* The `ServerSideConfiguration` that used to be passed during `configure` step
* Entity uses the `CreationException` in case of mismatch between server resources and specified ones, same for shared pools.
* State service destroy effectively removes the instance from the provider
* Clean up related to the above changes
Flagged as no merge for now since this means breaking compatibility of client -> server communication and thus requires bumping version to 3.3.0-SNAPSHOT on master.
(description copied in the issue for better reference)
=> Fix #1710 Entity gets configured when created

107/src/main/java/org/ehcache/jsr107/Eh107Cache.java, 107/src/main/java/org/ehcache/jsr107/Eh107CacheManager.java, 107/src/main/java/org/ehcache/jsr107/Eh107CacheStatisticsMXBean.java, 107/src/main/java/org/ehcache/jsr107/Eh107InternalCacheManager.java, 107/src/main/java/org/ehcache/jsr107/EhcacheCachingProvider.java, core/src/main/java/org/ehcache/core/spi/service/StatisticsService.java, impl/src/main/java/org/ehcache/impl/internal/statistics/CacheStatistics.java, impl/src/main/java/org/ehcache/impl/internal/statistics/DefaultStatisticsService.java, impl/src/main/java/org/ehcache/impl/internal/statistics/DefaultStatisticsServiceFactory.java, impl/src/main/resources/META-INF/services/org.ehcache.core.spi.service.ServiceFactory, impl/src/test/java/org/ehcache/impl/internal/statistics/DefaultStatisticsServiceTest.java
This is the first step of a series of refactoring. It moves the statistics into ehcache.
=> Move JMX statistics to an ehcache service

clustered/server/src/main/java/org/ehcache/clustered/server/offheap/OffHeapServerStore.java
OffheapServerStore was not releasing write locks on destroy.
=> Closes #1754 Release write locks on clear

clustered/client/src/main/java/org/ehcache/clustered/client/internal/EhcacheClientEntityFactory.java, clustered/common/src/main/java/org/ehcache/clustered/common/EhcacheEntityVersion.java, clustered/integration-test/src/test/java/org/ehcache/clustered/BasicEntityInteractionTest.java, clustered/integration-test/src/test/java/org/ehcache/clustered/CacheManagerLifecycleEhcacheIntegrationTest.java, clustered/server/src/main/java/org/ehcache/clustered/server/EhcacheServerEntityService.java
This represents incompatibility - should have been done when the
configuration on create happened ideally.
=> Fix #1752 Bump entity version

build.gradle, clustered/integration-test/src/test/java/org/ehcache/clustered/management/ClusteredStatisticsCountTest.java, clustered/integration-test/src/test/java/org/ehcache/clustered/management/ClusteringManagementServiceTest.java, management/src/main/java/org/ehcache/management/providers/statistics/EhcacheStatisticsProvider.java, management/src/main/java/org/ehcache/management/providers/statistics/StandardEhcacheStatistics.java, management/src/test/java/org/ehcache/docs/ManagementTest.java, management/src/test/java/org/ehcache/management/providers/statistics/EvictionTest.java, management/src/test/java/org/ehcache/management/providers/statistics/StandardEhcacheStatisticsTest.java, management/src/test/java/org/ehcache/management/providers/statistics/StatsUtil.java, management/src/test/java/org/ehcache/management/registry/DefaultManagementRegistryServiceTest.java, management/src/test/java/org/ehcache/management/registry/DefaultSharedManagementServiceTest.java
See: https://github.com/Terracotta-OSS/terracotta-platform/issues/261
Depends on new tc-platform release __5.2.0-pre6__ (https://github.com/Terracotta-OSS/terracotta-platform/pull/264)
Note: All Ehcache tests passed locally with the tc-platform snapshot.
=> Compat' with new tc-platform (get rid of statistic wrappers)

gradle.properties
Defining these props is part of the local project setup, not
something that makes sense to share.
=> [master] Remove java6Home definition from gradle.properties

gradle.properties
Defining these props is part of the local project setup, not
something that makes sense to share.
=> [release/3.2] Remove java6Home definition from gradle.properties

clustered/server/src/main/java/org/ehcache/clustered/server/EhcacheExecutionStrategy.java
This is a temporary change, to last until the _prepare for destroy_ call effectively sets some state server side. Until then, since the passive cannot support the message, make it go to the active only.
=> Issue #1686 For now, prepare for destroy only on active

clustered/client/src/main/java/org/ehcache/clustered/client/internal/service/ClusteredStateRepository.java, clustered/client/src/main/java/org/ehcache/clustered/client/internal/service/ConcurrentClusteredMap.java, clustered/client/src/main/java/org/ehcache/clustered/client/internal/service/ValueCodec.java, clustered/client/src/main/java/org/ehcache/clustered/client/internal/service/ValueCodecFactory.java, clustered/client/src/test/java/org/ehcache/clustered/client/internal/service/ClusteredStateRepositoryReplicationTest.java, clustered/common/src/main/java/org/ehcache/clustered/common/internal/store/ValueWrapper.java
The StateRepository provided map for a clustered cache cannot store
any Serializable type as otherwise the server will fail to
deserialize classes not on its classpath. So keys and values are
encoded to preserve usage flexibility while providing a best effort on
equality contract.
=> [release/3.1] Issue #1814 StateRepository data format change

clustered/common/src/main/java/org/ehcache/clustered/common/internal/store/ValueWrapper.java
Suppressing the warning as the type is used in a specific context
where exposing that byte[] is not an issue.
=> [release/3.2] Issue #1814 Remove findbugs warning

clustered/common/src/main/java/org/ehcache/clustered/common/internal/store/ValueWrapper.java
Suppressing the warning as the type is used in a specific context
where exposing that byte[] is not an issue.
=> [release/3.1] Issue #1814 Remove findbugs warning

clustered/client/src/test/java/org/ehcache/clustered/client/replication/ActivePassiveClientIdTest.java, clustered/client/src/test/java/org/ehcache/clustered/server/ObservableEhcacheServerEntityService.java, clustered/client/src/test/java/org/ehcache/clustered/server/store/ObservableClusterTierServerEntityService.java, clustered/integration-test/src/test/java/org/ehcache/clustered/replication/BasicLifeCyclePassiveReplicationTest.java, clustered/server/src/main/java/org/ehcache/clustered/server/ClusterTierManagerActiveEntity.java, clustered/server/src/main/java/org/ehcache/clustered/server/ClusterTierManagerPassiveEntity.java, clustered/server/src/main/java/org/ehcache/clustered/server/EhcacheStateServiceImpl.java, clustered/server/src/main/java/org/ehcache/clustered/server/management/ClusterTierClientState.java, clustered/server/src/main/java/org/ehcache/clustered/server/management/ClusterTierManagement.java, clustered/server/src/main/java/org/ehcache/clustered/server/state/EhcacheStateService.java, clustered/server/src/main/java/org/ehcache/clustered/server/store/ClusterTierActiveEntity.java, clustered/server/src/main/java/org/ehcache/clustered/server/store/ClusterTierPassiveEntity.java, clustered/server/src/test/java/org/ehcache/clustered/server/ClusterTierManagerPassiveEntityTest.java, clustered/server/src/test/java/org/ehcache/clustered/server/store/ClusterTierActiveEntityTest.java
Client tracking need not happen at the cluster tier manager level as it adds an unnecessary contention point for different caches. So moving that to the cluster tier level.
=> Closes #1834 Client message tracking at cluster tier level

clustered/server/src/main/java/org/ehcache/clustered/server/ClientState.java, clustered/server/src/main/java/org/ehcache/clustered/server/ClusterTierManagerActiveEntity.java, clustered/server/src/main/java/org/ehcache/clustered/server/store/ClusterTierActiveEntity.java
Client ID validation done at the clustered tier must be moved to the clustered tier manager level since all the duplicate client ID resolution logic is at the clustered tier manager level and it's earlier in the life cycle.
=> Fixes #1834 Perform client ID validation at the clustered tier manager level

clustered/client/src/main/java/org/ehcache/clustered/client/internal/store/ClusteredStore.java, clustered/client/src/test/java/org/ehcache/clustered/client/internal/store/ClusteredStoreTest.java, impl/src/main/java/org/ehcache/impl/internal/store/heap/OnHeapStore.java, impl/src/main/java/org/ehcache/impl/internal/store/offheap/AbstractOffHeapStore.java, impl/src/main/java/org/ehcache/impl/internal/util/HashUtils.java, impl/src/test/java/org/ehcache/impl/internal/util/HashUtilsTest.java
We transform the key hash code into a long for the server but need
the transformation to be reversible as it is the basis for
invalidation in caching tiers. This commit extracts the cast based
conversion into a utility class and enriches it.
=> Make hash handling in clustered store explicit

clustered/client/src/test/java/org/ehcache/clustered/client/BasicClusteredCacheTest.java, clustered/server/src/main/java/org/ehcache/clustered/server/EhcacheStateServiceImpl.java, clustered/server/src/main/java/org/ehcache/clustered/server/ServerStoreImpl.java, clustered/server/src/main/java/org/ehcache/clustered/server/offheap/OffHeapServerStore.java, clustered/server/src/test/java/org/ehcache/clustered/server/offheap/OffHeapServerStoreTest.java
For small caches the max page size should be as low as
256 KB so that defragmenetaion in offheap storage is less
=> [release/3.1] Change Max page size for offheap store #1772

impl/src/main/java/org/ehcache/impl/internal/util/HashUtils.java
The bit fiddling done here was causing Long.hashcode to always be zero.
=> Back to simple cast

xml/src/test/resources/configs/docs/getting-started.xml
Required because #1919 is now checking that.
=> Add missing serializer. Use different names for caches (close #1930)

clustered/server/src/main/java/org/ehcache/clustered/server/state/MessageTracker.java, clustered/server/src/test/java/org/ehcache/clustered/server/state/ClientMessageTrackerTest.java
Closes a thread safety issue in the message tracker. Very minor window with very minor possibility of happening, since active does not do message tracking.
Still fixing this for correctness reasons.
=> Closes #1925 Fix message tracker thread safety issue

core/src/main/java/org/ehcache/core/config/BaseCacheConfiguration.java, core/src/test/java/org/ehcache/core/config/BaseCacheConfigurationTest.java
Key type, value type and resource pools cannot be null.
=> [master] Fix #1767 Null check in BaseCacheConfiguration

core/src/main/java/org/ehcache/core/config/BaseCacheConfiguration.java, core/src/test/java/org/ehcache/core/config/BaseCacheConfigurationTest.java
Key type, value type and resource pools cannot be null.
=> [release/3.2] Fix #1767 Null check in BaseCacheConfiguration

buildSrc/src/main/groovy/EhDocs.groovy
Following the build changes the doc generation internal plugin was
not adapted.
=> [master] Issue #1948 Fix javadoc generation

buildSrc/src/main/groovy/EhDocs.groovy
Following the build changes the doc generation internal plugin was
not adapted.
=> [release/3.2] Issue #1948 Fix javadoc generation

docs/src/docs/asciidoc/user/tiering.adoc, impl/src/main/java/org/ehcache/impl/config/store/disk/OffHeapDiskStoreConfiguration.java, impl/src/main/java/org/ehcache/impl/internal/store/disk/OffHeapDiskStore.java, impl/src/test/java/org/ehcache/docs/Tiering.java, impl/src/test/java/org/ehcache/impl/internal/store/disk/OffHeapDiskStoreSPITest.java, impl/src/test/java/org/ehcache/impl/internal/store/disk/OffHeapDiskStoreTest.java, impl/src/test/java/org/ehcache/impl/internal/store/tiering/TieredStoreSPITest.java, impl/src/test/java/org/ehcache/impl/internal/store/tiering/TieredStoreWith3TiersSPITest.java, xml/src/main/java/org/ehcache/xml/ConfigurationParser.java, xml/src/main/java/org/ehcache/xml/XmlConfiguration.java, xml/src/main/resources/ehcache-core.xsd, xml/src/test/java/org/ehcache/xml/XmlConfigurationTest.java, xml/src/test/resources/configs/ehcache-complete.xml, xml/src/test/resources/configs/resources-caches.xml
Do no merge now. I will add a unit test and some documentation first.
However, to prevent loosing my time, I would like a global validation on the implementation. An attribute was added to `OffHeapDiskStoreConfiguration`. The other thing is that the XSD is modified to accept this new attribute. So we might have to wait for a 3.4 release.
=> [3.4] Allow to specify the number of segments created by a disk store (close #1932)

clustered/integration-test/build.gradle
This allows IDE compilation without leaking the classes on the test classpath.
=> [release/3.3] Move added deps to testCompileOnly

clustered/integration-test/build.gradle
This allows IDE compilation without leaking the classes on the test classpath.
=> [master] Move added deps to testCompileOnly

core/src/main/java/org/ehcache/core/EhcacheManager.java, impl/src/test/java/org/ehcache/core/events/CacheManagerListenerInteractionsTest.java
* so that listeners can safely get an update cache manager configuration
=> [master] Close #1996 : remove cache configuration before calling the listeners

core/src/main/java/org/ehcache/core/EhcacheManager.java, impl/src/test/java/org/ehcache/core/events/CacheManagerListenerInteractionsTest.java
* so that listeners can safely get an update cache manager configuration
=> [3.2] Close #1996 : remove cache configuration before calling the listeners

core/src/main/java/org/ehcache/core/EhcacheManager.java, impl/src/test/java/org/ehcache/core/events/CacheManagerListenerInteractionsTest.java
* so that listeners can safely get an update cache manager configuration
=> [3.3] Close #1996 : remove cache configuration before calling the listeners

impl/src/main/java/org/ehcache/impl/internal/executor/OutOfBandScheduledExecutor.java, impl/src/main/java/org/ehcache/impl/internal/executor/PooledExecutionService.java, impl/src/test/java/org/ehcache/impl/internal/executor/PooledExecutionServiceTest.java
It contains an improved javadoc and better test code that can be permanent but that will also be helpful to diagnose with the test is failing
=> Give different names to pools in PooledExecutionServiceTest and make the test reliable

buildSrc/src/main/groovy/EhDeploy.groovy, buildSrc/src/main/groovy/EhDistribute.groovy, buildSrc/src/main/groovy/EhPomGenerate.groovy, buildSrc/src/main/groovy/scripts/Utils.groovy
Including maven metadata (pom.xml/pom.properties) in ehcache-common.jar only.  (primarily for internal use).
=> Including pom.xml and pom.properties in all published jars

buildSrc/src/main/groovy/EhDistribute.groovy
This removes duplicate pom.properties and pom.xml for ehcache in the shaded jar:
$ unzip ../ehcache-xxx.jar 
inflating: META-INF/maven/org.ehcache/ehcache/pom.properties 
replace META-INF/maven/org.ehcache/ehcache/pom.properties? [y]es, [n]o, [A]ll, [N]one, [r]ename:
=> Excluding duplicate pom files from shaded jar.

.gitignore, build.gradle, clustered/clustered-dist/build.gradle
Includes removing reference to `client-logging` which disappeared.
=> Bump to latest Terracotta versions

clustered/client/src/main/java/org/ehcache/clustered/client/internal/store/ClusteredStore.java, clustered/client/src/main/java/org/ehcache/clustered/client/internal/store/operations/BaseKeyValueOperation.java, clustered/client/src/main/java/org/ehcache/clustered/client/internal/store/operations/ChainResolver.java, clustered/client/src/main/java/org/ehcache/clustered/client/internal/store/operations/Operation.java, clustered/client/src/test/java/org/ehcache/clustered/client/ClusteredCacheExpirationTest.java, clustered/client/src/test/java/org/ehcache/clustered/client/internal/store/ClusteredStoreTest.java, clustered/client/src/test/java/org/ehcache/clustered/client/internal/store/operations/ChainResolverTest.java
This is a report about some behavior that has changed in ehcache3 very recently.
* one cache, with 3 tiers : onheap(10 elements max) , offheap (10 MB max), cluster dedicated (50 MB max)
* do 100 puts , each followed by a get on the same key
* onHeap mapping count : 10, offheap mapping count : 90
* onHeap mapping count : 10, offheap mapping count : **0**
=> :bug: Offheap as a middle tier does not seem to be used anymore.

build.gradle
The nexus plugin was correctly configured for oss.sonatype but not for internal use, also upgrading it.
=> correctly configuring nexus staging plugin, upgraded version

clustered/client/src/main/java/org/ehcache/clustered/client/config/ClusteringServiceConfiguration.java, clustered/integration-test/src/test/java/org/ehcache/clustered/management/EhcacheManagerToStringTest.java, clustered/integration-test/src/test/resources/clusteredConfiguration.txt
In the clustered/common/build.gradle file I added a dependency on core.  However there is probably a better solution to get access to org.ehcache.core.HumanReadable from the clustererd:common module.  Any suggestions?  Perhaps another location for org.ehcache.core.HumanReadable?
=> Issue #2078 adds missing properties to ehcache configuration

clustered/client/src/test/java/org/ehcache/clustered/client/internal/UnitTestConnectionService.java
This is an attempt to fix `UnitTestConnectionService`. It might destroy a manager before the cache entity. Which causes an exception. It works but it might hide the root cause. Maybe destroying the manager first should work.
=> Destroy entities in reverse order of creation

.gitignore, clustered/client/src/main/java/org/ehcache/clustered/client/internal/store/ClusteredStore.java, clustered/client/src/main/java/org/ehcache/clustered/client/internal/store/ClusteredValueHolder.java, clustered/client/src/main/java/org/ehcache/clustered/client/internal/store/ResolvedChain.java, clustered/client/src/main/java/org/ehcache/clustered/client/internal/store/operations/BaseKeyValueOperation.java, clustered/client/src/main/java/org/ehcache/clustered/client/internal/store/operations/ChainResolver.java, clustered/client/src/main/java/org/ehcache/clustered/client/internal/store/operations/Operation.java, clustered/client/src/test/java/org/ehcache/clustered/client/ClusteredCacheExpirationTest.java, clustered/client/src/test/java/org/ehcache/clustered/client/internal/UnitTestConnectionService.java, clustered/client/src/test/java/org/ehcache/clustered/client/internal/store/ClusteredStoreTest.java, clustered/client/src/test/java/org/ehcache/clustered/client/internal/store/EventualServerStoreProxyTest.java, clustered/client/src/test/java/org/ehcache/clustered/client/internal/store/operations/ChainResolverTest.java, clustered/server/src/main/java/org/ehcache/clustered/server/store/ClusterTierActiveEntity.java, core/src/main/java/org/ehcache/core/events/CacheEvents.java, core/src/test/java/org/ehcache/core/events/CacheEventsTest.java, impl/src/main/java/org/ehcache/impl/config/persistence/CacheManagerPersistenceConfiguration.java, impl/src/main/java/org/ehcache/impl/internal/store/tiering/TieredStore.java, integration-test/src/test/java/org/ehcache/integration/util/JavaExec.java, management/src/main/java/org/ehcache/management/cluster/DefaultClusteringManagementService.java
Backport of:
* #2050 Infinite local expiry with cluster tier
* #2073 Immediate expiry on middle offheap tier
* #2089 Cache closing sequence
* Misc fixes
=> [release/3.3] Backport fixes

build.gradle, buildSrc/src/main/groovy/EhPomGenerate.groovy
The `generatePomFileForMavenJavaPublication` task is dynamic and added
late, so anything that wants to depend on it must do so at the last
moment.
Also added a task graph visualisation plugin
=> Fix #2114 Resolve task dependency declaration

clustered/integration-test/src/test/java/org/ehcache/clustered/replication/BasicClusteredCacheOpsReplicationMultiThreadedTest.java, clustered/integration-test/src/test/java/org/ehcache/clustered/replication/DuplicateTest.java, clustered/server/src/main/java/org/ehcache/clustered/server/store/ClusterTierPassiveEntity.java
The PR should be 3.4 compatible.
Two things I noticed that I would like advice on:
* Comment "Reaching here means a lifecycle or sync operation failed" is talking about lifecycle. But no lifecycle message is handled. Only sync messages
* PassiveReplication messages are logging errors and sync messages are throwing an exception. It feels odd. Is that normal?
=> Return the real response from StateRepositoryMessages (close #2120)

transactions/src/main/java/org/ehcache/transactions/xa/internal/SoftLockValueCombinedSerializer.java, transactions/src/main/java/org/ehcache/transactions/xa/internal/StatefulSoftLockValueCombinedSerializer.java, transactions/src/main/java/org/ehcache/transactions/xa/internal/XAStore.java, transactions/src/test/java/org/ehcache/transactions/xa/integration/StatefulSerializerTest.java, transactions/src/test/java/org/ehcache/transactions/xa/internal/XAStoreProviderTest.java
The way the serializers were wired hid the fact that the underlying
Store may have to initialize a stateful one.
=> [release/3.4] Fix #2159 Proper support of StatefulSerializer in XAStore

transactions/src/main/java/org/ehcache/transactions/xa/internal/SoftLockValueCombinedSerializer.java, transactions/src/main/java/org/ehcache/transactions/xa/internal/StatefulSoftLockValueCombinedSerializer.java, transactions/src/main/java/org/ehcache/transactions/xa/internal/XAStore.java, transactions/src/test/java/org/ehcache/transactions/xa/integration/StatefulSerializerTest.java, transactions/src/test/java/org/ehcache/transactions/xa/internal/XAStoreProviderTest.java
The way the serializers were wired hid the fact that the underlying
Store may have to initialize a stateful one.
=> [release/3.3] Fix #2159 Proper support of StatefulSerializer in XAStore

clustered/server/src/main/java/org/ehcache/clustered/server/internal/messages/EhcacheMessageTrackerMessage.java, clustered/server/src/main/java/org/ehcache/clustered/server/internal/messages/EhcacheSyncMessageCodec.java, clustered/server/src/main/java/org/ehcache/clustered/server/store/ClusterTierPassiveEntity.java
This reverts commit 89995d8ae27681fd021214869b23d110d7066702.
On the 3.5 line, the backward compatible handling is no longer needed.
=> Revert "Issue #2122 Backward compatibility with 3.4.0"

impl/src/main/java/org/ehcache/impl/internal/concurrent/ConcurrentHashMap.java, impl/src/main/java/org/ehcache/impl/internal/store/heap/Backend.java, impl/src/main/java/org/ehcache/impl/internal/store/heap/KeyCopyBackend.java, impl/src/main/java/org/ehcache/impl/internal/store/heap/OnHeapStore.java, impl/src/main/java/org/ehcache/impl/internal/store/heap/SimpleBackend.java, impl/src/test/java/org/ehcache/impl/internal/concurrent/ConcurrentHashMapTest.java, transactions/src/test/java/org/ehcache/transactions/xa/internal/XAStoreProviderTest.java
A `List` does the job perfectly and removes all the hashing at insertion, the slow traversal and the superior object allocation
=> Using a HashMap to return the invalidated values is a bit heavyweight since we never use the map capabilities

107/src/main/java/org/ehcache/jsr107/Eh107Cache.java, 107/src/test/java/org/ehcache/docs/EhCache107ConfigurationIntegrationDocTest.java, api/src/main/java/org/ehcache/config/CacheConfiguration.java, api/src/test/java/org/ehcache/expiry/DurationTest.java, api/src/test/java/org/ehcache/expiry/ExpirationsTest.java, clustered/integration-test/src/test/java/org/ehcache/clustered/replication/DuplicateTest.java, core/src/main/java/org/ehcache/core/Ehcache.java, core/src/main/java/org/ehcache/core/EhcacheBase.java, core/src/main/java/org/ehcache/core/EhcacheRuntimeConfiguration.java, core/src/main/java/org/ehcache/core/EhcacheWithLoaderWriter.java, core/src/main/java/org/ehcache/core/InternalCache.java, core/src/main/java/org/ehcache/core/config/BaseCacheConfiguration.java, core/src/main/java/org/ehcache/core/config/ExpiryUtils.java, core/src/test/java/org/ehcache/core/EhcacheBasicCrudBase.java, impl/src/main/java/org/ehcache/config/builders/CacheConfigurationBuilder.java, impl/src/main/java/org/ehcache/config/builders/UserManagedCacheBuilder.java, impl/src/test/java/org/ehcache/config/builders/CacheManagerBuilderTest.java, impl/src/test/java/org/ehcache/docs/Ehcache3.java, xml/src/main/java/org/ehcache/xml/XmlConfiguration.java, xml/src/test/java/com/pany/ehcache/DeprecatedExpiry.java, xml/src/test/java/org/ehcache/xml/XmlConfigurationTest.java
This is the first step to mutualize the code between Ehcache and EhcacheWithLoaderWriter. A lot more can be done but at least we now have a starting point. This mutualization will be highly useful for implementing resilience.
=> Ehcache base class to mutualize basic and loader-writer code

clustered/client/src/main/java/org/ehcache/clustered/client/internal/config/xml/ClusteringServiceConfigurationParser.java
This PR fixes below findbugs error by throwing XmlConfigurationException in default case. Please review. let me know if any changes needed. 
```xml
<BugInstance type="SF_SWITCH_NO_DEFAULT" priority="2" rank="19" abbrev="SF" category="STYLE">
<Class classname="org.ehcache.clustered.client.internal.config.xml.ClusteringServiceConfigurationParser">
<SourceLine classname="org.ehcache.clustered.client.internal.config.xml.ClusteringServiceConfigurationParser" start="64" end="261" sourcefile="ClusteringServiceConfigurationParser.java" sourcepath="org/ehcache/clustered/client/internal/config/xml/ClusteringServiceConfigurationParser.java"/>
</Class>
<Method classname="org.ehcache.clustered.client.internal.config.xml.ClusteringServiceConfigurationParser" name="parseServiceCreationConfiguration" …
```
=> Fix findbugs error in ClusteringServiceConfigurationParser.java

107/build.gradle, 107/src/main/java/org/ehcache/jsr107/Eh107CacheManager.java, 107/src/main/java/org/ehcache/jsr107/EventListenerAdaptors.java, 107/src/tck/resources/ExcludeList, 107/src/test/java/org/ehcache/jsr107/Eh107CacheTypeTest.java, gradle.properties
PR to be ready for JCache 1.1 when it gets released as supporting it for Ehcache 3.5 would be ideal.
PR should fail to build until we can reference a released version though.
=> Support JCache 1.1.0

core-spi-test/src/main/java/org/ehcache/internal/store/StoreBulkComputeIfAbsentTest.java, core-spi-test/src/main/java/org/ehcache/internal/store/StoreBulkComputeTest.java, core-spi-test/src/main/java/org/ehcache/internal/store/StoreComputeIfAbsentTest.java, core-spi-test/src/main/java/org/ehcache/internal/store/StoreComputeTest.java, core/src/main/java/org/ehcache/core/exceptions/StorePassThroughException.java, core/src/test/java/org/ehcache/core/exceptions/StorePassThroughExceptionTest.java, impl/src/main/java/org/ehcache/impl/internal/store/tiering/TieredStore.java
It is expected that StorePassThroughExceptions thrown are supposed to have their cause being thrown in the end instead of being wrapped in a StoreAccessException.
=> Test that StorePassThroughExceptions are handled correctly

clustered/integration-test/src/test/java/org/ehcache/clustered/management/ClusteringManagementServiceTest.java, clustered/server/src/main/java/org/ehcache/clustered/server/management/PoolStatisticsManagementProvider.java, core/src/main/java/org/ehcache/core/spi/service/StatisticsService.java, core/src/main/java/org/ehcache/core/spi/service/StatisticsServiceConfiguration.java, core/src/main/java/org/ehcache/core/statistics/CacheStatistics.java, gradle.properties, impl/src/main/java/org/ehcache/impl/internal/statistics/DefaultCacheStatistics.java, impl/src/main/java/org/ehcache/impl/internal/statistics/DefaultStatisticsService.java, impl/src/main/java/org/ehcache/impl/internal/statistics/DefaultStatisticsServiceConfiguration.java, impl/src/main/java/org/ehcache/impl/internal/statistics/DefaultStatisticsServiceFactory.java, impl/src/test/java/org/ehcache/impl/internal/statistics/DefaultCacheStatisticsTest.java, impl/src/test/java/org/ehcache/impl/internal/statistics/DefaultStatisticsServiceConfigurationTest.java, impl/src/test/java/org/ehcache/impl/internal/statistics/DefaultStatisticsServiceFactoryTest.java, management/src/main/java/org/ehcache/management/providers/statistics/StandardEhcacheStatistics.java, management/src/test/java/org/ehcache/management/registry/DefaultManagementRegistryServiceTest.java
Adds `Cache:GetLatency` stat. 
A stat name is linked to a list of samples. For the moment in Ehcache, every stat collection reads a value and returns a sample. So for the moment, at each collection, we had 1 and only 1 sample generated for each stat, at the time of collect.
For the `Cache:GetLatency` stat, this is different. Ehcache will hold a history of by default 7200 samples, each sample being the latency aggregated (by maximum) over a 500ms window. So supposing there constantly some operations in Ehcache, this leads to a history of 1-hour.
At collect time (which is by default each 10 sec), it is possible that the `Cache:GetLatency` stat is not returned if there has been no operation called during the last 10 sec.
So for each collect of stats, `Cache:GetLatency` might return no …
=>  Close #2187: Latency statistics (Cache:GetLatency)

gradle.properties
Brings m&m bugfix (https://github.com/Terracotta-OSS/terracotta-platform/pull/457).
Note: build will fail because `5.4.1-pre7` is still releasing.
=> Upgrade to platform 5.4.1-pre7

clustered/integration-test/src/test/java/org/ehcache/clustered/OversizedCacheOpsTest.java, clustered/server/src/main/java/org/ehcache/clustered/server/ServerStoreImpl.java
Avoid the effect of clearing the cache if the user tries to put an object that is bigger than the cache.
=> Fix #2214 : Handle very large puts that may not fit the cache

clustered/integration-test/src/test/java/org/ehcache/clustered/replication/OversizedCacheOpsPassiveTest.java, clustered/server/src/main/java/org/ehcache/clustered/server/internal/messages/PassiveReplicationMessage.java, clustered/server/src/main/java/org/ehcache/clustered/server/offheap/OffHeapChainMap.java, clustered/server/src/main/java/org/ehcache/clustered/server/store/ClusterTierActiveEntity.java
Empty chains may get replicated due to possibility of eviction between calls on the active.
=> Fix #2204 : Handle empty chains that may get replicated

clustered/server/src/main/java/org/ehcache/clustered/server/offheap/OffHeapChainMap.java, clustered/server/src/main/java/org/ehcache/clustered/server/offheap/OffHeapServerStore.java, clustered/server/src/main/java/org/ehcache/clustered/server/store/ClusterTierPassiveEntity.java, clustered/server/src/test/java/org/ehcache/clustered/server/offheap/ChainMapTest.java, clustered/server/src/test/java/org/ehcache/clustered/server/store/ClusterTierPassiveEntityTest.java
Currently can only reproduce OSME in passive while putting, so the key is removed in a nested catch clause in OffHeapServerStore#put, and the exception is rethrown to be caught and logged in ClusterTierPassiveEntity#invokePassiveInternal. Not sure whether the same should be done in other methods potentially throwing OSME, e.g. in OffHeapServerStore#replaceAtHead - can't reproduce it there since the failure results in a successful eviction.
=> Handling OSME in passive: remove the key and catch.

clustered/client/src/main/java/org/ehcache/clustered/client/internal/store/ClusteredStore.java, clustered/client/src/test/java/org/ehcache/clustered/client/internal/store/ClusteredStoreTest.java, core/src/main/java/org/ehcache/core/EhcacheManager.java, core/src/main/java/org/ehcache/core/config/store/StoreStatisticsConfiguration.java, core/src/main/java/org/ehcache/core/internal/store/StoreConfigurationImpl.java, core/src/main/java/org/ehcache/core/spi/service/ServiceUtils.java, core/src/main/java/org/ehcache/core/spi/store/Store.java, core/src/test/java/org/ehcache/core/spi/service/ServiceUtilsTest.java, impl/src/main/java/org/ehcache/impl/internal/statistics/DefaultTierStatistics.java, impl/src/main/java/org/ehcache/impl/internal/statistics/StatsUtils.java, impl/src/main/java/org/ehcache/impl/internal/store/basic/BaseStore.java, impl/src/main/java/org/ehcache/impl/internal/store/disk/OffHeapDiskStore.java, impl/src/main/java/org/ehcache/impl/internal/store/heap/OnHeapStore.java, impl/src/main/java/org/ehcache/impl/internal/store/offheap/AbstractOffHeapStore.java, impl/src/main/java/org/ehcache/impl/internal/store/offheap/OffHeapStore.java, impl/src/test/java/org/ehcache/impl/internal/statistics/DefaultCacheStatisticsTest.java, impl/src/test/java/org/ehcache/impl/internal/statistics/DefaultTierStatisticsDisabledTest.java, impl/src/test/java/org/ehcache/impl/internal/statistics/DefaultTierStatisticsTest.java, impl/src/test/java/org/ehcache/impl/internal/statistics/StatsUtilsTest.java, impl/src/test/java/org/ehcache/impl/internal/store/disk/OffHeapDiskStoreTest.java, integration-test/src/test/java/org/ehcache/integration/StoreStatisticsTest.java, integration-test/src/test/java/org/ehcache/integration/statistics/TierCalculationTest.java, management/src/test/java/org/ehcache/management/providers/statistics/StandardEhCacheStatisticsQueryTest.java, management/src/test/java/org/ehcache/management/registry/DefaultManagementRegistryServiceTest.java
Seems to give a 7% speed optimization
=> Disable store statistics when having only one tier configured

clustered/client/src/main/java/org/ehcache/clustered/client/internal/ClusterTierManagerClientEntityFactory.java, clustered/client/src/main/java/org/ehcache/clustered/client/internal/service/ConnectionState.java, clustered/client/src/main/java/org/ehcache/clustered/client/internal/service/DefaultClusteringService.java, clustered/integration-test/src/test/java/org/ehcache/clustered/ClusterTierManagerClientEntityFactoryIntegrationTest.java, docs/build.gradle
This PR addresses the issue where a VoltronReadWriteLockEntity for a given cluster tier manager entity may remain in the system even after the cluster tier manager entity has been destroyed.
=> Fix #2426 : Abandon leadership if any is acquired before closing conn

clustered/client/src/main/java/org/ehcache/clustered/client/internal/ClusterTierManagerClientEntityFactory.java, clustered/client/src/main/java/org/ehcache/clustered/client/internal/store/ClusterTierClientEntityService.java, clustered/client/src/main/java/org/ehcache/clustered/client/internal/store/ClusterTierUserData.java, clustered/client/src/main/java/org/ehcache/clustered/client/internal/store/SimpleClusterTierClientEntity.java, clustered/client/src/test/java/org/ehcache/clustered/client/internal/UnitTestConnectionService.java, clustered/client/src/test/java/org/ehcache/clustered/client/internal/store/SimpleClusterTierClientEntityTest.java
By making timeouts final, it is also ensured that any out of band request (such as clientinvalidatehash) coming from the server the moment the client connects will always see correct timeouts and store identifier.
=> Fix #2447 : prevent race where clientinvalidatehash sees default timeouts instead of configured timeouts

core/src/main/java/org/ehcache/core/internal/service/ServiceLocator.java, core/src/test/java/org/ehcache/core/internal/service/ServiceLocatorTest.java
This is the simplest way I've found to ignore optional dependencies.
=> Closes #2451 - ignore unresolvable optional dependencies that are present on the classpath

gradle.properties
In the context of https://github.com/ehcache/ehcache3/issues/2468 , use final versions of terracotta modules , on top of internal25, aka commit 173d990d859b0b3ac98255d826662a510d8eae0f
=> Use final releases of tc modules

api/src/main/java/org/ehcache/spi/service/ServiceCreationConfigurationProvider.java, clustered/integration-test/src/test/java/org/ehcache/clustered/management/AbstractClusteringManagementTest.java, clustered/integration-test/src/test/java/org/ehcache/clustered/management/ManagementActivator.java, clustered/integration-test/src/test/resources/META-INF/services/org.ehcache.spi.service.ServiceCreationConfigurationProvider, clustered/integration-test/src/test/resources/simpleConfiguration.txt, impl/src/main/java/org/ehcache/config/builders/ConfigurationBuilder.java
We have the requirement to be able to automatically configure a management registry in some case.
So this PR is to add the ability to provide within the classpath a configuration provider that would be discovered and add configs if they are not already there through programmatic or xml config.
This PR is not complete:
- I'll send an email for more details and use case
- If this solution is good, we have to decide where to put the provider interface and depending on this what we document
=> Ability to autoconfigure Ehcache

core/src/main/java/org/ehcache/core/spi/store/AbstractValueHolder.java, impl/src/main/java/org/ehcache/impl/internal/store/heap/OnHeapStore.java, impl/src/main/java/org/ehcache/impl/internal/store/heap/OnHeapStrategy.java, impl/src/test/java/org/ehcache/impl/internal/store/heap/OnHeapStrategyTest.java, integration-test/src/test/java/org/ehcache/integration/OnHeapEvictionStrategyTest.java
This gives about 5% performance gain when no expiration is set and the SystemTimeSource is used. To get better, some further work is required on the `OnHeapValueHolder`.
=> Use an expiration strategy depending on expiration policy

core/src/test/java/org/ehcache/core/util/ClassLoadingTest.java, xml/src/main/java/org/ehcache/xml/XmlConfiguration.java, xml/src/test/java/org/ehcache/xml/XmlConfigurationTest.java, xml/src/test/resources/configs/pretty-typed-caches.xml
The only wrinkle that I can see with this is that we don't map back to the pretty class names when marshaling a configuration out to XML.
=> Fixes #2345 : Allow Java Language style syntax for arrays, primitives and inner classes

gradle.properties
This update brings the switch to runnel for the dynamic topology entity.
Note: model is still annotated with jackson annotations, which will create some warnings and fail when compiling with `-Werror`.
There is a WIP PR in tc-platform (https://github.com/Terracotta-OSS/terracotta-platform/pull/716) that is removing all annotations from the model classes and moves them to jackson mixins. This PR will be ready tomorrow I hope but it might be to late for the XPC, that is why we can use the `5.8.0-pre5` release at the moment.
=> Upgrade tc-platform to 5.8.0-pre5

clustered/clustered-dist/build.gradle, gradle.properties
Upgrade tc-platform to 5.8.0-pre9:
* TDB-4990: Refactoring of json wiring in dynamic config (https://github.com/Terracotta-OSS/terracotta-platform/pull/716)
* Added `<optional>` in dependencies so that felix can generate the right "resolution:=optional" attribute in the Import-Package manifest entry (https://github.com/Terracotta-OSS/terracotta-platform/pull/729)
=> Upgrade tc-platform to 5.8.0-pre9

clustered/integration-test/src/test/java/org/ehcache/clustered/NoOffheapTest.java, clustered/server/service/src/main/java/org/ehcache/clustered/server/state/EhcacheStateServiceProvider.java, gradle.properties
In relation to: https://github.com/Terracotta-OSS/terracotta-platform/pull/1006
```
> start-tc-server.sh
> start-tc-server.sh -auto-activate
> start-tc-server.sh -config-file ...
> start-tc-server.sh -auto-activate -config-file ...
```
Config file with/without offheap-resources.
=> Support starting with diagnostic mode and without offheap resources

build.gradle
Significant increase, however, at this time sonatype is taking a very long time to close repositories (>30 minutes)
=> Nexus staging plugin increase timeout (daggy 3.9)

demos/build.gradle, gradle.properties
This commit updates dependency versions to adopt upstream
dependencies using version ranges for logging components.
In addition, this commit pins the following versions:
* slf4j 1.7.36
* terracotta-utilities 0.0.15
Except for demos, the logback version is inherited from
terracotta-core and terracotta-platform.
=> Update dependency versions

gradle.properties
~~This PR is based on @cljohnso's one which has to be merged first: #3044~~
=> [3.9] terracottaPlatformVersion = 5.9.7 (fix required for docker container logging)

buildSrc/src/main/groovy/EhDistribute.groovy
This update is a circumvention for an XJC plugin fault that causes an
XJC-generated sourceSet to be observed twice during generation of a
source jar.
(The fault was apparently hidden by earlier Gradle versions ...)
This commit is DAGGY.
=> Prevent failure during sourceJar task

clustered/clustered-dist/build.gradle, clustered/clustered-dist/src/assemble/README.txt, clustered/clustered-dist/src/assemble/docker/README.md, clustered/clustered-dist/src/assemble/docker/buildAndTest.groovy, clustered/clustered-dist/src/assemble/docker/config-tool/Dockerfile, clustered/clustered-dist/src/assemble/docker/config-tool/README.md, clustered/clustered-dist/src/assemble/docker/config-tool/entrypoint.sh, clustered/clustered-dist/src/assemble/docker/server/Dockerfile, clustered/clustered-dist/src/assemble/docker/server/README.md, clustered/clustered-dist/src/assemble/docker/server/entrypoint.sh, clustered/clustered-dist/src/assemble/docker/voter/Dockerfile, clustered/clustered-dist/src/assemble/docker/voter/README.md, clustered/clustered-dist/src/assemble/docker/voter/entrypoint.sh
This PR adds a docker folder in the Ehcache kit with instructions on how to build the 3 images, plus the README to place on Docker Hub.
- ~~`ehcache-server`~~ `ehcache-terracotta-server`
- ~~`terracotta-voter-oss`~~ `ehcache-terracotta-voter`
- ~~`terracotta-config-tool-oss`~~ `ehcache-terracotta-config-tool`
**Notes:**
- I have manually tested them, since it is not yet possible to add docker tests in Ehcache
- Naming still to be discussed
- Gradle / Docker build scripts and deployment to hub.docker.com still to be done in a subsequent PR
- A cherry-pick to the `release/3.9` branch can be made once merged
Some ref regarding these required perm / `uid:0` with OpenShift (also others): https://docs.openshift.com/container-platform/3.11/creating_images/guidelines.html#openshift-specific-guidel …
=> [3.9] Docker files for Ehcache

clustered/ehcache-clustered/build.gradle, clustered/ehcache-clustered/src/assemble/README.txt, clustered/ehcache-clustered/src/assemble/docker/README.md, clustered/ehcache-clustered/src/assemble/docker/buildAndTest.groovy, clustered/ehcache-clustered/src/assemble/docker/config-tool/Dockerfile, clustered/ehcache-clustered/src/assemble/docker/config-tool/README.md, clustered/ehcache-clustered/src/assemble/docker/config-tool/entrypoint.sh, clustered/ehcache-clustered/src/assemble/docker/server/Dockerfile, clustered/ehcache-clustered/src/assemble/docker/server/README.md, clustered/ehcache-clustered/src/assemble/docker/server/entrypoint.sh, clustered/ehcache-clustered/src/assemble/docker/voter/Dockerfile, clustered/ehcache-clustered/src/assemble/docker/voter/README.md, clustered/ehcache-clustered/src/assemble/docker/voter/entrypoint.sh
This PR adds a docker folder in the Ehcache kit with instructions on how to build the 3 images, plus the README to place on Docker Hub.
- ~~`ehcache-server`~~ `ehcache-terracotta-server`
- ~~`terracotta-voter-oss`~~ `ehcache-terracotta-voter`
- ~~`terracotta-config-tool-oss`~~ `ehcache-terracotta-config-tool`
**Notes:**
- I have manually tested them, since it is not yet possible to add docker tests in Ehcache
- Naming still to be discussed
- Gradle / Docker build scripts and deployment to hub.docker.com still to be done in a subsequent PR
- A cherry-pick to the `release/3.9` branch can be made once merged
Some ref regarding these required perm / `uid:0` with OpenShift (also others): https://docs.openshift.com/container-platform/3.11/creating_images/guidelines.html#openshift-specific-guidel …
=> [master] Docker files for Ehcache

ehcache-api/src/main/java/org/ehcache/spi/loaderwriter/WriteBehindProvider.java, ehcache-impl/src/main/java/org/ehcache/impl/internal/loaderwriter/writebehind/BatchingLocalHeapWriteBehindQueue.java, ehcache-impl/src/main/java/org/ehcache/impl/internal/loaderwriter/writebehind/NonBatchingLocalHeapWriteBehindQueue.java, ehcache-impl/src/main/java/org/ehcache/impl/internal/loaderwriter/writebehind/StripedWriteBehind.java, ehcache-impl/src/main/java/org/ehcache/impl/internal/loaderwriter/writebehind/WriteBehindProviderFactory.java, ehcache-impl/src/main/java/org/ehcache/impl/internal/loaderwriter/writebehind/operations/BatchOperation.java, ehcache-impl/src/main/java/org/ehcache/impl/internal/loaderwriter/writebehind/operations/DeleteAllOperation.java, ehcache-impl/src/main/java/org/ehcache/impl/internal/loaderwriter/writebehind/operations/WriteAllOperation.java, ehcache-impl/src/main/java/org/ehcache/impl/internal/store/loaderwriter/LoaderWriterStoreProvider.java, ehcache-impl/src/test/java/org/ehcache/impl/internal/loaderwriter/writebehind/AbstractWriteBehindTestBase.java, ehcache-impl/src/test/java/org/ehcache/impl/internal/loaderwriter/writebehind/WriteBehindFailuresTest.java, ehcache-impl/src/test/java/org/ehcache/impl/internal/loaderwriter/writebehind/WriteBehindProviderFactoryTest.java
Handle the failure which may occur during following write-behind scenarios and removed failed entries from cache.
- Batching
- NonBatching
=> issue-628 Handled failures which might occur during write-behind

build-logic/src/main/java/org/ehcache/build/conventions/DeployConvention.java, build.gradle, gradle.properties, settings.gradle
Old plugin is no longer supported and new one *should* work better.
Removed convention code that is hopefully unnecessary.
=> Switch to gradle nexus publish plugin (Daggy master)

build.gradle, gradle.properties, settings.gradle
=> Switch to gradle nexus publish plugin (3.9 Daggy)

build.gradle, buildSrc/src/main/groovy/EhDeploy.groovy, buildSrc/src/main/groovy/EhPomMangle.groovy, gradle.properties, settings.gradle
gradle 6 stuff in ehcache3 isn't currently fully compatible, this will have to wait until that's fixed.
=> Revert upgrade to nexus-publish plugin 
